Add client/AccountID support into Adoppler adapter
prebid/prebid-server-java pull request #1010
Opened 2020-11-16 01:35 UTC by snahornyi

2020-11-18 13:19 UTC, DGarbar requested changes

2020-11-18 13:19 UTC, DGarbar commented on src/main/java/org/prebid/server/bidder/adoppler/AdopplerBidder.java
> +
Put all in the try catch

2020-11-18 15:08 UTC, DGarbar approved these changes

2020-11-19 12:32 UTC, rpanchyk approved these changes

2020-11-19 12:32 UTC, merged