Use POST, preserve original user agent and user ip in the headers
prebid/prebid-server-java pull request #1020
Opened 2020-11-18 14:37 UTC by sander-adhese

2020-11-19 13:37 UTC, rpanchyk requested changes

2020-11-19 13:37 UTC, rpanchyk commented on src/main/java/org/prebid/server/bidder/adhese/AdheseBidder.java
> +        return HttpUtil.headers();
Pls return `headers` instead.

2020-11-19 13:43 UTC, rpanchyk commented
Do we have any time frames for merging and rolling out this PR?
i mean when new POST bidder interface will be ready.

2020-11-19 14:45 UTC, sander-adhese commented
> @sander-adhese Do we have any time frames for merging and rolling out this PR?
> i mean when new POST bidder interface will be ready.

The POST bidder interface is already available - so we aim for the earliest window (I believe early December).

2020-11-20 09:21 UTC, rpanchyk approved these changes

2020-11-20 09:23 UTC, merged