Add account CCPA enabled and per-request-type enabled flags
prebid/prebid-server-java pull request #1044
Opened 2020-12-02 13:06 UTC by snahornyi

2020-12-03 12:27 UTC, DGarbar requested changes
@rpanchyk  I Think this feature is also connected with `Account.enforceCcpa`. 
Probably it is better to migrate this to `Account.ccpa.enabled`. 
So we need to change DB schema as well. But we can merge this ticket as it is, bc current workflow is no changed

2020-12-03 12:27 UTC, DGarbar commented on src/main/java/org/prebid/server/auction/PrivacyEnforcementService.java
> +    private Boolean isCCPAEnabled(Account account) {
Use camelCase

2020-12-03 12:27 UTC, DGarbar commented on src/main/java/org/prebid/server/auction/PrivacyEnforcementService.java
> +                accountCcpaConfig != null ? accountCcpaConfig.getEnabled() : null;
redundant /n

2020-12-03 12:27 UTC, DGarbar commented on src/main/java/org/prebid/server/auction/PrivacyEnforcementService.java
> +
redundant /n

2020-12-03 12:27 UTC, DGarbar commented on src/main/java/org/prebid/server/auction/PrivacyEnforcementService.java
> +        final Boolean accountCCPAEnabled =
redundant /n

2020-12-03 12:27 UTC, DGarbar commented on src/main/java/org/prebid/server/auction/PrivacyEnforcementService.java
> +            return ObjectUtils.firstNonNull(accountCCPAEnabled, ccpaEnforce);
Missed  `eturn ObjectUtils.firstNonNull(accountCCPAEnabled, account.getEnforceCcpa(), ccpaEnforce);`

2020-12-03 13:57 UTC, DGarbar commented
Current code is OK. But I think we need to change JdbcApplicationSettings and DB. Lets wait for Ruslan

2021-08-13 10:36 UTC, rpanchyk approved these changes

2021-08-13 10:40 UTC, rpanchyk approved these changes

2021-08-13 10:42 UTC, merged