Add support for multi-imp requests in ttx bidder
prebid/prebid-server-java pull request #1069
Opened 2020-12-13 23:20 UTC by snahornyi

2021-01-25 14:51 UTC, DGarbar requested changes

2021-01-25 14:51 UTC, DGarbar commented on src/main/java/org/prebid/server/bidder/ttx/TtxBidder.java
> +        final ExtRequest reqExt = updateExtRequest(request.getExt());
Catch exception

2021-01-25 14:51 UTC, DGarbar commented on src/main/java/org/prebid/server/bidder/ttx/TtxBidder.java
> +                requests.add(makeRequest(request, imp, reqExt));
makeRequest seems redundant. 
Could you split it like. 
validateImp()
parseImpExt()
updateImp()
 createRequest()

2021-01-25 14:51 UTC, DGarbar commented on src/main/java/org/prebid/server/bidder/ttx/TtxBidder.java
> +    private HttpRequest<BidRequest> createRequest(BidRequest request,
redundant /n

2021-01-25 14:51 UTC, DGarbar commented on src/main/java/org/prebid/server/bidder/ttx/TtxBidder.java
> +    private static BidRequest updateRequest(BidRequest request, Imp requestImp, ExtRequest extRequest) {
seems redundant method

2021-01-25 15:13 UTC, DGarbar submitted a review, later dismissed

2021-01-25 15:36 UTC, DGarbar commented on src/main/java/org/prebid/server/proto/openrtb/ext/FlexibleExtension.java
> +    }
Let's discuss this approach

2021-01-27 12:56 UTC, rpanchyk submitted a review, later dismissed

2021-01-28 06:07 UTC, rpanchyk approved these changes

2021-01-28 06:07 UTC, merged