SKAdNetwork support: pass imp.ext.skan to bidders as is and treat it as a special field
prebid/prebid-server-java pull request #1097
Opened 2021-01-15 10:00 UTC by schernysh

2021-01-15 17:54 UTC, bretg requested changes

2021-01-15 17:54 UTC, bretg commented on src/main/java/org/prebid/server/auction/ExchangeService.java
> +    private static final String SKAN_EXT = "skan";
there was a typo in the original issue. this should be `skadn` instead of `skan`.

2021-02-19 11:22 UTC, rpanchyk submitted a review, later dismissed

2021-02-23 09:14 UTC, rpanchyk approved these changes

2021-02-23 09:29 UTC, merged