Update IX bidder to support all MediaTypes.
prebid/prebid-server-java pull request #1098
Opened 2021-01-15 10:21 UTC by DGarbar

Refactored code.
Url change is not needed.
Left code that fixes empty bid.w and bid.h

2021-01-15 10:52 UTC, DGarbar commented
Also they added passing of the request type for Legacy IxAddapter. 
This change require refactoring of our code logic. (To pass additional information to makeBids method), so it will be ignored due no actual requests to this endpoint

2021-01-15 13:04 UTC, rpanchyk requested changes

2021-01-15 13:04 UTC, rpanchyk commented on src/main/java/org/prebid/server/bidder/ix/IxBidder.java
> +    private static Site modifiedSite(Site site, ExtImpIx extImpIx) {
i'd suggest to name functions in imperative mood, like `modifySite(..)`
Pls check other fun-s below if agree.

2021-01-15 13:04 UTC, rpanchyk commented on src/main/java/org/prebid/server/bidder/ix/IxBidder.java
> +        final List<Format> formats = getFormats(banner);
Can `getFormats(..)` return null? This may cause NPE if so.

2021-01-18 10:20 UTC, rpanchyk commented on src/main/java/org/prebid/server/bidder/ix/IxBidder.java
> +        final List<Format> formats = getFormats(banner);
Agree.

2021-01-18 10:23 UTC, rpanchyk approved these changes

2021-01-18 10:24 UTC, merged