Prefer deals flag to determine winning bid comparison logic
prebid/prebid-server-java pull request #1182
Opened 2021-03-10 10:56 UTC by BraslavskiyAndrey

2021-03-11 14:04 UTC, DGarbar submitted a review, later dismissed

2021-05-26 13:42 UTC, rpanchyk requested changes

2021-05-26 13:42 UTC, rpanchyk commented on src/test/java/org/prebid/server/auction/WinningBidComparatorFactoryTest.java
> +        final BidInfo loverPriceBidInfo = givenBidInfo(1.0f);
Pls fix typo.
Check all other tests.

2021-05-26 13:42 UTC, rpanchyk commented on src/main/java/org/prebid/server/auction/BidResponseCreator.java
> +    private boolean preferDeals(ExtRequestTargeting targeting) {
Can be static.

2021-05-27 13:02 UTC, rpanchyk approved these changes

2021-05-27 13:02 UTC, merged