First cut of established hook interfaces
prebid/prebid-server-java pull request #1195
Opened 2021-03-22 09:59 UTC by schernysh

2021-03-22 10:14 UTC, rpanchyk requested changes

2021-03-22 10:14 UTC, rpanchyk commented on src/main/java/org/prebid/server/hooks/v1/auction/AuctionRequestHook.java
> +public interface AuctionRequestHook extends Hook<AuctionRequestPayload, AuctionInvocationContext> {
Pls reanme to `RawAuctionRequestHook`

2021-03-22 10:30 UTC, rpanchyk approved these changes

2021-03-22 10:34 UTC, merged

2021-03-22 13:20 UTC, muuki88 commented
What's the usage for this? I'm currently looking for something that let's us

- add bid floors dynamically within prebid server for all adapters
- add static targetings for AMP auctions ( `hb_source: "s2s"`  in our case )

Is this something that hook infrastructure is capable of?

2021-03-22 13:33 UTC, schernysh commented
Hey @muuki88,

This PR is the beginning of the journey to modularity: https://github.com/prebid/prebid-server/issues/1734. It's on an early stage so far so feel free to join this effort - you may want to start with reviewing PRD, feel free to ask questions and suggest also.

Addressing your questions - modularity is envisioned as a response to the needs similar to those you mentioned.

2021-03-22 15:04 UTC, muuki88 commented on src/main/java/org/prebid/server/hooks/v1/auction/AuctionRequestPayload.java
> +    BidRequest bidRequest();
Is the BidRequest mutable and can be modified the hook?

2021-03-22 15:05 UTC, muuki88 commented
Thanks a lot for the pointers. I'll take a look at the documents and see where I can give valuable feedback.

Regarding this PR. As an external contributor I would love to see more documentation on the interfaces and how they are supposed to work, what I need to do as an implementor and where I can take a look at the whole picture (e.g. the google doc).

2021-03-30 16:47 UTC, bretg commented
@muuki88 - thought I'd answered this, but maybe not

> add static targetings for AMP auctions ( hb_source: "s2s" in our case )

static AMP targets are supported -- https://docs.prebid.org/prebid-server/endpoints/openrtb2/pbs-endpoint-auction.html#custom-targeting-pbs-java-only