openx adapter: use bidfloor if set - prebid.js adapter behavior
prebid/prebid-server-java pull request #1218
Opened 2021-04-07 18:53 UTC by laurb9

- Fixes bug that set bidfloor to 0 when customFloor not given (so almost always)
- Implements behavior in https://github.com/prebid/Prebid.js/blob/master/modules/openxBidAdapter.js#L495
- for #1787

2021-04-08 09:39 UTC, snahornyi requested changes

2021-04-08 09:39 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/openx/OpenxBidder.java
> +            impBuilder.bidfloor(customFloor);
Please, add test for this case

2021-04-09 00:01 UTC, laurb9 commented
Added unit tests and simplified the code, passing bidfloor with fallback to customFloor.
I did notice that no other adapter gives priority to incoming bidfloor from the standard place, so we may revisit this choice.

2021-04-09 07:22 UTC, snahornyi approved these changes

2021-04-21 07:04 UTC, merged