beachfront: Changes to support real 204
prebid/prebid-server-java pull request #1230
Opened 2021-04-16 09:16 UTC by RodionOrets

2021-04-16 09:40 UTC, snahornyi requested changes

2021-04-16 09:40 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/beachfront/BeachfrontBidder.java
> +        requestBuilder.real204(true);
Can we move this to 173 line?

2021-04-16 09:40 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/beachfront/model/BeachfrontBannerRequest.java
> +    boolean real204;
we prefer to use wrapped types

2021-04-19 10:31 UTC, RodionOrets commented on src/main/java/org/prebid/server/bidder/beachfront/BeachfrontBidder.java
> +        requestBuilder.real204(true);
Done

2021-04-19 10:31 UTC, RodionOrets commented on src/main/java/org/prebid/server/bidder/beachfront/model/BeachfrontBannerRequest.java
> +    boolean real204;
Changed to `Boolean`

2021-04-19 10:38 UTC, snahornyi approved these changes

2021-04-21 07:07 UTC, merged