new adf bidder was added
prebid/prebid-server-java pull request #1288
Opened 2021-05-28 11:19 UTC by nickluck8

2021-05-31 08:29 UTC, muuki88 commented
@nickluck8 there's already an [AdForm bidder](https://github.com/prebid/prebid-server-java/blob/master/src/main/java/org/prebid/server/bidder/adform/AdformBidder.java) available.

Can you highlight the difference and which one should be chosen? From the implementation I can see that
the `adf` one uses the standard `OpenrtbBidder`, which is great. So in general it would be nice to know 

- can both adapters be used?
- is there a difference in formats, demand, future support?

2021-05-31 09:55 UTC, rpanchyk commented
@muuki88 seems `ADF` - `https://adx.adform.net/adx/openrtb` is OpenRTB exchange instead of `AdForm` - `https://adx.adform.net/adx` where custom GET request used.
So, it depends on publisher which one to use.

2021-05-31 10:21 UTC, snahornyi requested changes
Seems this PR should be updated, with this changes https://github.com/prebid/prebid-server/pull/1841

2021-06-01 10:28 UTC, snahornyi requested changes

2021-06-01 10:28 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/adf/AdfBidder.java
> +public class AdfBidder extends OpenrtbBidder<ExtImpAdf> {
Minor. 
```java
/**
 * Adf {@link Bidder} implementation.
 */
```

2021-06-01 10:28 UTC, snahornyi commented on src/test/resources/org/prebid/server/it/openrtb2/adf/test-auction-adf-request.json
> +  },
Can be removed

2021-06-01 10:28 UTC, snahornyi commented on src/test/resources/org/prebid/server/it/openrtb2/adf/test-adf-bid-request.json
> +          "mid": "1"
Let's remove tagId in auction request, and check that masterId is being added as tagid

2021-06-01 13:15 UTC, snahornyi approved these changes

2021-06-02 08:11 UTC, merged