add processing of imp.ext.data to mediagrid
prebid/prebid-server-java pull request #1293
Opened 2021-06-03 10:16 UTC by nickluck8

2021-06-03 10:39 UTC, snahornyi requested changes
Pls add unit tests

2021-06-03 10:39 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/grid/model/ExtImp.java
> +public class ExtImp {
In custom models we prefer to use names like {bidderName}modelName

2021-06-03 10:39 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/grid/GridBidder.java
> +        ExtImp extImp = mapper.mapper().convertValue(
Can be final

2021-06-03 10:39 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/grid/GridBidder.java
> +            ExtImp modifiedExtImp = ExtImp.of(extImp.getPrebid(),
Can be final, and also you create model with `of` constructor, just to change one value, lets use builder

2021-06-03 10:39 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/grid/GridBidder.java
> +                && StringUtils.isNotEmpty(extImp.getExtImpData().getAdServer().getAdSlot())) {
Lets extract adSlot, and then use if statement

2021-06-03 10:39 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/grid/GridBidder.java
> +            ObjectNode modifiedExt = mapper.mapper().valueToTree(
we can move it directly to imp building
`imp.toBuilder().ext(mapper.mapper().valueToTree(modifiedExtImp)).build()`

2021-06-03 12:18 UTC, snahornyi requested changes

2021-06-03 12:18 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/grid/GridBidder.java
> +        String adSlot = getAdSlot(gridExtImp);
Can be final, but also by saying extracting I mean that we can do something like
```java
final GridExtImp gridExtImp = mapper.mapper().convertValue(imp.getExt(), GridExtImp.class);
final GridExtImpData extImpData = gridExtImp != null ? gridExtImp.getGridExtImpData() : null;
final GridExtImpDataAdServer adServer = extImpData != null ? extImpData.getAdServer() : null;
final String adSlot = adServer != null ? adServer.getAdSlot() : null;

 if (StringUtils.isNotEmpty(adSlot)) {
```

2021-06-03 12:18 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/grid/GridBidder.java
> +        );
Can be one line

2021-06-03 12:18 UTC, snahornyi commented on src/test/java/org/prebid/server/bidder/grid/GridBidderTest.java
> +                .build();
Can be one line and also final

2021-06-03 12:44 UTC, snahornyi approved these changes

2021-06-03 16:24 UTC, rpanchyk requested changes

2021-06-03 16:24 UTC, rpanchyk commented on src/main/java/org/prebid/server/bidder/grid/GridBidder.java
> +        final GridExtImp gridExtImp = mapper.mapper().convertValue(imp.getExt(), GridExtImp.class);
This can potentially rise exception. Pls wrap with `try...catch` to throw `PreBidException`.

2021-06-03 16:24 UTC, rpanchyk commented on src/main/java/org/prebid/server/bidder/grid/model/GridExtImp.java
> +    GridExtImpData gridExtImpData;
Rename field to `data` so annotation not required.

2021-06-04 07:00 UTC, rpanchyk approved these changes

2021-06-04 14:13 UTC, snahornyi approved these changes

2021-06-04 14:14 UTC, merged