New bidder: Bidmachine
prebid/prebid-server-java pull request #1328
Opened 2021-06-22 10:09 UTC by nickluck8

2021-06-22 13:21 UTC, snahornyi requested changes
Pls rearrange methods due to call order

2021-06-22 13:21 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/bidmachine/BidmachineBidder.java
> +            if (bannerBattr != null && !hasRewardedBattr(bannerBattr)) {
In Go they always add 16 even if bannerBattr or VideoBattr is not present, check `ListUtils.defaultIfNull` or same method for banner and videoBattr resolving

2021-06-22 13:21 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/bidmachine/BidmachineBidder.java
> +        }
There is no such validation in go, and actually we don't need it, because we have Json validation schemas

2021-06-22 13:21 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/bidmachine/BidmachineBidder.java
> +        errors.add(BidderError.badServerResponse(String.format("Failed to find impression with id: %s", impId)));
In Go they use a bit another error message, and also they ignore `UndefinedMediaType` bids

2021-06-22 13:21 UTC, snahornyi commented on src/test/java/org/prebid/server/bidder/bidmachine/BidmachineBidderTest.java
> +                .containsExactly("https://127.0.0.1/path/1");
Can be used together like 
```java
assertThat(result.getValue()).hasSize(1)
                .extracting(HttpRequest::getUri)
                .containsExactly("https://127.0.0.1/path/1");
```

2021-06-22 13:21 UTC, snahornyi commented on src/test/java/org/prebid/server/bidder/bidmachine/BidmachineBidderTest.java
> +                .containsExactly("https://127.0.0.1/path/1");
Pls check for similar occurrences

2021-06-22 13:21 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/bidmachine/BidmachineBidder.java
> +                bannerBattr.add(16);
We will have UnsupportedOperationException if this method will be used to unmodifiable collection

2021-06-22 13:21 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/bidmachine/BidmachineBidder.java
> +                bannerBattr.add(16);
And also we should not change reference media types, as they will change every bid request

2021-06-22 13:21 UTC, snahornyi commented on src/test/java/org/prebid/server/bidder/bidmachine/BidmachineBidderTest.java
> +        List<Integer> requestBattr = new ArrayList<>();
Can be final, check for similar occurrences

2021-06-22 13:21 UTC, snahornyi commented on src/test/java/org/prebid/server/bidder/bidmachine/BidmachineBidderTest.java
> +        requestBattr.add(1);
better use `singletonList(1)`;

2021-06-22 13:21 UTC, snahornyi commented on src/test/java/org/prebid/server/bidder/bidmachine/BidmachineBidderTest.java
> +                .containsExactly(Arrays.asList(1, 16));
Flat extracting and then Arrays.asList can be omitted, check for similar occurrences

2021-06-22 13:21 UTC, snahornyi commented on src/test/resources/org/prebid/server/it/openrtb2/bidmachine/test-auction-bidmachine-request.json
> +{
Seems not all data from this file is necessary

2021-06-23 08:24 UTC, rpanchyk commented
Please remove call to cache in tests, see #1329

2021-06-23 08:31 UTC, snahornyi requested changes

2021-06-23 08:31 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/bidmachine/BidmachineBidder.java
> +        if (battr != null && !hasRewardedBattr(battr)) {
lets update method to be like 
```java
private static boolean isMissedRewardedBattr(List<Integer> battr) {
        return battr == null || !battr.contains(16);
    }
```

2021-06-23 08:31 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/bidmachine/BidmachineBidder.java
> +            final List<Integer> updatedBattr = new ArrayList<>(battr);
If battr is null, we should create collection and add 16, but in our case `new ArrayList<>(battr)` will throw NPE for this case

2021-06-23 08:31 UTC, snahornyi commented on src/test/java/org/prebid/server/bidder/bidmachine/BidmachineBidderTest.java
> +                        tuple(HttpUtil.X_OPENRTB_VERSION_HEADER.toString(), "2.5"));
can be one line

2021-06-23 08:31 UTC, snahornyi commented on src/test/java/org/prebid/server/bidder/bidmachine/BidmachineBidderTest.java
> +        assertThat(result.getErrors()).hasSize(1);
Should we check error message?

2021-06-23 08:31 UTC, snahornyi commented on src/test/java/org/prebid/server/bidder/bidmachine/BidmachineBidderTest.java
> +                .containsExactly("https://127.0.0.1/path/1");
Why you prefer to use separately?

2021-06-23 08:44 UTC, snahornyi commented
> Please remove call to cache in tests, see #1329

Already done

2021-06-25 11:28 UTC, snahornyi approved these changes

2021-06-25 12:47 UTC, merged