Add evolution bidder
prebid/prebid-server-java pull request #1354
Opened 2021-07-05 13:56 UTC by And1sS

2021-07-06 11:43 UTC, snahornyi requested changes

2021-07-06 11:43 UTC, snahornyi commented on src/test/resources/org/prebid/server/it/openrtb2/evolution/test-auction-evolution-request.json
> +        "evolution": {
From `go` name should be `e_volution`

2021-07-06 11:43 UTC, snahornyi commented on src/test/java/org/prebid/server/it/EvolutionTest.java
> +                response, singletonList("evolution"));
e_volution

2021-07-06 11:43 UTC, snahornyi commented on src/main/resources/bidder-config/evolution.yaml
> +      cookie-family-name: evolution
e_volution

2021-07-06 11:43 UTC, snahornyi commented on src/main/resources/bidder-config/evolution.yaml
> +  evolution:
e_volution

2021-07-06 11:43 UTC, snahornyi commented on src/main/java/org/prebid/server/spring/config/bidder/EvolutionConfiguration.java
> +    private static final String BIDDER_NAME = "evolution";
e_volution

2021-07-06 11:43 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/evolution/EvolutionBidder.java
> +    }
Let's prepare some updates for this methods
```java
 private List<BidderBid> bidsFromResponse(BidResponse bidResponse) {
        final SeatBid firstSeatBid = bidResponse.getSeatbid().get(0);
        return CollectionUtils.emptyIfNull(firstSeatBid.getBid()).stream()
                .filter(Objects::nonNull)
                .map(bid -> BidderBid.of(bid, getBidMediaType(bid.getExt()), bidResponse.getCur()))
                .collect(Collectors.toList());
    }

    private BidType getBidMediaType(JsonNode bidExt) {
        final JsonNode mediaTypeNode = bidExt != null ? bidExt.get("mediaType") : null;
        try {
            return ObjectUtils.defaultIfNull(mapper.mapper()
                    .convertValue(mediaTypeNode, BidType.class), BidType.banner);
        } catch (IllegalArgumentException e) {
            return BidType.banner;
        }
    }
```
Then EvolutionBidResponse class can be deleted

2021-07-06 11:43 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/evolution/EvolutionBidder.java
> +    }
Let's get rid of this method and put it's logic directly to `makeHttpRequests` method

2021-07-06 11:43 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/evolution/EvolutionBidder.java
> +    public Result<List<HttpRequest<BidRequest>>> makeHttpRequests(BidRequest request) {
Also pls add test that only one request should be created for all imps

2021-07-07 12:46 UTC, rpanchyk requested changes

2021-07-07 12:46 UTC, rpanchyk commented on src/main/java/org/prebid/server/bidder/evolution/model/EvolutionBidResponse.java
> +public class EvolutionBidResponse {
Do we need this model ?

2021-07-08 09:09 UTC, snahornyi commented on src/main/resources/bidder-config/evolution.yaml
> +      redirect-url: /setuid?bidder=e_volution&gdpr={{gdpr}}&gdpr_consent={{gdpr_consent}}&uid=[UID]
In redirect-url all this parameters should be present
`&gdpr={{gdpr}}&gdpr_consent={{gdpr_consent}}&us_privacy={{us_privacy}}`

2021-07-08 10:22 UTC, rpanchyk approved these changes

2021-07-08 10:23 UTC, snahornyi approved these changes

2021-07-08 10:42 UTC, merged