Add SaLunamedia bidder
prebid/prebid-server-java pull request #1364
Opened 2021-07-09 08:14 UTC by And1sS

2021-07-09 13:54 UTC, snahornyi requested changes

2021-07-09 13:54 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/salunamedia/SaLunamediaBidder.java
> +        if (firstBidType == null) {
It is possible case when we have ext, but not valid bidType, then we will have message `Missing BidExt`. Pls update this logic

2021-07-09 13:54 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/salunamedia/SaLunamediaBidder.java
> +    private BidType getBidType(ObjectNode node) {
Pls rename `node` to `bidExt`

2021-07-09 13:54 UTC, snahornyi commented on src/test/java/org/prebid/server/bidder/salunamedia/SaLunamediaBidderTest.java
> +    public void makeBidsShouldReturnOnlyFirstBid() throws JsonProcessingException {
makeBidsShouldReturnOnlyBidderBidWithFirstBid

2021-07-09 13:54 UTC, snahornyi commented on src/test/java/org/prebid/server/bidder/salunamedia/SaLunamediaBidderTest.java
> +                Bid.builder().impid("123").ext(mediaTypeObjectNode).build(), xNative, null));
Pls add for banner and video types too

2021-07-09 13:54 UTC, snahornyi commented on src/test/java/org/prebid/server/bidder/salunamedia/SaLunamediaBidderTest.java
> +    private static BidRequest givenBidRequest(Function<Imp.ImpBuilder, Imp.ImpBuilder> impCustomizer) {
This method is never used

2021-07-09 13:54 UTC, snahornyi commented on src/test/java/org/prebid/server/bidder/salunamedia/SaLunamediaBidderTest.java
> +        assertThat(result.getErrors()).containsExactlyInAnyOrder(BidderError.badServerResponse("Missing BidExt"));
ContainsExactly is enough

2021-07-09 14:21 UTC, snahornyi submitted a review, later dismissed

2021-07-12 08:49 UTC, rpanchyk commented on src/test/java/org/prebid/server/bidder/salunamedia/SaLunamediaBidderTest.java
> +    private static final String ENDPOINT_URL = "https://mobile.mng-ads.com/bidrequest{{ZoneID}}";
Minor. Pls don't use real urls in unit tests.

2021-07-12 09:17 UTC, merged