Review Ix bidder
prebid/prebid-server-java pull request #1372
Opened 2021-07-15 16:30 UTC by snahornyi

2021-07-19 16:05 UTC, rpanchyk requested changes

2021-07-19 16:05 UTC, rpanchyk commented on src/main/java/org/prebid/server/bidder/ix/IxBidder.java
> +    private String updateAdm(Response response, boolean isV11) {
i'd suggest to inline this method.

2021-07-19 16:11 UTC, And1sS commented on src/main/java/org/prebid/server/bidder/ix/IxBidder.java
> +            } else {
else if (bidType == BidType.xNative)

2021-07-19 17:25 UTC, rpanchyk commented on src/main/java/org/prebid/server/bidder/ix/IxBidder.java
> +            } else {
Seems it is already checked above.

2021-07-21 10:34 UTC, rpanchyk approved these changes

2021-07-21 10:41 UTC, merged