Add generic bidder
prebid/prebid-server-java pull request #1391
Opened 2021-07-27 15:01 UTC by And1sS

2021-07-28 12:15 UTC, snahornyi requested changes

2021-07-28 12:15 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/GenericBidder.java
> +        } catch (DecodeException | PreBidException e) {
PreBidException will never be thrown, pls get rid of it

2021-07-28 12:15 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/GenericBidder.java
> +    private List<BidderBid> extractBids(BidRequest bidRequest, BidResponse bidResponse) {
Can be static

2021-07-28 12:15 UTC, snahornyi commented on src/test/resources/org/prebid/server/it/openrtb2/generic_adapter/test-generic_adapter-bid-response.json
> +          "w": 300
Only id, impId, price and crid needed. And also set crid value to `creativeId`

2021-07-28 12:15 UTC, snahornyi commented on src/test/java/org/prebid/server/bidder/generic_adapter/GenericBidderTest.java
> +    @SafeVarargs
Remove

2021-07-28 12:15 UTC, snahornyi commented on src/test/java/org/prebid/server/bidder/generic_adapter/GenericBidderTest.java
> +    private static ExtPrebid<?, ExtImpKayzen> givenPrebidKayzenExt(String zoneId, String exchange) {
Method is being used only once, so can be inlined

2021-07-28 12:15 UTC, snahornyi commented on src/test/java/org/prebid/server/bidder/generic_adapter/GenericBidderTest.java
> +                .containsOnly(BidderBid.of(Bid.builder().impid("123").build(), banner, null));
Let's use containsExactly

2021-08-03 11:11 UTC, snahornyi requested changes

2021-08-03 11:11 UTC, snahornyi commented on src/test/java/org/prebid/server/bidder/generic_adapter/GenericBidderTest.java
> +                .containsOnly(BidderBid.of(Bid.builder().impid("123").build(), xNative, null));
Let's use containsExactly in every case

2021-08-03 11:11 UTC, snahornyi commented on src/test/java/org/prebid/server/bidder/generic_adapter/GenericBidderTest.java
> +    public void makeBidsShouldReturnNativeBidIfNativeIsPresentInRequestImp() throws JsonProcessingException {
Pls add audio bid test

2021-08-03 11:11 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/GenericBidder.java
> + */
So, it's time to remove this comment

2021-08-03 11:11 UTC, snahornyi commented on src/main/resources/bidder-config/generic_adapter.yaml
> +        - native
In code it also work for `audio`

2021-08-09 11:43 UTC, snahornyi submitted a review, later dismissed

2021-08-12 09:14 UTC, rpanchyk requested changes

2021-08-12 09:14 UTC, rpanchyk commented on src/test/java/org/prebid/server/bidder/generic_adapter/GenericBidderTest.java
> +                        .build(),
1. Extract to `givenBidRequest(UnaryOperator xxx)`.
2. Check all other tests and replace it there.

2021-08-12 09:14 UTC, rpanchyk commented on src/test/java/org/prebid/server/bidder/generic_adapter/GenericBidderTest.java
> +    private static BidRequest givenBidRequest(Function<Imp.ImpBuilder, Imp.ImpBuilder> impCustomizer) {
We can use `UnaryOperator` instead of `Function` since the same input-output.

2021-08-12 09:14 UTC, rpanchyk commented on src/test/java/org/prebid/server/bidder/generic_adapter/GenericBidderTest.java
> +                .containsExactly(BidderBid.of(Bid.builder().impid("123").build(), banner, null));
Pls replace `Bid.builder().impid("123").build()` with `givenBid(...)` method call.

2021-08-12 09:14 UTC, rpanchyk commented on src/test/resources/org/prebid/server/it/openrtb2/generic_adapter/test-auction-generic_adapter-request.json
> +          "supplyPartnerId": "1701"
Pls rename to `exampleProperty` and add it JSON schema.
Can be discussed.

2021-08-19 09:29 UTC, rpanchyk approved these changes

2021-08-20 19:32 UTC, muuki88 commented
I'm confused 😅 is this a real bidder or a generic implementation? If the second, what's the use case for it?

2021-08-27 14:11 UTC, schernysh submitted a review, later dismissed

2021-09-20 08:55 UTC, rpanchyk commented
> I'm confused  is this a real bidder or a generic implementation? If the second, what's the use case for it?

hey @muuki88 ! Updated description.

2021-09-20 10:08 UTC, rpanchyk approved these changes

2021-09-20 10:09 UTC, merged