Add operaads bidder
prebid/prebid-server-java pull request #1393
Opened 2021-07-29 08:39 UTC by And1sS

2021-08-04 11:08 UTC, nickluck8 requested changes

2021-08-04 11:08 UTC, nickluck8 commented on src/test/java/org/prebid/server/bidder/operaads/OperaadsBidderTest.java
> +
can you add test case with 2 imps: one is valid and another is not

2021-08-04 11:08 UTC, nickluck8 commented on src/test/java/org/prebid/server/bidder/operaads/OperaadsBidderTest.java
> +
test case when price == null || price < 0 ?

2021-08-05 13:39 UTC, nickluck8 approved these changes

2021-09-24 13:39 UTC, rpanchyk approved these changes

2021-09-24 13:42 UTC, merged