Smaato: Rework multi imp support and add adpod support
prebid/prebid-server-java pull request #1405
Opened 2021-08-05 09:48 UTC by And1sS

2021-08-11 08:50 UTC, nickluck8 requested changes

2021-08-11 08:50 UTC, nickluck8 commented on src/main/java/org/prebid/server/bidder/smaato/SmaatoBidder.java
> +    private Imp modifyImpForAdBreak(Imp imp, Integer sequence, String tagId) {
can you rename tagId to adBreakId

2021-08-11 08:50 UTC, nickluck8 commented on src/main/java/org/prebid/server/bidder/smaato/SmaatoBidder.java
> +            return (int) Math.max((expiresAtMillis - currentTimeMillis) / 1000, 0);
can you add unit tests for these lines

2021-08-11 08:50 UTC, nickluck8 commented on src/main/java/org/prebid/server/bidder/smaato/SmaatoBidder.java
> +        } else if (adm.startsWith("{\"richmedia\":")) {
unit test for this if

2021-08-11 08:50 UTC, nickluck8 commented on src/main/java/org/prebid/server/bidder/smaato/SmaatoBidder.java
> +        } else if (adm.startsWith("<?xml")) {
unit test for this if

2021-08-11 08:50 UTC, nickluck8 commented on src/main/java/org/prebid/server/proto/openrtb/ext/request/smaato/ExtImpSmaato.java
> +
remove comment here as well?

2021-08-20 09:42 UTC, nickluck8 approved these changes

2021-08-20 09:48 UTC, rpanchyk approved these changes

2021-08-20 09:49 UTC, merged