IX: update required site id field to be more flexible
prebid/prebid-server-java pull request #1406
Opened 2021-08-05 15:15 UTC by And1sS

2021-08-05 21:07 UTC, muuki88 commented
Out of curiousity. Why? 😅

Was this an issue for other Prebid Server vendors?

2021-08-06 10:20 UTC, And1sS commented
> Out of curiousity. Why? sweat_smile
> 
> Was this an issue for other Prebid Server vendors?

We did it just to match with go implementation.
https://github.com/prebid/prebid-server/commit/bab487e8a54b37dca75c5f86694170e60d638ef3

2021-08-06 10:24 UTC, snahornyi requested changes

2021-08-06 10:24 UTC, snahornyi commented on src/main/java/org/prebid/server/proto/openrtb/ext/request/ix/ExtImpIx.java
> +    @JsonAlias({"siteId", "siteid", "siteID"})
It's not necessary to duplicate `"siteId"`

2021-08-10 09:16 UTC, rpanchyk approved these changes

2021-08-10 09:17 UTC, merged