Yieldmo: Add gpid support
prebid/prebid-server-java pull request #1452
Opened 2021-08-30 08:57 UTC by And1sS

2021-09-02 13:57 UTC, rpanchyk requested changes

2021-09-02 13:57 UTC, rpanchyk commented on src/main/java/org/prebid/server/bidder/yieldmo/YieldmoBidder.java
> +        final JsonNode pbadslotNode = imp.getExt().at("/data/pbadslot");
The `JsonNode.at(...)` returns `MissingNode` but not null.

2021-09-08 12:19 UTC, snahornyi approved these changes

2021-09-24 14:56 UTC, rpanchyk approved these changes

2021-09-24 14:56 UTC, merged