RemovingGoogleCollection
prebid/prebid-server-java pull request #1454
Opened 2021-08-30 19:29 UTC by laarchenko

2021-09-01 18:06 UTC, Net-burst requested changes

2021-09-01 18:06 UTC, Net-burst commented on src/main/java/org/prebid/server/bidder/appnexus/AppnexusBidder.java
> +import org.apache.commons.collections4.ListUtils;
Import ordering.

2021-09-01 18:06 UTC, Net-burst commented on src/main/java/org/prebid/server/bidder/bidscube/BidscubeBidder.java
>  import java.util.Objects;
Import ordering.

2021-09-01 18:06 UTC, Net-burst commented on src/main/java/org/prebid/server/bidder/madvertise/MadvertiseBidder.java
>  import java.util.Objects;
Import order.

2021-09-08 13:16 UTC, rpanchyk approved these changes

2021-09-08 13:34 UTC, Net-burst approved these changes
LGTM

2021-09-16 13:43 UTC, merged