Iq zone bidder
prebid/prebid-server-java pull request #1479
Opened 2021-09-15 11:59 UTC by laarchenko

https://github.com/prebid/prebid-server/pull/1964

2021-09-15 12:46 UTC, And1sS approved these changes

2021-09-27 08:25 UTC, snahornyi requested changes

2021-09-27 08:25 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/iqzone/IqzoneBidder.java
> +        } catch (IllegalArgumentException e) {
Seems this catch block can have only PreBidEx which can come from getBidType(), so what is the purpose of `catch (IllegalArgumentException e)`? You can see that there is no test for this case.

2021-09-27 08:25 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/iqzone/IqzoneBidder.java
> +                .filter(Objects::nonNull)
ConstructBidderBid never returns null, pls remove this filter

2021-09-27 08:25 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/iqzone/IqzoneBidder.java
> +            throw new PreBidException("Bid response is null or seat bid is empty");
There is no error like this in go implementation

2021-09-27 08:25 UTC, snahornyi commented on src/test/java/org/prebid/server/bidder/iqzone/IqzoneBidderTest.java
> +
Pls create test for makeHttp request method

2021-09-27 08:25 UTC, snahornyi commented on src/main/resources/bidder-config/iqzone.yaml
> +    modifying-vast-xml-allowed: false
Pls merge master and use adapter-defaults feature

2021-09-27 12:50 UTC, snahornyi submitted a review, later dismissed

2021-09-27 12:59 UTC, rpanchyk approved these changes

2021-09-27 13:01 UTC, merged