Create a test for stored request and stored response
prebid/prebid-server-java pull request #1548
Opened 2021-10-22 12:35 UTC by mtuchkova

2021-11-03 09:48 UTC, Net-burst requested changes

2021-12-31 12:09 UTC, hupaloo submitted a review, later dismissed

2021-12-31 12:09 UTC, hupaloo commented on src/test/groovy/org/prebid/server/functional/HttpSettingsSpec.groovy
> +        assert response.seatbid.first().seat == BidderName.GENERIC
you may use enum static import here

2021-12-31 12:09 UTC, hupaloo commented on src/test/groovy/org/prebid/server/functional/AmpSpec.groovy
> +        assert response.targeting["hb_pb"] == "${price.setScale(1, RoundingMode.DOWN)}0"
you may use enum static import here

2022-02-17 20:19 UTC, hupaloo submitted a review, later dismissed

2022-03-30 14:51 UTC, Net-burst approved these changes
LGTM

2022-03-30 17:27 UTC, merged