Tests for pbs version header
prebid/prebid-server-java pull request #1561
Opened 2021-11-02 09:53 UTC by mtuchkova

2021-11-02 14:37 UTC, Net-burst requested changes

2021-11-02 14:37 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/model/response/amp/AmpResponse.groovy
> +    AmpResponseBody responseBody
Bad idea. You will need headers for only a couple of tests, but you are complicating model for everything else. Better add a method to a PBS service to return raw response body and headers.

2021-11-02 14:37 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/model/response/auction/AuctionResponse.groovy
> +    BidResponse responseBody
Same as with AMP. You are complicating things where you should not.

2021-11-02 14:37 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/model/response/amp/AmpResponse.groovy
> +    AmpResponseBody responseBody
You can leave this class as a wrapper for that service method to return, but it should not replace existing interactions. But the name will need to change.

2021-11-02 14:37 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/AmpSpec.groovy
> +        assert response.headers["x-prebid"]
You should check that actual project version from `pom.xml` is passed.

2021-11-04 12:39 UTC, And1sS reviewed
Could you, please, add test that checks header on failed request?

2021-11-04 13:31 UTC, And1sS approved these changes
LGTM! Thanks!

2021-11-05 21:20 UTC, Net-burst approved these changes
LGTM

2021-11-05 21:21 UTC, merged