Tests for builders not satisfying the json-schema
prebid/prebid-server-java pull request #1567
Opened 2021-11-05 12:26 UTC by mtuchkova

2021-11-05 13:20 UTC, rpanchyk commented on src/test/groovy/org/prebid/server/functional/BidderParamsSpec.groovy
> +                 "WARNING: request.imp[0].ext must contain at least one valid bidder"]
i'd rather recommend to test the case when `exampleProperty` given as string.

2021-11-05 13:37 UTC, rpanchyk commented on src/test/groovy/org/prebid/server/functional/BidderParamsSpec.groovy
> +                 "WARNING: request.imp[0].ext must contain at least one valid bidder"]
sorry, misunderstand. You're actually did in right way.

2021-11-05 14:04 UTC, rpanchyk submitted a review, later dismissed

2021-11-05 21:55 UTC, Net-burst requested changes

2021-11-05 21:55 UTC, Net-burst commented on src/test/resources/org/prebid/server/functional/db_schema.sql
> +    resid   varchar(40) NOT NULL,
Why change that?

2021-11-05 21:55 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/model/request/auction/ImpExtPrebid.groovy
> +    StoredAuctionResponse storedAuctionResponse
You'll need to lowercase that for JSON processing.

2021-11-05 21:55 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/BidderParamsSpec.groovy
> +                ["WARNING: request.imp[0].ext.prebid.generic was dropped with a reason: " +
Wording looks wrong. What exactly was dropped?

2021-11-05 21:55 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/BidderParamsSpec.groovy
> +        and: "Response should contain warnings"
Please be more exact. Bidder should be dropped.

2021-11-05 21:55 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/BidderParamsSpec.groovy
> +    def "PBS should not fail auction with storedAuctionResponse when request bidder params doesn't satisfy json-schema"() {
Kinda pointless test. Stored auction response is for debugging purposes. Better check that the same logic is valid for AMP and stored requests.

2021-11-15 11:34 UTC, Net-burst approved these changes
LGTM

2021-11-15 12:54 UTC, rpanchyk approved these changes

2021-11-15 12:57 UTC, merged