Add new bid parameters to Adprime
prebid/prebid-server-java pull request #1569
Opened 2021-11-08 08:43 UTC by yevhenii-viktorov

Prebid server PR: https://github.com/prebid/prebid-server/pull/1963
Docs: https://docs.prebid.org/dev-docs/pbs-bidders.html#adprime

2021-11-16 13:46 UTC, rpanchyk requested changes

2021-11-16 13:46 UTC, rpanchyk commented on src/main/java/org/prebid/server/bidder/adprime/AdprimeBidder.java
> +                .collect(Collectors.toList());
You have to add `.filter(Objects::nonNull)` since `resolveBidderBid` may return null.

2021-11-24 14:15 UTC, yevhenii-viktorov commented on src/main/java/org/prebid/server/bidder/adprime/AdprimeBidder.java
> +        if (Objects.isNull(bidRequest.getSite()) || CollectionUtils.isEmpty(audiences)) {
CollectionUtils.isEmpty checks null-reference. In go they dont care about if it is null.

2021-12-02 11:04 UTC, rpanchyk approved these changes

2021-12-02 11:07 UTC, merged