Adds NextMillenium Bidder to PBS
prebid/prebid-server-java pull request #1572
Opened 2021-11-11 13:43 UTC by yevhenii-viktorov

Original ticket: https://github.com/prebid/prebid-server/pull/2016/
Additional changes: https://github.com/prebid/prebid-server/pull/2061

2021-11-15 11:56 UTC, snahornyi requested changes

2021-11-15 11:56 UTC, snahornyi commented on src/test/resources/org/prebid/server/it/test-application.properties
> +adapters.nextmillenium.endpoint=http://localhost:8090/nextmillenium-exchange/
Minor. Remove redundant `/` make value to be `/nextmillenium-exchange`

2021-11-15 11:56 UTC, snahornyi commented on src/test/java/org/prebid/server/it/NextMilleniumTest.java
> +        WIRE_MOCK_RULE.stubFor(post(urlPathEqualTo("/nextmillenium-exchange/"))
Minor. Remove redundant `/` make value to be `/nextmillenium-exchange`

2021-11-15 11:56 UTC, snahornyi commented on src/main/java/org/prebid/server/proto/openrtb/ext/request/nextmillenium/ExtImpNextMillenium.java
> +@Value
@Value(staticConstructor = "of")

2021-11-15 11:56 UTC, snahornyi commented on src/main/java/org/prebid/server/proto/openrtb/ext/request/nextmillenium/ExtImpNextMillenium.java
> +    @JsonProperty("placement_id")
Unnecessary `@JsonProperty` default strategy is already snake case

2021-11-15 11:56 UTC, snahornyi commented on src/main/java/org/prebid/server/proto/openrtb/ext/request/nextmillenium/ExtImpNextMillenium.java
> + */
We are going to get rid of useless comments, pls remove it

2021-11-15 11:56 UTC, snahornyi commented on src/main/java/org/prebid/server/spring/config/bidder/NextMilleniumConfiguration.java
> +        return BidderDepsAssembler.forBidder(BIDDER_NAME)
NitPick. `/n` before return statement

2021-11-15 11:56 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/nextmillenium/NextMilleniumBidder.java
> +                return Result.of(null, null);
return Result.empty();

2021-11-15 11:56 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/nextmillenium/NextMilleniumBidder.java
> +            if (bidResponse.getSeatbid().size() == 0) {
CollectionUtils.isEmpty(bidResponse.getSeatbid())

2021-11-15 11:56 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/nextmillenium/NextMilleniumBidder.java
> +    private List<ExtImpNextMillenium> errorIfEmpty(List<BidderError> errors) {
BidRequest validator checks is there any imp in request, even more without imp request will not come to bidder. This method is redundant

2021-11-15 11:56 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/nextmillenium/NextMilleniumBidder.java
> +            return Result.of(null, errors);
return Result.withErrors(errors);

2021-11-15 11:56 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/nextmillenium/NextMilleniumBidder.java
> +            return Result.of(makeRequests(bidRequest, extImps), Collections.emptyList());
return Result.withValues(makeRequests(bidRequest, impExts));

2021-11-15 11:56 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/nextmillenium/NextMilleniumBidder.java
> +        } else {
Else can be ommited

2021-11-15 11:56 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/nextmillenium/NextMilleniumBidder.java
> +
We can update this to this, and also I would suggest to extract ext resolving logic to another method
```java
        final List<BidderError> errors = new ArrayList<>();
        final List<ExtImpNextMillenium> impExts = new ArrayList<>();

        for (Imp imp : bidRequest.getImp()) {
            try {
                impExts.add(mapper.mapper()
                        .convertValue(imp.getExt(), NEXTMILLENIUM_EXT_TYPE_REFERENCE)
                        .getBidder());
            } catch (IllegalArgumentException e) {
                errors.add(BidderError.of(e.getMessage(), BidderError.Type.bad_input));
            }
        }
```

2021-11-15 11:56 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/nextmillenium/NextMilleniumBidder.java
> +                .headers(HttpUtil.headers().add(HttpUtil.X_OPENRTB_VERSION_HEADER, "2.5"))
```java
private static MultiMap headers() {

        return HttpUtil.headers()
                .add(HttpUtil.X_OPENRTB_VERSION_HEADER, "2.5");
    }
```

2021-11-15 11:56 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/nextmillenium/NextMilleniumBidder.java
> +        return httpRequests;
Let's update with stream approach
```java
private List<HttpRequest<BidRequest>> makeRequests(BidRequest bidRequest, List<ExtImpNextMillenium> extImps) {

        return extImps.stream()
                .map(extImp -> makeHttpRequest(updateBidRequest(bidRequest, extImp)))
                .collect(Collectors.toList());

    }
```

2021-11-15 11:56 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/nextmillenium/NextMilleniumBidder.java
> +    private BidRequest updateBidRequest(BidRequest bidRequest, ExtImpNextMillenium ext) {
Can be static

2021-11-15 11:56 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/nextmillenium/NextMilleniumBidder.java
> +    private BidRequest updateBidRequest(BidRequest bidRequest, ExtImpNextMillenium ext) {
Pls put methods in call order

2021-11-15 11:56 UTC, snahornyi commented on src/test/java/org/prebid/server/bidder/nextmillenium/NextMilleniumBidderTest.java
> +public class NextMilleniumBidderTest extends VertxTest {
Pls add tests for present payload check

2021-11-15 11:56 UTC, snahornyi commented on src/test/java/org/prebid/server/bidder/nextmillenium/NextMilleniumBidderTest.java
> +    private static BidRequest givenBidRequest(Function<Imp.ImpBuilder, Imp.ImpBuilder>... impCustomizers) {
UnaryOperator

2021-11-15 11:56 UTC, snahornyi commented on src/test/java/org/prebid/server/bidder/nextmillenium/NextMilleniumBidderTest.java
> +            List<Function<Imp.ImpBuilder, Imp.ImpBuilder>> impCustomizers) {
UnaryOperator
Pls check similar

2021-11-15 11:56 UTC, snahornyi commented on src/test/java/org/prebid/server/bidder/nextmillenium/NextMilleniumBidderTest.java
> +    private static BidRequest givenBidRequest(Function<Imp.ImpBuilder, Imp.ImpBuilder>... impCustomizers) {
Seems in your case one impCustomizer is enough, no need for varargs here

2021-11-19 11:55 UTC, rpanchyk requested changes

2021-11-19 11:55 UTC, rpanchyk commented on src/main/java/org/prebid/server/bidder/nextmillenium/NextMilleniumBidder.java
> +        if (errors.size() > 0) {
Pls refactor to use ternary operation:
`return errors.isEmpty() ? result1 : result2;`

2021-11-19 11:55 UTC, rpanchyk commented on src/main/java/org/prebid/server/bidder/nextmillenium/NextMilleniumBidder.java
> +
Redundant line.

2021-11-19 11:55 UTC, rpanchyk commented on src/main/java/org/prebid/server/bidder/nextmillenium/NextMilleniumBidder.java
> +
Redundant line.

2021-11-19 11:55 UTC, rpanchyk commented on src/main/resources/bidder-config/nextmillenium.yaml
> +      vendor-id: 0
Should be `1060`
As listed in https://vendor-list.consensu.org/v2/archives/vendor-list-v118.json

2021-11-29 12:40 UTC, snahornyi requested changes

2021-11-29 12:40 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/nextmillenium/NextMilleniumBidder.java
> +                errors.add(BidderError.of(e.getMessage(), BidderError.Type.bad_input));
errors.add(BidderError.badInput(e.getMessage()));

2021-11-29 12:40 UTC, snahornyi commented on src/test/java/org/prebid/server/bidder/nextmillenium/NextMilleniumBidderTest.java
> +        assertThat(result.getErrors().get(0).getMessage()).startsWith("Failed to decode:");
Pls also check error type. allSatisfy can be used

2021-11-29 12:40 UTC, snahornyi commented on src/test/java/org/prebid/server/bidder/nextmillenium/NextMilleniumBidderTest.java
> +    public void makeBidsGivenCorrectBidResponseContainsCorrectBidder() throws JsonProcessingException {
makeBidsShouldReturnBannerBidByDefault

2021-11-29 12:40 UTC, snahornyi commented on src/test/java/org/prebid/server/bidder/nextmillenium/NextMilleniumBidderTest.java
> +                        .seatbid(List.of())
Pls avoid "Import with class", and also for this case use `emptyList()`

2021-11-29 12:40 UTC, snahornyi commented on src/test/java/org/prebid/server/bidder/nextmillenium/NextMilleniumBidderTest.java
> +        assertThat(result.getErrors().get(0).getMessage()).startsWith("Cannot deserialize value of type");
Check for type also

2021-11-29 12:40 UTC, snahornyi commented on src/test/java/org/prebid/server/bidder/nextmillenium/NextMilleniumBidderTest.java
> +                        .bid(List.of(bidCustomizer.apply(Bid.builder()).build()))
singletonList

2021-11-29 12:40 UTC, snahornyi commented on src/test/java/org/prebid/server/bidder/nextmillenium/NextMilleniumBidderTest.java
> +                .seatbid(List.of(SeatBid.builder()
singletonList

2021-11-30 10:39 UTC, snahornyi approved these changes

2021-12-02 11:59 UTC, rpanchyk approved these changes

2021-12-02 12:00 UTC, merged