Refactor AdfBidder
prebid/prebid-server-java pull request #1575
Opened 2021-11-12 10:50 UTC by CTMBNara

Rid off the OpenrtbBidder usage.

2021-11-23 17:54 UTC, snahornyi requested changes

2021-11-23 17:54 UTC, snahornyi commented on src/main/java/com/iab/openrtb/request/BidRequest.java
> +    @Wither
Pls remove it. It is not good to have two approaches for one action. For this one second approach is for specific case

2021-11-23 17:54 UTC, snahornyi commented on src/main/java/com/iab/openrtb/request/Imp.java
> +    @Wither
Pls remove

2021-11-23 17:54 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/adf/AdfBidder.java
> +                     @NonNull JacksonMapper mapper) {
Pls use project style with requireNonNull function

2021-11-23 17:54 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/adf/AdfBidder.java
> +        return Result.of(List.of(httpRequest), errors);
For one object pls use Collections.singletonList

2021-11-23 17:54 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/adf/AdfBidder.java
> +        final Optional<ExtImpAdf> optionalAdfImp;
For now we don't use Optional in our code. Pls update

2021-11-23 17:54 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/adf/AdfBidder.java
> +    private Imp modifyImp(Imp imp, Consumer<BidderError> onError) {
According to style, pls just pass errors. And then call errors.add

2021-11-23 17:54 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/adf/AdfBidder.java
> +    private BidResponse parseBidResponse(HttpCall<BidRequest> httpCall) throws DecodeException {
According to other bidders style, pls move it to makeBidds method

2021-11-23 17:54 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/adf/AdfBidder.java
> +    }
Pls check other Bidders code style, like between bidder, and update your code style to be as much similar as possible

2021-11-29 11:23 UTC, snahornyi approved these changes

2021-11-29 11:23 UTC, rpanchyk approved these changes

2021-11-29 11:24 UTC, merged