Tests for debug log for ccpa,coppa,gdpr
prebid/prebid-server-java pull request #1577
Opened 2021-11-15 09:17 UTC by mtuchkova

2021-11-15 11:54 UTC, Net-burst requested changes
First round.

2021-11-15 11:54 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/util/ConsentString.groovy
> +    static private final String VENDOR_LIST_URL = "https://vendor-list.consensu.org/v2/vendor-list.json"
wrong keyword order.

2021-11-15 11:54 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/model/response/auction/Privacy.groovy
> +class Privacy {
Better switch places in names: name this class DebugPrivacy and other just Privacy.

2021-11-15 11:54 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/CcpaSpec.groovy
> +        def validCcpa = "1YYY"
While you're at it, you can also create a wrapper class for it, because a lot of people won't know what 1YYY means.

2021-11-15 11:54 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/CcpaSpec.groovy
>  class CcpaSpec extends BaseSpec {
Looks like this can be nested under `privacy` package as we now have 3 different groups of tests for this topic that also share a lot of code.

2021-11-15 11:54 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/util/ConsentString.groovy
> +    static public final Integer BASIC_ADS_PURPOSE_ID = 2
This should be an Enum.

2021-11-22 17:11 UTC, Net-burst requested changes
Almost there. Foud couple minor issues.

2021-11-22 17:11 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/tests/privacy/CcpaSpec.groovy
> +        assert bidderRequests.device?.geo?.lat == maskedGeo["lat"]
You're comparing bidder request to bidder request here. This is incorrect. Please provide your own device.geo and compare against that. Same for other tests.

2021-11-22 17:11 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/tests/privacy/PrivacyBaseSpec.groovy
> +    protected static Map<String, Float> getMaskedGeo(BidderRequest bidderRequest) {
You're doing very different thing to masking Geo. Geo is a POGO, so please return a POGO and not a map.

2021-11-26 10:08 UTC, rpanchyk approved these changes

2021-11-26 10:42 UTC, merged