Remove extraInfo field for bidder configuration properties
prebid/prebid-server-java pull request #1594
Opened 2021-11-24 18:00 UTC by yevhenii-viktorov

2021-11-29 13:33 UTC, And1sS requested changes

2021-11-29 13:33 UTC, And1sS commented on src/main/java/org/prebid/server/spring/config/bidder/TripleliftNativeConfiguration.java
> +        private List<String> whitelist;
Lets add `@NotNull` annotation.

2021-11-29 13:33 UTC, And1sS commented on src/main/resources/bidder-config/tripleliftnative.yaml
> +    whitelist: test
Please, replace with `whitelist:`. Don't use test values in production code.

2021-12-03 12:03 UTC, rpanchyk approved these changes

2021-12-03 13:37 UTC, And1sS approved these changes

2021-12-03 13:47 UTC, merged