Validation by BIDDER.yaml for media types tests
prebid/prebid-server-java pull request #1606
Opened 2021-11-30 09:52 UTC by mtuchkova

Tests for #1144

2021-12-06 13:03 UTC, Net-burst requested changes

2021-12-06 13:03 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/tests/BidderParamsSpec.groovy
> +        ["adapters.generic.meta-info.validate-media-types": "true",
This looks like it should be 2 separate tests as in one case you're setting validate-media-types and in other - not. Also try to not parametrize description.

2021-12-17 15:39 UTC, Net-burst approved these changes
LGTM

2022-01-04 08:16 UTC, hupaloo approved these changes

2022-05-25 10:16 UTC, merged