Add privacy debug log
prebid/prebid-server-java pull request #1617
Opened 2021-12-09 14:07 UTC by And1sS

2021-12-17 13:01 UTC, snahornyi commented
Tests in https://github.com/prebid/prebid-server-java/pull/1577

2021-12-20 12:57 UTC, rpanchyk requested changes

2021-12-20 12:57 UTC, rpanchyk commented on src/main/java/org/prebid/server/privacy/PrivacyExtractor.java
> +    private Privacy extractOriginPrivacy(Regs regs, User user, List<String> errors) {
Can be static?

2021-12-20 12:57 UTC, rpanchyk commented on src/main/java/org/prebid/server/privacy/model/PrivacyDebugLog.java
> +        public static PrivacyTcfDebug of(String gdpr, String tcfConsentString) {
Let's declare methods after fields.

2021-12-20 12:57 UTC, rpanchyk commented on src/main/java/org/prebid/server/privacy/PrivacyAnonymizationService.java
> +        return extUser != null && (CollectionUtils.isNotEmpty(extUser.getEids()));
Redundant braces.

2021-12-20 12:57 UTC, rpanchyk commented on src/main/java/org/prebid/server/privacy/PrivacyAnonymizationService.java
> +                    deviceBuilder.geo(PrivacyAnonymizationService.maskGeoCoordinates(device.getGeo())));
The `PrivacyAnonymizationService` deals with TCF, CCPA and COPPA privacies. Why it cares about geo?

2021-12-20 15:08 UTC, snahornyi approved these changes

2021-12-20 15:08 UTC, snahornyi commented on src/main/java/org/prebid/server/privacy/model/PrivacyDebugLog.java
> +                .privacyActionsPerBidder(new HashMap<>())
Should we think, of immutable data structures?

2021-12-20 15:08 UTC, snahornyi commented on src/main/java/org/prebid/server/privacy/model/PrivacyDebugLog.java
> +        @JsonInclude(value = JsonInclude.Include.NON_EMPTY)
Maybe move it on class level?

2021-12-20 15:08 UTC, snahornyi commented on src/main/java/org/prebid/server/privacy/model/PrivacyDebugLog.java
> +        public static PrivacyTcfDebug of(String gdpr, String tcfConsentString) {
Let's place it after field declaration

2021-12-20 15:08 UTC, snahornyi commented on src/main/java/org/prebid/server/privacy/PrivacyExtractor.java
> +        final List<String> errors = new ArrayList<>();
immutable collection?

2021-12-20 15:08 UTC, snahornyi commented on src/main/java/org/prebid/server/privacy/PrivacyAnonymizationService.java
> +     * Returns true if {@link User} has sensitive privacy information that can be masked.
can or should?

2021-12-20 15:08 UTC, snahornyi commented on src/main/java/org/prebid/server/auction/ExchangeService.java
> +                // for each bidder create a new request that is a copy of original request except buyerid, imp
Let's delete or move to method docs

2022-05-16 10:33 UTC, closed without merging