Externalize max number of containers through pom.xml and lower the de…
prebid/prebid-server-java pull request #1655
Opened 2021-12-28 11:59 UTC by mtuchkova

…fault value

2021-12-28 12:52 UTC, Net-burst approved these changes
LGTM with minor remark.

2021-12-28 12:52 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/testcontainers/PbsServiceFactory.groovy
> +    private static final Integer MAX_CONTAINERS_COUNT = Integer.valueOf(System.getProperty("max.containers.count"))
`int` please. You will still get an exception if you pass in null.

2021-12-30 12:40 UTC, snahornyi requested changes

2021-12-30 12:40 UTC, snahornyi commented on src/test/groovy/org/prebid/server/functional/testcontainers/PbsServiceFactory.groovy
> +    private static final Integer MAX_CONTAINERS_COUNT = Integer.valueOf(
Can we use parseInt(String num)?

2021-12-30 13:08 UTC, Net-burst approved these changes
LGTM

2021-12-30 13:09 UTC, snahornyi approved these changes

2021-12-30 13:10 UTC, merged