Add caller info to 33across bid requests.
prebid/prebid-server-java pull request #1656
Opened 2021-12-28 21:32 UTC by CTMBNara

2022-01-25 15:24 UTC, curlyblueeagle commented on src/main/java/org/prebid/server/bidder/thirtythreeacross/ThirtyThreeAcrossBidder.java
> +            ThirtyThreeAcrossExtTtxCaller.of("Prebid-Server", "n/a");
Hi, I am the maintainer from 33Across. Can I request the caller name passed as `Prebid-Server-Java` to differentiate requests from the Go adapter we already have? Thanks.

2022-02-09 14:46 UTC, yevhenii-viktorov approved these changes

2022-02-09 15:31 UTC, SerhiiNahornyi requested changes

2022-02-09 15:31 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/bidder/thirtythreeacross/proto/ThirtyThreeAcrossExtTtxCaller.java
> +    @JsonInclude(JsonInclude.Include.NON_EMPTY)
Pls remove @JsonInclude(JsonInclude.Include.NON_EMPTY)

2022-02-09 15:31 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/bidder/thirtythreeacross/ThirtyThreeAcrossBidder.java
> +            callers.add(PREBID_CALLER);
ListUtils.union(extTtx.getCaller(), Collections.singletonList(PREBID_CALLER)) and then create ternary

2022-02-09 15:31 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/bidder/thirtythreeacross/ThirtyThreeAcrossBidder.java
> +        final Map<String, JsonNode> properties = ObjectUtil.getIfNotNull(ext, ExtRequest::getProperties);
extProperties

2022-02-09 15:31 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/bidder/thirtythreeacross/ThirtyThreeAcrossBidder.java
> +    private Imp updateImp(Imp imp, ExtImpThirtyThreeAcross extImpThirtyThreeAcross) throws PreBidException {
Pls remove unchecked exceptions from method declarations

2022-02-11 10:34 UTC, yevhenii-viktorov approved these changes

2022-02-11 15:35 UTC, merged