Adf adapter: lacked gross/net parameter support
prebid/prebid-server-java pull request #1689
Opened 2022-01-18 13:07 UTC by marki1an

2022-01-19 13:52 UTC, CTMBNara requested changes

2022-01-19 13:52 UTC, CTMBNara commented on src/main/java/org/prebid/server/bidder/adf/AdfBidder.java
> +                priceType = Objects.nonNull(adfImp.getPriceType()) ? adfImp.getPriceType() : "";
From Go, you need to get the first non empty inclusion of `priceType`.

2022-01-19 13:52 UTC, CTMBNara commented on src/main/java/org/prebid/server/bidder/adf/AdfBidder.java
> +                    ExtRequest.of(extRequestPrebid), adfNode);
Following the current solution, you can wipe the data in `request.getExt()` outside of `request.getExt().getPrebid()`. Try like this:
```
final ExtRequest extRequest = ObjectUtils.defaultIfNull(bidRequest.getExt(), ExtRequest.empty());
mapper.fillExtension(extRequest, adfNode);
```

2022-01-19 13:52 UTC, CTMBNara commented on src/main/java/org/prebid/server/bidder/adf/AdfBidder.java
> +            bidRequest.toBuilder().ext(extRequest).build();
`BidRequest` is immutable object. This action does not change it.

2022-01-19 13:52 UTC, CTMBNara commented on src/main/java/org/prebid/server/proto/openrtb/ext/request/adf/ExtImpAdf.java
> +    String priceType;
Add
```
@JsonProperty("priceType")
@JsonInclude(JsonInclude.Include.NON_EMPTY)
```

2022-01-20 13:38 UTC, CTMBNara requested changes

2022-01-20 13:38 UTC, CTMBNara commented on src/main/java/org/prebid/server/bidder/adf/AdfBidder.java
> +                    .set("pt", TextNode.valueOf(priceType));
Use `.put("pt", priceType)`

2022-01-20 13:38 UTC, CTMBNara commented on src/main/java/org/prebid/server/bidder/adf/AdfBidder.java
> +                        && Objects.nonNull(adfImp.getPriceType()) ? adfImp.getPriceType() : "";
Use `StringUtils.isNotEmpty` instead of `Objects.nonNull`

2022-01-20 13:38 UTC, CTMBNara commented on src/main/java/org/prebid/server/bidder/adf/AdfBidder.java
> +            bidRequest = bidRequest.toBuilder().ext(fillExtRequest).build();
Introduce new variable `modifiedRequest`. Do not assign new reference to method parameters.

2022-01-20 13:38 UTC, CTMBNara commented on src/test/java/org/prebid/server/bidder/adf/AdfBidderTest.java
> +                .containsExactly(expectedRequest.getImp().toArray(new Imp[0]));
Rid of `expectedRequest`.

2022-01-20 13:38 UTC, CTMBNara commented on src/test/java/org/prebid/server/bidder/adf/AdfBidderTest.java
>      }
This test does not follow the logic of the bidder. You need to add the `priceType` to the `imp.ext.priceType` and check that the adapter will put this value into `request.ext.pt`.

2022-01-20 13:38 UTC, CTMBNara commented on src/test/java/org/prebid/server/bidder/adf/AdfBidderTest.java
>                                  .build())));
Replace `Imp.builder` with `givenImp`

2022-01-20 13:38 UTC, CTMBNara commented on src/test/java/org/prebid/server/bidder/adf/AdfBidderTest.java
>      }
This test asserts too much. Separate it.

2022-01-20 13:40 UTC, CTMBNara commented on src/main/java/org/prebid/server/bidder/adf/AdfBidder.java
> +                    ExtRequest.of(extRequestPrebid), adfNode);
Pls follow the above approach

2022-01-31 14:26 UTC, CTMBNara requested changes

2022-01-31 14:26 UTC, CTMBNara commented on src/main/java/org/prebid/server/bidder/adf/AdfBidder.java
> +        }
Extract to `modifyBidRequest` method.

2022-02-15 10:02 UTC, And1sS requested changes

2022-02-15 10:02 UTC, And1sS commented on src/main/java/org/prebid/server/bidder/adf/AdfBidder.java
> +        String priceType = "";
`priceType = null;` then, `priceType = ObjectUtil.defaultIfNull(priceType, adfImp.getPriceType());`

2022-02-16 12:46 UTC, CTMBNara approved these changes

2022-02-22 10:25 UTC, SerhiiNahornyi approved these changes

2022-02-22 10:31 UTC, merged