Refactor Adman Bidder: Extend from Bidder interface
prebid/prebid-server-java pull request #1694
Opened 2022-01-20 10:41 UTC by marki1an

2022-01-20 14:11 UTC, CTMBNara requested changes

2022-01-20 14:11 UTC, CTMBNara commented on src/test/java/org/prebid/server/bidder/adman/AdmanBidderTest.java
> +        assertThat(result.getErrors().get(0).getMessage()).startsWith("Imp.ext could not be parsed");
Merge assertions. And use `extracting(...)`.

2022-01-20 14:11 UTC, CTMBNara commented on src/test/java/org/prebid/server/bidder/adman/AdmanBidderTest.java
> +    public void makeBidsShouldThrowExceptionIsNoImpressionWithIdFound() throws JsonProcessingException {
Rename test to `makeBidsShouldContainsErrorIfImpForBidAbsent`

2022-01-20 14:11 UTC, CTMBNara commented on src/test/java/org/prebid/server/bidder/adman/AdmanBidderTest.java
> +                impBuilder -> impBuilder.id("123"));
Add additional imp and bid to verify that errors will not affect correct bids.

2022-01-31 14:57 UTC, CTMBNara approved these changes

2022-02-01 12:26 UTC, SerhiiNahornyi approved these changes

2022-02-01 12:26 UTC, merged