Adot: Add OpenRTB macros resolution
prebid/prebid-server-java pull request #1703
Opened 2022-01-25 16:45 UTC by marki1an

2022-02-01 13:56 UTC, CTMBNara requested changes

2022-02-01 13:56 UTC, CTMBNara commented on src/main/java/org/prebid/server/bidder/adot/AdotBidder.java
> +        final String auctionPrice = "${AUCTION_PRICE}";
Introduce constant.

2022-02-01 13:56 UTC, CTMBNara commented on src/main/java/org/prebid/server/bidder/adot/AdotBidder.java
> +        final String bidPrice = Objects.toString(bid.getPrice());
`Bid.Price` is required field. Just use `getPrice().toString()`

2022-02-09 18:48 UTC, SerhiiNahornyi approved these changes

2022-02-09 18:48 UTC, And1sS approved these changes

2022-02-09 18:48 UTC, CTMBNara approved these changes

2022-02-09 18:53 UTC, merged