Removed redundant amp validations
prebid/prebid-server-java pull request #1705
Opened 2022-01-25 17:52 UTC by And1sS

2022-01-26 09:34 UTC, rpanchyk commented on src/main/java/org/prebid/server/auction/requestfactory/AmpRequestFactory.java
> +        return Regs.of(null, ExtRegs.of(gdpr, usPrivacy));
Suggesting to add `gdpr != null || usPrivacy != null`, otherwise - return null.

2022-03-14 07:37 UTC, SerhiiNahornyi requested changes

2022-03-14 07:37 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/auction/model/ConsentType.java
> +                .filter(value -> StringUtils.equals(value.type, resolvedType))
Nitpick. As we know, that resolvedType will never be null, we can use `resolvedType.equals(value.type)` instead of `StringUtils.equals`

2022-03-14 07:37 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/auction/privacycontextfactory/AmpPrivacyContextFactory.java
> +        if (Objects.equals(requestType, MetricName.openrtb2web)) {
As we work with enum value`MetricName.openrtb2web == requestType. Pls make same change for enforcement service

2022-03-14 07:37 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/auction/privacycontextfactory/AmpPrivacyContextFactory.java
> +    private static TcfContext logWarnings(AuctionContext auctionContext, TcfContext tcfContext) {
Same as for privacyEnforcementService, pls pass List of warnings

2022-03-14 07:37 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/auction/privacycontextfactory/AmpPrivacyContextFactory.java
> +            return RequestLogInfo.of(requestType, refUrl, accountId);
See no test for this case

2022-03-14 07:37 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/auction/privacycontextfactory/AmpPrivacyContextFactory.java
> +            return shouldBeMasked ? ipAddressHelper.maskIpv4(ipV4Address) : ipV4Address;
Pls add test for this case, also for Ipv6

2022-03-14 09:20 UTC, Net-burst approved these changes
LGTM with a question

2022-03-15 14:51 UTC, SerhiiNahornyi approved these changes

2022-03-15 14:51 UTC, merged