Adnuntius : read device information from ortb Request
prebid/prebid-server-java pull request #1707
Opened 2022-01-26 15:15 UTC by marki1an

2022-01-27 10:51 UTC, CTMBNara requested changes

2022-01-27 10:51 UTC, CTMBNara commented on src/main/java/org/prebid/server/bidder/adnuntius/AdnuntiusBidder.java
> +            final String deviceUa = device.getUa();
Inline it to methods call.

2022-01-27 10:51 UTC, CTMBNara commented on src/main/java/org/prebid/server/bidder/adnuntius/AdnuntiusBidder.java
> +            if (StringUtils.isNotBlank(deviceIp)) {
Remove redundant `if` statement

2022-01-27 10:51 UTC, CTMBNara commented on src/main/java/org/prebid/server/bidder/adnuntius/AdnuntiusBidder.java
> +            if (StringUtils.isNotBlank(deviceUa)) {
Remove redundant `if` statement

2022-02-01 12:40 UTC, SerhiiNahornyi approved these changes

2022-02-01 12:40 UTC, merged