Adds mediatype chooser and tests for PriceFloorAdjuster
prebid/prebid-server-java pull request #1733
Opened 2022-02-11 11:59 UTC by yevhenii-viktorov

+ some minor refactoring

2022-02-17 09:59 UTC, SerhiiNahornyi requested changes

2022-02-17 09:59 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/floors/BasicPriceFloorAdjuster.java
> +                ? BidderUtil.roundFloor(imp.getBidfloor().divide(factor, 30, RoundingMode.HALF_EVEN))
instead of 30 factor.precision()

2022-02-17 09:59 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/floors/BasicPriceFloorAdjuster.java
> +        for (ImpMediaType mediaType : extBidadjustmentfactors.getMediatypes().keySet()) {
Seems extBidadjustmentfactors.getMediatypes() can be null let's add tests for it

2022-02-17 09:59 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/floors/BasicPriceFloorAdjuster.java
> +    private static ImpMediaType chooseMediaType(ExtRequestBidadjustmentfactors extBidadjustmentfactors, String bidder) {
What if the lowest mediatype value is 0.7 for banner, but Imp even don't have banner mediatype? We should work only with mediatypes presented in Imp

2022-02-17 09:59 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/floors/BasicPriceFloorAdjuster.java
> +        final BigDecimal factor = mediaType != null
Factor can be not only for mediatype

2022-02-17 09:59 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/floors/BasicPriceFloorAdjuster.java
> +            Map<String, BigDecimal> mediaTypeValues = extBidadjustmentfactors.getMediatypes().get(mediaType);
final

2022-02-17 09:59 UTC, SerhiiNahornyi commented on src/test/java/org/prebid/server/floors/BasicPriceFloorAdjusterTest.java
> +        final String bidder = "bidder";
According to project style, just create 
```java
private static final String RUBICON = "rubicon";
```
And then use it directly in when block, also actually everything can be moved to `when` block

2022-02-22 14:35 UTC, SerhiiNahornyi requested changes

2022-02-22 14:35 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/floors/BasicPriceFloorAdjuster.java
> +            if (imp.getVideo().getPlacement() != 1) {
Seems NPE when placement is null

2022-02-22 14:35 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/floors/BasicPriceFloorAdjuster.java
> +        if (imp.getAudio() != null) {
Minor. Just for consistency with project, place it in order (banner, video, native, audio)

2022-02-22 14:35 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/floors/BasicPriceFloorAdjuster.java
> +                : imp.getBidfloor();
Just null for 38 line

2022-02-22 14:35 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/floors/BasicPriceFloorAdjuster.java
> +        final TreeMap<BigDecimal, ImpMediaType> factorToMediatype = new TreeMap<>();
Why we need this complex logic with Map? Can we just find and return biggest floor? Then compare it with extBidadjustmentfactors.getAdjustments().get(bidder) factor?

2022-02-22 14:35 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/floors/BasicPriceFloorAdjuster.java
> +        return imp.getBidfloor() != null
imp.getBidfloor() used three times in this method, pls introduce it to separate variable

2022-02-22 14:51 UTC, yevhenii-viktorov commented on src/main/java/org/prebid/server/floors/BasicPriceFloorAdjuster.java
> +                : imp.getBidfloor();
yea I thought about it :)

2022-02-23 09:15 UTC, yevhenii-viktorov commented on src/main/java/org/prebid/server/util/BidderUtil.java
> +    public static BigDecimal roundFloor(BigDecimal floor) {
Agreed on both things. We should refactor it out of BidderUtil.

2022-02-28 11:16 UTC, SerhiiNahornyi approved these changes

2022-02-28 11:17 UTC, merged