ENUM case to the uppercase.
prebid/prebid-server-java pull request #1741
Opened 2022-02-16 15:16 UTC by marki1an

2022-02-22 09:19 UTC, yevhenii-viktorov requested changes
We have an issue here, proposed changes change API: Functional tests are failing, metrics will have **another** names (which is unexceptable at all), We should figure out how to **not** change external usage of enums as this is **refactoring** and not logic change.
I have placed comment on class that is my main concern. Please, take your time to figure better idea of changing enums to uppercase.
We can discuss everything here if you would like to.

2022-02-22 09:19 UTC, yevhenii-viktorov commented on src/main/java/org/prebid/server/metric/MetricName.java
>  public enum MetricName {
My main concern

2022-03-02 14:43 UTC, marki1an commented on docs/application-settings.md
> +    `price_granularity` enum('LOW','MED','HIGH','AUTO','DENSE','UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
What does it mean change from other sides ?

2022-03-02 14:49 UTC, marki1an commented on docs/application-settings.md
> +- `auction.price-granularity` - defines price granularity types: 'LOW','MED','HIGH','AUTO','DENSE','UNKNOWN'.
you mean change doc  or price granularity types ?

2022-03-02 15:17 UTC, marki1an commented on docs/config-app.md
> +- `metrics.accounts.BASIC-verbosity` - a list of accounts for which only basic metrics will be submitted.
why it should be in lowercase ?

2022-03-02 15:17 UTC, marki1an commented on docs/metrics.md
> +- `APP_REQUESTS` - number of requests received from applications
also why it should be in lowercase ?

2022-03-02 15:19 UTC, marki1an commented on src/main/java/org/prebid/server/auction/ExchangeService.java
> +                metrics.updateAdapterRequestErrorMetric(bidderResponse.getBidder(), MetricName.UNKNOWN_ERROR);
also explain more detail regarding this

2022-03-03 10:06 UTC, yevhenii-viktorov commented on docs/application-settings.md
> +    `price_granularity` enum('LOW','MED','HIGH','AUTO','DENSE','UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
What will happen, if we deploy changes to database, but some other application will use lowercase values? It will fail.

2022-03-03 10:06 UTC, yevhenii-viktorov commented on docs/application-settings.md
> +- `auction.price-granularity` - defines price granularity types: 'LOW','MED','HIGH','AUTO','DENSE','UNKNOWN'.
ENUM change is part of this PR, while database change is not.

2022-03-03 10:07 UTC, yevhenii-viktorov commented on docs/application-settings.md
> +- `auction.price-granularity` - defines price granularity types: 'LOW','MED','HIGH','AUTO','DENSE','UNKNOWN'.
Maybe we should reflect this in doc

2022-03-03 10:09 UTC, yevhenii-viktorov commented on docs/config-app.md
> +- `metrics.metricType` - set the type of metric counter for [Dropwizard Metrics](http://metrics.dropwizard.io). Can be `FLUSHING_COUNTER` (default), `COUNTER` or `METER`.
Metrics are exported by name. therefore flushCounter and FLUSHING_COUNTER are different metrics from Grafana PoV.  Infrastructural stuff like alerts can be tight to metric name. So pushing other metric name will break that,

2022-03-03 10:10 UTC, yevhenii-viktorov commented on docs/config-app.md
> +- `metrics.accounts.BASIC-verbosity` - a list of accounts for which only basic metrics will be submitted.
Metric names should be lowercase, while actual enum should be uppercase.

2022-03-03 10:11 UTC, yevhenii-viktorov commented on src/main/java/org/prebid/server/auction/ExchangeService.java
> +                metrics.updateAdapterRequestErrorMetric(bidderResponse.getBidder(), MetricName.UNKNOWN_ERROR);
Explained in previous comments.

2022-03-07 10:12 UTC, marki1an commented on src/main/java/org/prebid/server/analytics/reporter/pubstack/PubstackAnalyticsReporter.java
> +            return HttpUtil.validateUrl(endpoint + EVENT_REPORT_ENDPOINT_PATH + "/" + eventType);
EventType has defined toString already

2022-03-10 11:02 UTC, marki1an commented on docs/application-settings.md
> +    `price_granularity` enum('LOW','MED','HIGH','AUTO','DENSE','UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
Okei, what can we do with that?

2023-02-15 12:05 UTC, SerhiiNahornyi commented
Resolving merge conflicts will require significant work, easier to implement from start in future, if needed

2023-02-15 12:05 UTC, closed without merging