Pass server info to request
prebid/prebid-server-java pull request #1758
Opened 2022-02-25 12:21 UTC by CTMBNara

2022-03-03 13:20 UTC, And1sS commented on src/main/java/org/prebid/server/auction/requestfactory/Ortb2ImplicitParametersResolver.java
>      public Ortb2ImplicitParametersResolver(boolean shouldCacheOnlyWinningBids,
Why have you reverted parameter and field name changes `shouldCacheOnlyWinningBids` -> `cacheOnlyWinningBids`?

2022-03-15 13:21 UTC, And1sS submitted a review, later dismissed

2022-05-05 07:34 UTC, SerhiiNahornyi requested changes

2022-05-05 07:34 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/auction/requestfactory/Ortb2ImplicitParametersResolver.java
> +                                           ExtRequestPrebidServer serverInfo,
Pls pass serverInfo properties, than create ExtRequestPrebidServer in class constructor

2022-05-05 11:53 UTC, SerhiiNahornyi approved these changes

2022-05-05 11:54 UTC, merged