Add additional metrcis for rejected responses
prebid/prebid-server-java pull request #1778
Opened 2022-03-22 12:39 UTC by CTMBNara

2022-03-22 15:55 UTC, And1sS requested changes

2022-03-22 15:55 UTC, And1sS commented on src/main/java/org/prebid/server/metric/Metrics.java
> +        accountMetrics.requests().incCounter(metricName);
Can be a one-liner.

2022-03-22 15:55 UTC, And1sS commented on src/main/java/org/prebid/server/exception/InvalidStoredRequestException.java
> +    private final List<String> messages;
Do we really need these messages? Looks like this field can be safely removed.

2022-03-22 15:55 UTC, And1sS commented on src/main/java/org/prebid/server/auction/requestfactory/Ortb2RequestFactory.java
> +        final Future<Account> accountResponse = StringUtils.isBlank(accountId)
Let's call it `accountFuture`, because it's not actually a response.

2022-03-22 15:55 UTC, And1sS commented on src/main/java/org/prebid/server/auction/StoredRequestProcessor.java
> +                String.format("Stored request processing failed: %s", cause.getMessage())));
Same here

2022-03-30 19:20 UTC, muuki88 approved these changes

2022-05-12 06:00 UTC, SerhiiNahornyi requested changes

2022-05-12 12:53 UTC, merged