AdyoulikeBidder: Add currency conversion
prebid/prebid-server-java pull request #1791
Opened 2022-03-29 10:43 UTC by marki1an

https://github.com/prebid/prebid-server/pull/2194

2022-03-29 13:27 UTC, And1sS requested changes
LGTM with minor changes

2022-03-29 13:27 UTC, And1sS commented on src/main/java/org/prebid/server/util/BidderUtil.java
> +
Pls, remove this method. It's purpose it not clear from it's name. I guess it's better to inline calls like that.

2022-03-29 13:27 UTC, And1sS commented on src/main/java/org/prebid/server/bidder/adyoulike/AdyoulikeBidder.java
> +                           JacksonMapper mapper) {
Very minor. Pls, add separate line

2022-04-01 09:05 UTC, And1sS approved these changes

2022-04-01 13:24 UTC, SerhiiNahornyi approved these changes

2022-04-01 13:24 UTC, merged