Core: Support prometheus namespace and subsystem prefixes
prebid/prebid-server-java pull request #1802
Opened 2022-04-04 14:35 UTC by And1sS

Corresponding issue: https://github.com/prebid/prebid-server-java/issues/1682

2022-04-07 17:20 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/spring/config/metrics/PrometheusConfiguration.java
> +    public static class PrometheusConfigurationProperties {
.

2022-05-16 06:52 UTC, SerhiiNahornyi requested changes

2022-05-16 06:52 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/metric/prometheus/NamespaceSubsystemSampleBuilder.java
> +    private static final String VALID_PREFIX_REGEX = "[a-zA-Z_:]?([a-zA-Z0-9_:])*";
Why we need capturing group here?

2022-05-16 06:52 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/metric/prometheus/NamespaceSubsystemSampleBuilder.java
> +                    "Invalid prefix, namespace and subsystem should match regex: " + VALID_PREFIX_REGEX);
Pls add prefix value `Invalid prefix %s`

2022-05-16 06:52 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/metric/prometheus/NamespaceSubsystemSampleBuilder.java
> +        prefix = toPrefix(namespace) + toPrefix(subsystem);
Do we need to trim namespace and subsystem values?

2022-05-16 06:52 UTC, SerhiiNahornyi commented on src/main/resources/metrics-config/labels.yaml
> +mappers:
Should it be prometheus.yaml or properties.yaml with prometheus.mappers structure?

2022-05-16 06:52 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/spring/config/metrics/PrometheusMapperConfiguration.java
> +public class PrometheusMapperConfiguration {
We have PrometheusConfiguration, why not to use it?

2022-05-16 12:00 UTC, SerhiiNahornyi approved these changes

2022-05-16 12:00 UTC, merged

2022-05-19 07:16 UTC, rmattis commented
@And1sS Did you test if this works together with the prometheus mappers from #1681?
I checked out this branch last week and mapping didn't work if a namespace/subsystem was configured.

2022-05-19 11:15 UTC, And1sS commented
> @And1sS Did you test if this works together with the prometheus mappers from #1681? I checked out this branch last week and mapping didn't work if a namespace/subsystem was configured.

The problem that you are facing with can be described as this:
1. `NamespaceSubsystemSampleBuilder` adds prefix to metric name (e.g. you had `"metric"`, now you have `"prefix_metric"`)
2. Prometheus library takes metric name from step 1 (now it's `"prefix_metric"`) and tries to match it with your `MapperConfig`(in config you have `match="metric"`)
So, after adding prefix you cannot match `"prefix_metric"` with `"metric"`.
To achieve what you want, change `"metric"` matcher to `"namespace_subsystem_metric"` in `classpath:/metrics-config/prometheus-labels.yaml`. 
There are other more flexible solutions, but they are hard to maintain(Just because we need to reimplement prometheus library logic). So we decided to stay with this implementation.

2022-05-19 11:24 UTC, rmattis commented
Yeah sure, I know that matching won't work with the prefix.
Is there anything against simply adjusting the `MapperConfig` dynamically with the prefix?
That would be a lot easier than adjusting lots of matches in the `prometheus-labels.yaml`

2022-05-19 12:23 UTC, And1sS commented
> Yeah sure, I know that matching won't work with the prefix. Is there anything against simply adjusting the `MapperConfig` dynamically with the prefix? https://github.com/prebid/prebid-server-java/pull/1802/files#diff-deb1c084b7d74d16f7e2374bea6fb085be0292098cc041fb5522ded767a31d3dR28-R32
> 
> That would be a lot easier than adjusting lots of matches in the `prometheus-labels.yaml`

It will add implicit modifications, which we didn't want to have. But, if you really need it, here it is: https://github.com/prebid/prebid-server-java/pull/1873
:)

2022-05-21 16:17 UTC, muuki88 commented
Thanks @And1sS 🤗 really appreciate it.

I understand that this may look unideal from a developer perspective, but as a user this reduces the amount of errors during configuration.