Add validate Alias GVL IDs
prebid/prebid-server-java pull request #1835
Opened 2022-04-22 14:47 UTC by marki1an

Corresponding ticket: [2126](https://github.com/prebid/prebid-server/pull/2126)
This logic was almost implemented at PBS Java  - [2098](https://github.com/prebid/prebid-server/issues/2098)

2022-05-04 14:45 UTC, CTMBNara requested changes

2022-05-04 14:45 UTC, CTMBNara commented on src/main/java/org/prebid/server/validation/RequestValidator.java
> +    private void validateAliasesGVLIDs(ExtRequestPrebid extRequestPrebid,
Nitpick: rename to `validateAliasesGvlIds`

2022-05-04 14:45 UTC, CTMBNara commented on src/main/java/org/prebid/server/validation/RequestValidator.java
> +                : Collections.emptyMap();
Can be simplified with
```
final Map<String, Integer> aliasGvlIds = MapUtils.emptyIfNull(extRequestPrebid.getAliasgvlids());
```

2022-05-04 14:45 UTC, CTMBNara commented on src/main/java/org/prebid/server/validation/RequestValidator.java
> +                        + " unknown bidder alias: %s", aliasgvlid.getKey(), aliasgvlid.getValue());
`aliasGvlId.getKey()` and `aliasGvlId.getValue()` are swapped.

2022-05-04 14:45 UTC, CTMBNara commented on src/main/java/org/prebid/server/validation/RequestValidator.java
> +                        + "remove this entry.", aliasgvlid.getKey(), aliasgvlid.getValue());
aliasGvlId.getKey() and aliasGvlId.getValue() are swapped.

2022-05-04 14:45 UTC, CTMBNara commented on src/main/java/org/prebid/server/validation/RequestValidator.java
> +        for (Map.Entry<String, Integer> aliasgvlid : aliasgvlids.entrySet()) {
Nitpick: rename `aliasgvlid ` to `aliasToGvlId`

2022-05-06 12:01 UTC, CTMBNara submitted a review, later dismissed

2022-06-10 13:03 UTC, SerhiiNahornyi approved these changes

2022-06-10 13:04 UTC, merged