Tests for account metrics level control
prebid/prebid-server-java pull request #1853
Opened 2022-05-10 10:47 UTC by marki1an

Tests for https://github.com/prebid/prebid-server-java/pull/1462

2022-05-15 16:05 UTC, marki1an commented on src/test/groovy/org/prebid/server/functional/model/config/AccountMetricsVerbosityLevel.groovy
> +    none, basic, detailed
Yeah, but we can change this when the core enum will be changed to uppercase.

2022-05-23 22:57 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/model/config/AccountMetricsVerbosityLevel.groovy
> +    none, basic, detailed
We can, but if you look at other enums, you will see that all the test enums are in uppercase. Please be consistent with other code.

2022-05-23 23:02 UTC, Net-burst requested changes

2022-05-23 23:02 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/tests/MetricsSpec.groovy
> +        then: "account.<account-id>.* shouldn't be exists"
"account.<account-id>.* metric shouldn't be populated"

2022-05-23 23:02 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/tests/MetricsSpec.groovy
> +        assert !metrics.find(it -> { it.key.startsWith("account.${accountId}") })
`metrics.find { it.key.startsWith("account.${accountId}") }`

2022-05-23 23:02 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/tests/MetricsSpec.groovy
> +        assert metrics["account.${accountId}.requests" as String] == 1
Please make sure that other account metrics are not populated.

2022-05-24 08:09 UTC, marki1an commented on src/test/groovy/org/prebid/server/functional/model/config/AccountMetricsVerbosityLevel.groovy
> +    none, basic, detailed
Yeah, you are right, we can do this.

2022-05-24 08:16 UTC, marki1an commented on src/test/groovy/org/prebid/server/functional/tests/AuctionSpec.groovy
> +        assert !metrics["account.${accountId}.adapter.generic.bids_received"    as String]
Done!

2022-05-25 03:14 UTC, Net-burst submitted a review, later dismissed
LGTM with minor remark

2022-05-25 03:14 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/tests/MetricsSpec.groovy
> +class MetricsSpec extends BaseSpec {
I recommend flushing the metrics before you enter this spec just to be sure that nothing will dirty your tests.

2022-05-27 09:54 UTC, Net-burst approved these changes
LGTM

2022-05-27 11:38 UTC, merged