Tests for `Cache-Control` header parsing
prebid/prebid-server-java pull request #1855
Opened 2022-05-11 08:06 UTC by marki1an

2022-05-11 08:22 UTC, Net-burst requested changes

2022-05-11 08:22 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsFetchingSpec.groovy
> +    def "PBS should reject fetch when response header is invalid"() {
Wrong check. PBS should not reject the auction when the header is invalid.

2022-05-11 08:22 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsFetchingSpec.groovy
> +        assert !response.seatbid?.isEmpty()
You should add a check that rule fetch has statred.

2022-05-11 08:22 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsFetchingSpec.groovy
> +        def header = [(headerKey): "no-cache, no-store, max-age=0, must-revalidate"]
Please create a test to make sure that PBS honors this parameter by redownloading rules after max age.

2022-05-12 11:34 UTC, closed without merging

2022-05-12 11:50 UTC, marki1an commented
Corresponding ticket: https://github.com/prebid/prebid-server-java/pull/1858