Cookiesync: Refactor configuration
prebid/prebid-server-java pull request #1954
Opened 2022-07-18 13:23 UTC by And1sS

This pr will make cookie-sync configuration to be more in-line with GO version.

Example of usersync configuration this pr introduces:
```yaml
    usersync:
      cookie-family-name: bidder_name
      redirect:
        url: bidder_url?gdpr={{gdpr}}&gdpr_consent={{gdpr_consent}}&us_privacy={{us_privacy}}&redir={{redirect_url}}
        support-cors: false
        uid-macro: '[BIDDER_UID_MACRO]'
        format-override: blank
      iframe:
        url: bidder_url?gdpr={{gdpr}}&gdpr_consent={{gdpr_consent}}&us_privacy={{us_privacy}}&redir={{redirect_url}}
        support-cors: false
        uid-macro: '[BIDDER_UID_MACRO]'
        format-override: pixel
```
fields `uid-macro` and `format-override` can be omitted, as well as `iframe`, `redirect` sections or even whole `usersync` section.
More detailes in docs pr: https://github.com/prebid/prebid.github.io/pull/3916

2022-07-25 10:31 UTC, SerhiiNahornyi requested changes

2022-07-25 10:31 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/auction/ExchangeService.java
> +                ? ObjectUtil.getIfNotNull(bidderCatalog.usersyncerByName(bidder), Usersyncer::getCookieFamilyName)
Just to think. Maybe it is worth making `usersyncerByName` return Optional?

2022-07-25 10:31 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/bidder/UsersyncFormat.java
> +    UsersyncFormat(String name) {
Can we delete this constructor and add `@RequiredArgsConstructor`?

2022-07-25 10:31 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/bidder/UsersyncInfoBuilder.java
> +public class UsersyncInfoBuilder {
Just to think. Can this one be `UsersyncInfoResolver`? Then it is not required to use this complex and useless for this case builder approach(whole class will be refactored)?

2022-07-25 10:31 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/bidder/UsersyncMethodType.java
> +    }
Maybe `@RequiredArgsConstructor`?

2022-08-29 13:01 UTC, Net-burst approved these changes
LGTM

2022-09-09 09:38 UTC, SerhiiNahornyi approved these changes

2022-09-09 09:38 UTC, merged

2023-01-18 10:07 UTC, richaudience commented
Hi Guys,
I see that the last Update was to 4 months, could you please tell me for when this programmed the next refactor for cookie-sync?
I need that upgrade the richaudience .yaml file
Cheers

2023-01-24 11:43 UTC, And1sS commented
> Hi Guys, I see that the last Update was to 4 months, could you please tell me for when this programmed the next refactor for cookie-sync? I need that upgrade the richaudience .yaml file Cheers

Hi, which update are you talking about? We have plenty of them planned :)

2023-02-01 07:22 UTC, richaudience commented
Hi,
I am talking specifically about the richaudience adapter, we only have to add the image sync to our .yalm file. That is possible?
Cheers

2023-03-30 06:40 UTC, richaudience commented
Hi guys!
Have been able to check my last comment?? I wait for your response.
Cheers