Test: Price Floors imp level floorMin
prebid/prebid-server-java pull request #1979
Opened 2022-08-03 11:17 UTC by marki1an

Test for: https://github.com/prebid/prebid-server-java/pull/1975

2022-08-04 10:18 UTC, SerhiiNahornyi commented on src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsCurrencySpec.groovy
> +        floorsProvider.setResponse(bidRequest.site.publisher.id, floorsResponse)
For a first request, we don't have floors data we have only a request to start fetching provider values
1) You can pass rules in request to use them from first call
2) The best case request.floorMin =2USD, imp.floorMin =4USD, modelGroup = 3USD (Resolved 4 for bidder)

2022-08-05 01:39 UTC, Net-burst requested changes

2022-08-05 01:39 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsCurrencySpec.groovy
> +                ext.prebid.floors.floorMin = BigDecimal.valueOf(2)
Same. Please don't hardcode magic numbers.

2022-08-05 01:39 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsCurrencySpec.groovy
> +                ext.prebid.floors.data.modelGroups[0].values = [(rule): BigDecimal.valueOf(3)]
Same. Please don't hardcode magic numbers.

2022-08-05 01:39 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsCurrencySpec.groovy
> +        def impExtPrebidFloorMin = BigDecimal.valueOf(4)
Please don't hardcode magic numbers.

2022-08-05 01:39 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsCurrencySpec.groovy
> +        def extPrebidFloorMin = BigDecimal.valueOf(5)
Same. Please don't hardcode magic numbers.

2022-08-11 13:32 UTC, Net-burst approved these changes
LGTM

2022-08-12 13:19 UTC, merged