Test: Add functional test for PG Targeting video lookup size
prebid/prebid-server-java pull request #2062
Opened 2022-10-24 11:46 UTC by marki1an

Test for https://github.com/prebid/prebid-server-java/pull/2058

2022-10-26 01:39 UTC, Net-burst requested changes

2022-10-26 01:39 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/tests/pg/TargetingSpec.groovy
> +    def "PBS should be able to match video size targeting taken from imp[].video sources by INTERSECTS matching function"() {
Only INTERSECTS?

2022-10-26 01:39 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/tests/pg/TargetingSpec.groovy
> +        def defaultLineItemSize = LineItemSize.defaultLineItemSize
`def defaultLineItemSize` -> `def lineItemSize`

2022-10-26 01:39 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/tests/pg/TargetingSpec.groovy
> +        def lineItemSize = plansResponse.lineItems.size()
You don't need this variable. Please inline it.

2022-10-26 09:08 UTC, marki1an commented on src/test/groovy/org/prebid/server/functional/tests/pg/TargetingSpec.groovy
> +    def "PBS should be able to match video size targeting taken from imp[].video sources by INTERSECTS matching function"() {
Yep

2022-10-27 11:19 UTC, Net-burst approved these changes
LGTM

2022-10-27 12:38 UTC, merged