Tests: Cookie-sync refine core logic of /cookie-sync endpoint
prebid/prebid-server-java pull request #2071
Opened 2022-11-04 12:34 UTC by marki1an

Tests for https://github.com/prebid/prebid-server-java/pull/2065

2022-11-11 02:09 UTC, Net-burst commented
Your branch also tracks an old state of feature branch. Please update.

2022-11-11 02:09 UTC, Net-burst requested changes

2022-11-11 02:09 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/tests/CookieSyncSpec.groovy
> +                ["host-cookie.family"                                : "generic",
This name should correspond to bidder name. Please or should correlate with family name override. Please make this obvious.

2022-11-11 02:09 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/tests/CookieSyncSpec.groovy
> +                 "host-cookie.cookie-name"                           : "rubicon",
Please extract this value to a variable. And preferably make it random to signify that name can be arbitrary.

2022-11-11 02:09 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/tests/CookieSyncSpec.groovy
> +                 "adapters.generic.usersync.redirect.format-override": "blank"])
Why do you need this here?

2022-11-11 02:09 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/tests/CookieSyncSpec.groovy
> +        and: "Default uids cookie with rubicon"
What do you mean by "with rubicon"? You're talking about host cookie here.

2022-11-11 02:09 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/tests/CookieSyncSpec.groovy
> +        def cookies = ["uids": UidsCookie.defaultUidsCookie, "rubicon": rubiconUidsCookie]
This it totally wrong as host cookie is a plain string. And again, don't hardcode names.

2022-11-11 02:09 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/tests/CookieSyncSpec.groovy
> +        and: "Response should contain rubicon uids"
Again, what do you mean by "rubicon uids"? You're once more talking about host cookie. But it's not clear to me what you are expecting.

2022-11-11 02:09 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/tests/CookieSyncSpec.groovy
> +    def "PBS cookie sync with host-cookie.family which hasn't the same value in both uids and from the direct host-cookie then should re-sync"() {
Again, I can't understand what this test should check. This applies to most test names. They are not clear and have typos or state weird stuff.

2022-11-11 02:12 UTC, Net-burst commented
Your tests are arranged in a weird way. They should go in the order of increasing complexity of the feature. Secondary features should also go after primary.

2022-11-13 15:43 UTC, marki1an commented on src/test/groovy/org/prebid/server/functional/model/request/cookiesync/CookieSyncRequest.groovy
> +    @JsonProperty("filterSettings")
`@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy)` defined here

2022-11-14 13:42 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/model/request/cookiesync/CookieSyncRequest.groovy
> +    @JsonProperty("filterSettings")
This is precisely why I asked to remove this annotation.

2022-11-14 13:48 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/model/request/cookiesync/CookieSyncRequest.groovy
> +    @JsonProperty("filterSettings")
Sorry, my bad. I was sure that I'm seeing camelCase there...

2022-11-15 04:21 UTC, Net-burst approved these changes
LGTM

2022-11-15 04:22 UTC, merged