IX: Add multi-format ad unit support
prebid/prebid-server-java pull request #2078
Opened 2022-11-09 14:35 UTC by liliana-sortable

This is a port of https://github.com/prebid/prebid-server/pull/2315

2022-11-16 10:20 UTC, SerhiiNahornyi requested changes

2022-11-16 10:20 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/bidder/ix/IxBidder.java
> +        Integer mType = bid.getMtype();
According to project style, we prefer to use final keyword on variables declaration

2022-11-16 10:20 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/bidder/ix/IxBidder.java
> +        BidType bidType = mType != null ? switch (bid.getMtype()) {
Seems bidType resolving logic can be moved to separate function

2022-11-16 10:20 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/bidder/ix/IxBidder.java
> +        Optional<String> prebidType = Optional.ofNullable(bid.getExt())
final

2022-11-16 10:20 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/bidder/ix/IxBidder.java
> +        Optional<String> prebidType = Optional.ofNullable(bid.getExt())
If you will move logic from 315 line to separate method, then you code will be easily simplified to
```java
return Optional.ofNullable(bid.getExt())
...
.orElseGet(()->methodWithLogicFrom315Line());
```

2022-11-16 10:20 UTC, SerhiiNahornyi commented on src/test/java/org/prebid/server/bidder/ix/IxBidderTest.java
> +    public void makeBidsShouldReturnCorrectTypeMTypeInResponse() throws JsonProcessingException {
makeBidsShouldReturnVideoBidIfMtypeIsTwo

2022-11-16 10:20 UTC, SerhiiNahornyi commented on src/test/java/org/prebid/server/bidder/ix/IxBidderTest.java
> +    public void makeBidsShouldReturnCorrectTypeMTypeInResponse() throws JsonProcessingException {
Also pls create test for every mtype possible value

2022-11-18 14:38 UTC, SerhiiNahornyi requested changes

2022-11-18 14:38 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/bidder/ix/IxBidder.java
> +                .orElse(getBidTypeFromImp(imps, bid.getImpid()));
If you are using `orElse` argument value will always be calculated, to had it calculated only if really needed
pls use (.orElseGet(() -> getBidTypeFromImp(imps, bid.getImpid())))

2022-11-18 14:38 UTC, SerhiiNahornyi commented on src/test/java/org/prebid/server/bidder/ix/IxBidderTest.java
> +        // then
Pls make 768 line empty

2022-11-18 14:38 UTC, SerhiiNahornyi commented on src/test/java/org/prebid/server/bidder/ix/IxBidderTest.java
> +        final Result<List<BidderBid>> result = ixBidder.makeBids(httpCall, null);
We prefer to have empty line between`given` `when` `then` blocks

2022-11-18 14:38 UTC, SerhiiNahornyi commented on src/test/java/org/prebid/server/bidder/ix/IxBidderTest.java
> +        final Result<List<BidderBid>> result = ixBidder.makeBids(httpCall, null);
Also pls check for similar occurences

2022-12-06 13:09 UTC, CTMBNara commented on src/main/java/org/prebid/server/bidder/ix/IxBidder.java
> +                .orElseGet(() -> getBidTypeFromImp(imps, bid.getImpid()));
What about to split different sources?
```
    private static BidType getBidType(Bid bid, List<Imp> imps) {
        return getBidTypeFromMtype(bid.getMtype())
                .or(() -> getBidTypeFromExtPrebidType(bid.getExt()))
                .orElseGet(() -> getBidTypeFromImp(imps, bid.getImpid()));
    }

    private static Optional<BidType> getBidTypeFromMtype(Integer mType) {
        final BidType bidType = mType != null ? switch (mType) {
            case 1 -> BidType.banner;
            case 2 -> BidType.video;
            case 3 -> BidType.audio;
            case 4 -> BidType.xNative;
            default -> null;
        } : null;

        return Optional.ofNullable(bidType);
    }

    private static Optional<BidType> getBidTypeFromExtPrebidType(ObjectNode bidExt) {
        return Optional.ofNullable(bidExt)
                .map(ext -> ext.get("prebid"))
                .map(prebid -> prebid.get("type"))
                .map(JsonNode::asText)
                .map(BidType::fromString);
    }

...
```

2022-12-06 13:09 UTC, CTMBNara commented on src/test/java/org/prebid/server/bidder/ix/IxBidderTest.java
> +                .containsExactly(BidType.video);
Why do we need to assert our input?

2022-12-08 19:17 UTC, CTMBNara commented on src/test/java/org/prebid/server/bidder/ix/IxBidderTest.java
> +                .containsExactly(BidType.video);
Only the adapter can affect this result. If logic appears that somehow changes this object, the corresponding test will be written.

2022-12-12 06:43 UTC, SerhiiNahornyi approved these changes

2022-12-12 06:43 UTC, merged