Lower `tmax` for bidders
prebid/prebid-server-java pull request #2113
Opened 2023-01-12 10:34 UTC by CTMBNara

2023-01-16 15:13 UTC, SerhiiNahornyi requested changes

2023-01-16 15:13 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
> +            @Value("${auction.biddertmax.max:#{null}}") Long maxTimeout,
Can we have `maxTimeout ` of primitive type?

2023-01-16 15:13 UTC, SerhiiNahornyi commented on src/test/java/org/prebid/server/auction/ExchangeServiceTest.java
> +    private TimeoutFactory timeoutFactory;
Why we don't just mock this class?

2023-01-16 19:07 UTC, SerhiiNahornyi submitted a review, later dismissed

2023-01-17 02:54 UTC, Net-burst commented on docs/config-app.md
> +- `auction.max-timeout-ms` - maximum operation timeout for OpenRTB Auction requests. Deprecated.
Why is this deprecated? AFAIK this property remains valid.

2023-01-17 16:11 UTC, SerhiiNahornyi approved these changes

2023-01-17 16:12 UTC, merged