testOpenrtb2AuctionCoreFunctionality migrated to generic bidder
prebid/prebid-server-java pull request #2115
Opened 2023-01-13 14:26 UTC by ValeriiBarsuk

testOpenrtb2AuctionCoreFunctionality migrated to generic bidder

2023-01-13 14:43 UTC, SerhiiNahornyi requested changes
Pls delete previous files

2023-01-14 16:51 UTC, ValeriiBarsuk commented
> 
Files is used for the another test
org.prebid.server.it.RubiconTest#testOpenrtb2AuctionCoreFunctionality

2023-01-16 08:33 UTC, SerhiiNahornyi submitted a review, later dismissed

2023-01-16 15:04 UTC, SerhiiNahornyi approved these changes

2023-01-16 15:04 UTC, merged