Functional tests for `<bidder>.usersync.enabled` property
prebid/prebid-server-java pull request #2145
Opened 2023-02-06 11:43 UTC by marki1an

2023-02-06 21:42 UTC, Net-burst requested changes

2023-02-06 21:42 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/tests/UserSyncSpec.groovy
> +    private static final Map GENERIC_USERSYNC_CONFIG = ["adapters.${GENERIC.value}.usersync.${IFRAME.value}.url"         : "$networkServiceContainer.rootUri/generic-usersync&redir={{redirect_url}}".t
Please don't use raw types. Either use `def` or use fully-qualified types.

2023-02-06 21:42 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/tests/UserSyncSpec.groovy
> +    def "PBS cookie sync should sync bidder which bidder.usersync.enabled=true"() {
"PBS cookie sync should sync bidder when bidder.usersync.enabled=true"

2023-02-06 21:42 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/tests/UserSyncSpec.groovy
> +    def "PBS cookie sync shouldn't sync bidder which bidder.usersync.enabled=false"() {
"PBS cookie sync shouldn't sync bidder when bidder.usersync.enabled=false"

2023-02-08 08:57 UTC, SerhiiNahornyi approved these changes

2023-02-08 08:57 UTC, merged

2023-02-08 09:03 UTC, Net-burst reviewed
LGTM