Tests: Functional tests for GPP /cookie_sync endpoint.
prebid/prebid-server-java pull request #2181
Opened 2023-02-16 09:28 UTC by osulzhenko

2023-03-02 04:03 UTC, Net-burst requested changes
Very good overall, but left some remarks. Most of them apply to all of the tests.

2023-03-02 04:03 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/tests/GppCookieSyncSpec.groovy
> +            it.bidders = []
Do you need to explicitly override seemingly irrelevant parameter?

2023-03-02 04:03 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/tests/GppCookieSyncSpec.groovy
> +            it.bidders = []
Do you need to explicitly override seemingly irrelevant parameter?

2023-03-02 04:03 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/tests/GppCookieSyncSpec.groovy
> +        then: "Response should contain gdpr as 0"
Please add a blank line between sections.

2023-03-02 04:03 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/tests/GppCookieSyncSpec.groovy
> +    def "PBS cookie sync request should reflect warning when GPP is contains 2  and gdpr is not 1"() {
1) "reflect" -> "respond with"
2) "PBS cookie sync request should respond with a warning when GPP SID contains 2 and gdpr is not 1"

2023-03-02 14:15 UTC, marki1an requested changes

2023-03-02 14:15 UTC, marki1an commented on src/test/groovy/org/prebid/server/functional/tests/privacy/GppCookieSyncSpec.groovy
> +        assert response.ext.warnings == "GPP scope does not match TCF2 scope"
Same

2023-03-02 14:15 UTC, marki1an commented on src/test/groovy/org/prebid/server/functional/tests/privacy/GppCookieSyncSpec.groovy
> +        assert prebidServerService.sendCollectedMetricsRequest() == [ "cookie_sync.generic.tcf.blocked": 0 ]
Redundant

2023-03-02 14:15 UTC, marki1an commented on src/test/groovy/org/prebid/server/functional/tests/privacy/GppCookieSyncSpec.groovy
> +        def invalidGpp = PBSUtils.getRandomString(20)
just `randomString`

2023-03-02 14:15 UTC, marki1an commented on src/test/groovy/org/prebid/server/functional/tests/privacy/GppCookieSyncSpec.groovy
> +        assert prebidServerService.sendCollectedMetricsRequest() == [ "cookie_sync.generic.tcf.blocked": 0 ]
Same. Redundant

2023-03-02 14:15 UTC, marki1an commented on src/test/groovy/org/prebid/server/functional/tests/privacy/GppCookieSyncSpec.groovy
> +        expect: "Response should contain warning"
use `then`, `expect` keyword doesn't present

2023-03-02 14:15 UTC, marki1an commented on src/test/groovy/org/prebid/server/functional/tests/privacy/GppCookieSyncSpec.groovy
> +    def "PBS should copy regs.gpp to user.consent when gppSid contains 2, gpp is TCF2-EU and user.consent isn't specified without any warning from cookie sync request"() {
We can't test this scenario

2023-03-02 14:15 UTC, marki1an commented on src/test/groovy/org/prebid/server/functional/tests/privacy/GppCookieSyncSpec.groovy
> +    def "PBS should copy gpp to usPrivacy when gppSid contains 6, gpp is TCF2-EU and us_privacy isn't specified without warnings"() {
Same we can't test it

2023-03-02 14:15 UTC, marki1an commented on src/test/groovy/org/prebid/server/functional/tests/privacy/GppCookieSyncSpec.groovy
> +    def "PBS should copy regs.gpp to user.consent when gppSid contains 2, gpp is TCF2-EU and user.consent are different with warning from cookie sync request"() {
Same. We can't test it

2023-03-02 14:15 UTC, marki1an commented on src/test/groovy/org/prebid/server/functional/tests/privacy/GppCookieSyncSpec.groovy
> +        assert prebidServerService.sendCollectedMetricsRequest() == ["cookie_sync.generic.tcf.blocked": 0]
Redundant

2023-03-03 12:09 UTC, Net-burst approved these changes
LGTM

2023-03-03 20:54 UTC, merged