undertone params under ext
prebid/prebid-server-java pull request #2199
Opened 2023-02-26 14:02 UTC by tamarm-perion

2023-02-28 10:28 UTC, CTMBNara reviewed
@tamarm-perion Please, cover the changed logic with unit tests.

2023-03-06 11:00 UTC, SerhiiNahornyi approved these changes

2023-03-06 11:00 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/bidder/undertone/proto/UndertoneRequestExt.java
> +    int adapterId;
We prefer not to use primitives in such models, pls use `Integer`

2023-03-06 11:00 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/bidder/undertone/proto/UndertoneRequestExt.java
> +@Value
@Value(staticConstructor = "of")

2023-03-06 11:00 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/bidder/undertone/proto/UndertoneRequestExt.java
> +    @JsonProperty("version")
No need of `@JsonProperty("version")` because variable name is similar, so it will serialize to `version` even without annotation

2023-03-06 11:00 UTC, SerhiiNahornyi commented on src/test/java/org/prebid/server/bidder/undertone/UndertoneBidderTest.java
> +        final int placementId = 12345;
We prefer not to use such variables in tests, but set values without previous variables creation
Like
``` java
ExtImpUndertone.of(1234, 12345)
final Publisher expectedPublisher = Publisher.builder()
                .id("1234")
                .build();
```

2023-03-06 11:04 UTC, SerhiiNahornyi requested changes

2023-03-06 11:04 UTC, SerhiiNahornyi commented on src/test/java/org/prebid/server/bidder/undertone/UndertoneBidderTest.java
> +        final Imp.ImpBuilder impBuilderInstance = Imp.builder()
Pls don't use same impBuilder for given and expected values

2023-03-07 12:33 UTC, SerhiiNahornyi approved these changes

2023-03-07 12:33 UTC, merged