Test: Fix `PG` flaky functional tests
prebid/prebid-server-java pull request #2219
Opened 2023-03-10 16:16 UTC by marki1an

Error message:
```
	org.spockframework.runtime.SpockComparisonFailure: Condition not satisfied:

deliveryStatistics.requestCount == initialRequestCount
|                  |            |  |
|                  1            |  0
|                               false
<org.prebid.server.functional.testcontainers.scaffolding.pg.DeliveryStatistics@62041909 mockServerClient=org.mockserver.client.MockServerClient@e0989ce endpoint=/deals/report/delivery>
```

2023-03-13 16:30 UTC, Net-burst requested changes

2023-03-31 12:02 UTC, Net-burst approved these changes

2023-03-31 12:21 UTC, Net-burst commented
Let's try this approach instead of wait in the assertions. I can't understand why your approach works.
```
    def setup() {
        pgPbsService.sendForceDealsUpdateRequest(ForceDealsUpdateRequest.sendReportRequest)
        pgPbsService.sendForceDealsUpdateRequest(ForceDealsUpdateRequest.invalidateLineItemsRequest)
        deliveryStatistics.reset()
        PBSUtils.waitUntil { deliveryStatistics.requestCount == 0 }
    }
```

2023-04-06 09:45 UTC, marki1an commented
Re-implemented in https://github.com/prebid/prebid-server-java/pull/2271

2023-04-06 09:45 UTC, closed without merging