Globalsun: Add new bidder
prebid/prebid-server-java pull request #2237
Opened 2023-03-20 14:25 UTC by ValeriiBarsuk

Globalsun: Add new bidder

2023-03-24 13:05 UTC, SerhiiNahornyi requested changes

2023-04-04 00:57 UTC, And1sS requested changes

2023-04-04 00:57 UTC, And1sS commented on src/main/resources/bidder-config/globalsun.yaml
> +      site-media-type:
Wrong spelling, it should be `site-media-types`.

2023-04-04 13:11 UTC, SerhiiNahornyi requested changes

2023-04-04 13:11 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/bidder/globalsun/model/GlobalsunImpExtBidder.java
> +    @JsonProperty(value = "placementId")
I mean you can write like this
`@JsonProperty("placementId")`

2023-04-04 13:11 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/bidder/globalsun/GlobalsunBidder.java
> +    private Imp modifyImp(Imp imp, ExtImpGlobalsun extImpAndGlobalsun) {
Pls put methods in call order
makeRequests
... makeRequest related
makeBids
...makeBids related

2023-04-04 13:11 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/bidder/globalsun/GlobalsunBidder.java
> +    private GlobalsunImpExtBidder resolveOutgoingImpExt(ExtImpGlobalsun extImpAndGlobalsun) {
Can be static

2023-04-10 12:23 UTC, SerhiiNahornyi approved these changes

2023-04-10 13:04 UTC, And1sS approved these changes

2023-04-10 13:05 UTC, merged