Started rewriting old usage of embedded vertx to verticles deployment…
prebid/prebid-server-java pull request #2306
Opened 2023-04-20 14:43 UTC by And1sS

… style

2023-04-23 15:56 UTC, SerhiiNahornyi requested changes

2023-04-23 15:56 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/handler/OptoutHandler.java
> +    }
I don't like the idea that handler, can have more then one endpoint.
It makes a thought that single responsibility principle is broken.
Maybe it is worth to separate for two different? And make ApllicationResource class have only `endpoint` method?

2023-04-23 15:56 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/vertx/verticles/VerticleDeployer.java
> +    private static final int TIMEOUT_MILLIS = 5000;
To application properties?

2023-04-23 15:56 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/vertx/verticles/server/ServerVerticle.java
> +    private void onServerStarted(AsyncResult<HttpServer> result) {
onServerStart

2023-04-23 15:56 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/vertx/verticles/server/application/ApplicationResource.java
> +public interface ApplicationResource extends Handler<RoutingContext> {
HttpResource extends ApplicationResource?
And use HttpResource for handlers?

2023-04-23 15:56 UTC, SerhiiNahornyi commented on src/main/resources/application.yaml
> +    server-instances: 10
Why 10?

2023-04-23 15:56 UTC, SerhiiNahornyi commented on src/main/resources/application.yaml
> +    enabled: true
Why changed?

2024-02-23 14:09 UTC, SerhiiNahornyi requested changes

2024-02-23 14:09 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/spring/config/server/admin/AdminServerAuthProvider.java
> +        if (StringUtils.isNotBlank(requestPassword) && Objects.equals(storedPassword, requestPassword)) {
StringUtils.equesl

2024-03-05 13:29 UTC, CTMBNara commented on src/main/java/org/prebid/server/spring/config/metrics/PrometheusConfiguration.java
> +        };
What about to wrap `MetricsHandler` with `ApplicationResource` implementation?

2024-03-07 14:13 UTC, CTMBNara requested changes

2024-03-07 14:13 UTC, CTMBNara commented on src/main/java/org/prebid/server/spring/config/server/application/ApplicationServerConfiguration.java
> +    }
I would get rid of this factory. It feels too redundant for me.

2024-03-07 14:13 UTC, CTMBNara commented on src/main/java/org/prebid/server/spring/config/server/application/ApplicationServerConfiguration.java
> +            StaticHandler staticHandler) {
I don't see any other use of Vertx in this file, let's inject it directly to create this bean.

2024-03-07 14:13 UTC, CTMBNara commented on src/main/java/org/prebid/server/vertx/verticles/server/ServerVerticle.java
> +        final HttpServerOptions httpServerOptions = ObjectUtils.defaultIfNull(serverOptions, new HttpServerOptions());
`ObjectUtils.getIfNull(serverOptions, HttpServerOptions::new);`

2024-04-08 21:54 UTC, Net-burst approved these changes
LGTM

2024-04-08 22:56 UTC, merged