Add `ActivityInfrastructure`
prebid/prebid-server-java pull request #2308
Opened 2023-04-21 09:34 UTC by CTMBNara

2023-05-03 13:01 UTC, And1sS requested changes

2023-05-04 09:43 UTC, CTMBNara commented on src/main/java/org/prebid/server/analytics/reporter/AnalyticsReporterDelegator.java
> +                .maskDeviceForActivity(device, disallowTransmitUfpd, disallowTransmitGeo);
Considering that calls to these methods are necessary to mask the user and device, it was decided to rename the method to better match the logic of its use.

2023-05-04 09:49 UTC, And1sS submitted a review, later dismissed

2023-05-04 13:01 UTC, SerhiiNahornyi approved these changes

2023-05-04 13:02 UTC, merged