Change Adhese bidder to use /openrtb2 endpoint
prebid/prebid-server-java pull request #2447
Opened 2023-06-21 08:40 UTC by karol-adhese

- switch endpoint and therefore adjust the payload manipulation, adjust tests
- Go version of the server does not have the same changes, PR for those should follow

2023-06-22 07:36 UTC, JakubKAdhese approved these changes

2023-06-29 12:21 UTC, And1sS requested changes

2023-06-29 12:21 UTC, And1sS commented on src/main/java/org/prebid/server/bidder/adhese/AdheseBidder.java
> +    private BidRequest modifyBidRequest(BidRequest bidRequest, ExtImpAdhese extImpAdhese) {
Please, place methods in call order.

2023-06-29 12:21 UTC, And1sS commented on src/main/java/org/prebid/server/bidder/adhese/AdheseBidder.java
> +        Imp imp = bidRequest.getImp().get(0).toBuilder()
Should be final, also please, check for similar occurences.

2023-06-29 12:21 UTC, And1sS commented on src/main/java/org/prebid/server/bidder/adhese/AdheseBidder.java
> +        return bidResponse.getSeatbid().stream()
Can be simplified to smth like:
```java
return Optional.ofNullable(bidResponse)
    .map(BidResponse::getSeatbid)
    .stream()
    .flatMap(Collection::stream)
    .map(SeatBid::getBid)
    .filter(Objects::nonNull)
    .flatMap(Collection::stream)
    .findFirst();
```

2023-06-30 09:21 UTC, karol-adhese commented
I made the requested changes (in separate commits), please verify again

2023-07-03 09:48 UTC, And1sS approved these changes

2023-07-03 10:23 UTC, merged