Split multiformat bid request into 1 bid request per media type
prebid/prebid-server-java pull request #2476
Opened 2023-07-04 19:37 UTC by maxime-dupuis

Mirroring this [pull request](https://github.com/prebid/prebid-server/pull/2866) in the Golang adapter

2023-07-05 19:07 UTC, maxime-dupuis commented
The functional tests fail for this PR but also for other PR's. So I think this one doesn't cause the problem

2023-07-17 12:29 UTC, SerhiiNahornyi commented
@maxime-dupuis Could you pls merge master to this PR, it should fix tests

2023-07-17 16:42 UTC, maxime-dupuis commented
> @maxime-dupuis Could you pls merge master to this PR, it should fix tests

@SerhiiNahornyi Thanks I merged it. I don't seem to be able to rerun the tests though, can you do it?

2023-07-19 20:56 UTC, CTMBNara requested changes

2023-07-19 20:56 UTC, CTMBNara commented on src/test/java/org/prebid/server/bidder/sharethrough/SharethroughBidderTest.java
> +                .allSatisfy(impression -> assertThat(impression.getAudio()).isNull());
Please, assert audio object in previous blocks. For example:
```
                         impression -> {
                             assertThat(impression.getBanner()).isEqualTo(banner);
                             assertThat(impression.getVideo()).isNull();
                             assertThat(impression.getXNative()).isNull();
                             assertThat(impression.getAudio()).isNull();
                         },
```

2023-07-23 11:03 UTC, CTMBNara approved these changes

2023-07-24 08:20 UTC, SerhiiNahornyi approved these changes
LGTM

2023-07-24 08:20 UTC, merged