Rubicon: bidonmultiformat updates
prebid/prebid-server-java pull request #2503
Opened 2023-07-14 12:50 UTC by And1sS

2023-07-17 12:24 UTC, SerhiiNahornyi requested changes

2023-07-17 12:24 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/bidder/rubicon/RubiconBidder.java
> +        return Optional.ofNullable(imp)
Imp can be null?

2023-07-17 12:24 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/bidder/rubicon/RubiconBidder.java
> +                .or(() -> Optional.ofNullable(extImpRubicon.getParams()).map(ExtImpRubiconParams::getFormats))
`.map` on new line?

2023-07-17 12:33 UTC, And1sS commented on src/main/java/org/prebid/server/bidder/rubicon/RubiconBidder.java
> +                .or(() -> Optional.ofNullable(extImpRubicon.getParams()).map(ExtImpRubiconParams::getFormats))
Sorry for removed comment, missclick.

2023-07-23 13:58 UTC, muuki88 commented
Do I get this change right, that multi format bid requests will trigger a bid request to magnite for every media type?

2023-08-02 09:37 UTC, And1sS commented
> Do I get this change right, that multi format bid requests will trigger a bid request to magnite for every media type?

Yes!

2023-08-15 11:51 UTC, SerhiiNahornyi approved these changes

2023-08-15 11:51 UTC, merged