Tests: Fix fluke when timeout message differs in timeout spec
prebid/prebid-server-java pull request #2531
Opened 2023-07-29 13:11 UTC by Lightwood13

There is a possibility that PBS will return timeout error with message `"Timeout period of %dms has been exceeded"` [here](https://github.com/Lightwood13/prebid-server-java/blob/a53dcbad135bc0397780c665c338a83ac99f6766/src/main/java/org/prebid/server/vertx/http/BasicHttpClient.java#L89) instead of `"Timeout has been exceeded"` which is returned [here](https://github.com/Lightwood13/prebid-server-java/blob/a53dcbad135bc0397780c665c338a83ac99f6766/src/main/java/org/prebid/server/vertx/http/BasicHttpClient.java#L51). This leads to inconsistent behavior in test runs.

This pr fixes test to address this possibility.

2023-07-29 13:27 UTC, And1sS approved these changes

2023-07-31 08:26 UTC, marki1an approved these changes

2023-07-31 12:08 UTC, CTMBNara approved these changes

2023-08-07 13:41 UTC, SerhiiNahornyi requested changes
This is not a fix, but a hide of the problem
@osulzhenko Please provide a better solution

2023-08-17 12:32 UTC, osulzhenko requested changes
Hello,
thank you for the time and effort in addressing this matter. Regrettably, it appears that the potential issue is not related to the tests themselves.
Concerning the test cases outlined in `TimeoutSpec.groovy`, we have:
`"PBS amp should return an error when the auction.biddertmax.min value is insufficient for the bidder request."`
`"PBS auction should return an error when the auction.biddertmax.min value is inadequate for the bidder request."`
In these scenarios, the error message `"Timeout period of %dms has been exceeded"` will not appear. Instead, the amp and auction requests will undergo processing via the `HttpBidderRequester.doRequest` and `CircuitBreakerSecuredHttpClient.request` methods. Pay attention I am mentioning methods of another class, not the one you specified.
The only request that will interact with the `BasicHttpClient.request` method pertains to the currency-file, which adheres to the default timeout indicated in the `currency-converter.external-rates.default-timeout-ms` field within the `resources/application.yaml` file.
It's important to note that this default request applies to all containers. Consequently, I recommend extending the timeout if you encounter this error within the specified test cases. There's a slight possibility that other test cases and the application itself are not functioning correctly on your machine (with your hardware but our timeout).
Furthermore, you should encounter challenges with the `currency-converter`, you have the option to adjust the timeouts for other fundamental requests utilized in additional test cases. These may be requests like: `vendorlist`, `floors-provider`, `geolocation`, and similar ones.
One more time, your dedication to addressing these intricacies is genuinely appreciated.

2023-10-19 12:56 UTC, SerhiiNahornyi commented
Closed due to inactivity

2023-10-19 12:56 UTC, closed without merging