Tests: Increase test coverage for `cookie_sync`
prebid/prebid-server-java pull request #2570
Opened 2023-08-10 10:12 UTC by marki1an

2023-09-07 11:56 UTC, osulzhenko requested changes

2023-09-07 11:56 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/service/PrebidServerService.groovy
>          def cookies = [:]
can we use?
` def cookies = additionalCookies ?: [:]`

2023-09-07 11:56 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/CookieSyncSpec.groovy
> +            iframe = new MethodFilter(bidders: "*", filter: EXCLUDE)
Can we make this `"*"` as a constant? So that it is clear from the outside what it is responsible for. The more it repeats itself.

2023-09-07 11:56 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/CookieSyncSpec.groovy
> +        and: "Response shouldn't contain proper"
and: "Response should contain amount of bidder then define in request"

2023-09-07 11:56 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/CookieSyncSpec.groovy
> +        assert response?.getBidderStatus()?.size() == 8
not sure that just the number 8 is enough. Maybe we can get it from PBS_CONFIG, or specify what it means.

2023-09-07 11:56 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/CookieSyncSpec.groovy
> +        then: "Response should have status"
maybe `then: "Response should have status with limit the number of returned bidders"`?

2023-09-07 13:29 UTC, osulzhenko approved these changes

2023-10-23 14:29 UTC, Net-burst requested changes

2023-10-23 14:29 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/model/bidder/BidderName.groovy
> +    ALIAS, GENERIC, RUBICON, APPNEXUS, BOGUS, OPENX, ACEEX, ACUITYADS, GRID, AAX, ADKERNEL, MEDIANET
Please rearrange the list and put `BOGUS` somewhere at the beginning.

2023-10-23 14:29 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/model/mock/services/vendorlist/VendorListResponse.groovy
> +        static Vendor getDefaultVendor(Integer id) {
`id` can be `null`? If not, please use `int` to signify this.

2023-10-23 14:29 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/model/request/cookiesync/MethodFilter.groovy
> +    // Here we use wildcard for different compatibility
I don't understand what you meant by this comment.

2023-10-23 14:29 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/service/PrebidServerService.groovy
> +    CookieSyncResponse sendCookieSyncRequest(CookieSyncRequest request, String uidsCookie) {
What was the point of duplicating the method, but using a String instead of POJO?

2023-10-23 14:29 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/service/PrebidServerService.groovy
> +                                    String uidsAudit = null) {
This shouldn't be here at all.

2023-12-11 18:09 UTC, osulzhenko requested changes

2023-12-11 18:09 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/CookieSyncSpec.groovy
> +    def "PBS cookie sync request should return maximum 8 coop sync bidder when limit is not specified"() {
not fully clear why it should be 8, maybe `all available bidders`?

2023-12-11 18:09 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/CookieSyncSpec.groovy
> +        and: ""
`and: "bidders matched with requests"`?

2023-12-11 18:09 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/CookieSyncSpec.groovy
> +        given: "Empty cookie sync request body"
maybe not empty but without account?

2023-12-11 18:09 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/CookieSyncSpec.groovy
> +        given: "Empty cookie sync request body"
invalid description

2023-12-11 18:09 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/CookieSyncSpec.groovy
> +        given: "Empty cookie sync request body"
invalid description

2023-12-11 18:09 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/CookieSyncSpec.groovy
> +        given: "Empty cookie sync request body"
invalid description

2023-12-14 14:01 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/CookieSyncSpec.groovy
> +        def defaultLimit
defaultLimit is null?

2023-12-15 12:55 UTC, osulzhenko requested changes

2023-12-15 12:55 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/CookieSyncSpec.groovy
> +        assert response.getBidderUserSync(ADKERNEL)
also add a total number check, for make sure that it all

2023-12-15 12:55 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/CookieSyncSpec.groovy
> +        given: "Empty cookie sync request body"
given: "Default cookie sync request"?

2023-12-15 12:55 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/CookieSyncSpec.groovy
> +        given: "Empty cookie sync request body"
given: "Default cookie sync request with limit"? Same for similar one

2023-12-15 12:55 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/CookieSyncSpec.groovy
> +    def "PBS cookie sync request should fill response with 8 coop sync bidder when limit is not specified"() {
maybe not with magic 8, but with `all available bidders`?

2023-12-15 12:55 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/CookieSyncSpec.groovy
> +        then: "Response should contains 8 coop sync bidders"
same

2023-12-15 12:55 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/CookieSyncSpec.groovy
> +            it.limit = 4
can be replaced by random?

2023-12-21 08:24 UTC, osulzhenko approved these changes
LGTM

2024-01-03 04:50 UTC, Net-burst approved these changes
LGTM

2024-01-03 13:10 UTC, merged