Conversant: rebrand to Epsilon
prebid/prebid-server-java pull request #2654
Opened 2023-09-26 23:12 UTC by kim-ng93

2023-10-02 10:48 UTC, CTMBNara requested changes

2023-10-02 10:48 UTC, CTMBNara commented on src/test/java/org/prebid/server/it/EpsilonTest.java
> +    public void openrtb2AuctionShouldRespondWithBidsFrom() throws IOException, JSONException {
Please, rename to `openrtb2AuctionShouldRespondWithBidsFromConversant`

2023-10-02 10:48 UTC, CTMBNara commented on src/test/resources/org/prebid/server/it/openrtb2/epsilon/alias/test-auction-epsilon-request.json
>        },
This `aliases` block is redundant. If you wanna be sure, that aliases feature properly works, change it to be like this:
```
      "ext": {
         "conversantAlias": {
           "site_id": "site_id"
         }
       }
      ....
      "aliases": {
         "conversantAlias": "conversant"
       },
```

2023-10-11 10:34 UTC, And1sS approved these changes

2023-10-16 13:47 UTC, SerhiiNahornyi approved these changes

2023-12-06 11:40 UTC, merged