Update adnuntius bidder
prebid/prebid-server-java pull request #2693
Opened 2023-10-11 14:48 UTC by marki1an

2023-10-16 13:14 UTC, And1sS requested changes

2023-10-16 13:14 UTC, And1sS commented on src/main/java/org/prebid/server/bidder/adnuntius/AdnuntiusBidder.java
> +        }
In go they check with respect to case-insensitivity.

2023-10-16 13:14 UTC, And1sS commented on src/main/java/org/prebid/server/bidder/adnuntius/AdnuntiusBidder.java
> +        return bidderBids;
Can be simplified to:
```java
final String currency = extractCurrency(validAdsUnitToImp);
final Stream<BidderBid> generalBids = validAdsUnitToImp.stream()
                .map(adsUnitWithImpId -> makeGeneralBid(adsUnitWithImpId, currency));
final Stream<BidderBid> dealBids = validAdsUnitToImp.stream()
                .filter(adsUnitWithImpId -> CollectionUtils.isNotEmpty(adsUnitWithImpId.getAdsUnit().getDeals()))
                .map(adsUnitWithImpId -> makeDealsBid(adsUnitWithImpId, currency))
                .filter(Objects::nonNull);

return Stream.concat(generalBids, dealBids).toList();
```

No need to create temporary lists every time and put pressure on GC.

2023-10-16 13:14 UTC, And1sS commented on src/test/java/org/prebid/server/bidder/adnuntius/AdnuntiusBidderTest.java
> +        assertThat(result.getErrors()).hasSize(0);
`.isEmpty()` is better than `.hasSize(0)` as its easier to read. Please, replace with call to `.isEmpty()` and also check for similar occurences.

2023-11-08 14:02 UTC, SerhiiNahornyi requested changes

2023-11-08 15:08 UTC, SerhiiNahornyi approved these changes

2023-11-08 15:14 UTC, And1sS approved these changes

2023-11-08 15:17 UTC, merged