Add product support for gumgum
prebid/prebid-server-java pull request #2724
Opened 2023-10-24 14:34 UTC by gg-natalia

IN this changes we will start to pass the product param from Prebid Server to GG Ad Server under the impressions.ext param.
For any questions/comments pls feel free to reach out
Thanks
Natalia Castiglioni

2023-10-26 12:21 UTC, SerhiiNahornyi requested changes

2023-10-26 12:21 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/bidder/gumgum/GumgumBidder.java
> +        //Product parameter
Comment is redundant, please remove

2023-10-27 11:48 UTC, gg-natalia commented on src/main/java/org/prebid/server/bidder/gumgum/GumgumBidder.java
> +        //Product parameter
Changed, ty

2023-10-30 12:58 UTC, SerhiiNahornyi approved these changes
LGTM

2023-10-30 13:06 UTC, SerhiiNahornyi reviewed
[INFO] Starting audit...
Error:  /home/runner/work/prebid-server-java/prebid-server-java/src/main/java/org/prebid/server/bidder/gumgum/GumgumBidder.java:127: Line has trailing spaces. [RegexpSingleline]
Audit done.


You can check build locally by running `mvn clean package -f extra` even `mvn clean package` will be enough

2023-10-30 14:29 UTC, SerhiiNahornyi approved these changes

2023-10-30 15:45 UTC, merged