Mobilefuse Adapter Updates
prebid/prebid-server-java pull request #2748
Opened 2023-11-06 14:33 UTC by AntoxaAntoxic

2023-11-08 14:33 UTC, SerhiiNahornyi requested changes

2023-11-08 14:33 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/bidder/mobilefuse/MobilefuseBidder.java
> +    private ObjectNode parseSkadn(Imp imp) {
It's enough to pass only ObjectNode impExt, no need for whole imp

2023-11-08 15:13 UTC, AntoxaAntoxic commented on src/test/resources/org/prebid/server/it/openrtb2/mobilefuse/test-auction-mobilefuse-request.json
> +      "ext": {
@SerhiiNahornyi this check is pretty cheap, so I think it's fine to keep it

P.S. it's covered in the unit tests

2023-11-08 15:21 UTC, SerhiiNahornyi commented on src/test/resources/org/prebid/server/it/openrtb2/mobilefuse/test-auction-mobilefuse-request.json
> +      "ext": {
About a year ago, we discussed having IT tests maximum simple.
And we updated them to be that simple and similar.

2023-11-09 11:41 UTC, SerhiiNahornyi approved these changes

2023-11-09 11:44 UTC, merged