Configurable targeting prefix
prebid/prebid-server-java pull request #2769
Opened 2023-11-17 12:42 UTC by KolomiietsSerhii

2023-11-20 14:38 UTC, SerhiiNahornyi requested changes

2023-11-20 14:38 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/auction/TargetingKeywordsCreator.java
>       * Used as a value for HB_ENV_KEY.
Comment should be updated

2023-11-20 14:38 UTC, SerhiiNahornyi commented on src/test/java/org/prebid/server/auction/TargetingKeywordsCreatorTest.java
> +        final String expected = "test_";
customPrefix will be better name

2023-11-20 14:50 UTC, KolomiietsSerhii commented on src/main/java/org/prebid/server/auction/TargetingKeywordsCreator.java
>       * Used as a value for HB_ENV_KEY.
Done.

2023-11-20 14:51 UTC, KolomiietsSerhii commented on src/test/java/org/prebid/server/auction/TargetingKeywordsCreatorTest.java
> +        final String expected = "test_";
Done.

2023-12-07 10:03 UTC, SerhiiNahornyi approved these changes

2023-12-07 14:20 UTC, merged