Test: Filter multi format impressions
prebid/prebid-server-java pull request #2793
Opened 2023-11-27 19:15 UTC by marki1an

Tests for https://github.com/prebid/prebid-server-java/pull/2780

2023-11-28 22:02 UTC, Net-burst requested changes

2023-11-28 22:02 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/model/config/PreferredMediaType.groovy
> +    MediaType generic
It's per-bidder? Can we express it in a somewhat different way? Or at least make it obvious that it's a bidder. Dumb option would be to add some other bidders here. Other option is to make `AccountAuctionConfig` field for this a map of bidder to preferred media type.

2023-11-28 22:02 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/model/request/auction/Bidder.groovy
> +    Bidder bidder
You just lost me here. What is the point of recursion here?

2023-11-28 22:02 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/model/request/auction/Prebid.groovy
> +    Bidder bidders
We have the same object in several places?

2023-11-28 22:21 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/tests/FilterMultiFormatSpec.groovy
> +    def "PBS should response with all requested media type when default adapters multi format true in config and at account level specified preferred media type"() {
"PBS should response with all requested media type when default adapters multi format true in config and at account level specified preferred media type" -> "PBS should respond with all requested media types when default adapters multi format is true in config and preferred media type specified at account level"

There is a very similar grammar errors in all test names. Please proofread and correct them.

2023-12-06 15:43 UTC, osulzhenko requested changes

2023-12-06 15:43 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/model/bidder/Generic.groovy
> +import org.prebid.server.functional.model.response.auction.MediaType
unused import

2023-12-06 15:43 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/FilterMultiFormatSpec.groovy
> +        assert !bidResponse.ext?.warnings
```
If the request does not contain a preferred type:
The bidder will not be called and a warning will be returned.
```
https://github.com/prebid/prebid-server/issues/2711#issue-1677787288

`if a preferred mediatype is not specified, there's no default. The bid adapter may choke.`

https://github.com/prebid/prebid-server/issues/2711#issuecomment-1518069774

2023-12-07 09:57 UTC, merged