FreewheelSSP bidder updates
prebid/prebid-server-java pull request #2823
Opened 2023-12-06 18:41 UTC by KolomiietsSerhii

Added support of GPP, ZoneID support of Integer or String values.

2023-12-07 10:06 UTC, AntoxaAntoxic commented
@SerhiiNahornyi @KolomiietsSerhii This is the bidder that can be added as the alias for the generic bidder, isn't it?

2023-12-07 13:14 UTC, And1sS reviewed
In go version of bid adapter they also add this header
```go
headers.Add("Componentid", "prebid-go")
```
Which looks like an indicator that request comes from PBS-Go.

I guess we should check whether PBS-Java has to add similar indicator that request is coming from PBS-Java.

2023-12-08 10:47 UTC, SerhiiNahornyi requested changes

2023-12-08 10:47 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/bidder/freewheelssp/FreewheelSSPBidder.java
> +        headers.add("Componentid", "prebid-java");
Pls create constant of `"prebid-java"`

2023-12-08 10:47 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/bidder/freewheelssp/FreewheelSSPBidder.java
> +        headers.add("Componentid", "prebid-java");
Pld add test case for this change

2023-12-08 11:04 UTC, KolomiietsSerhii commented on src/main/java/org/prebid/server/bidder/freewheelssp/FreewheelSSPBidder.java
> +        headers.add("Componentid", "prebid-java");
Done.

2023-12-08 13:18 UTC, SerhiiNahornyi approved these changes

2023-12-08 13:19 UTC, merged