Nativo: Add adapter
prebid/prebid-server-java pull request #2827
Opened 2023-12-08 00:33 UTC by rafataveira

2023-12-08 10:42 UTC, SerhiiNahornyi requested changes

2023-12-08 10:42 UTC, SerhiiNahornyi commented on src/main/resources/bidder-config/generic.yaml
> +        vendor-id: 263
Wrong Identaion

2023-12-08 17:09 UTC, rafataveira commented on src/main/resources/bidder-config/generic.yaml
> +        vendor-id: 263
Fixed

2023-12-10 18:05 UTC, SerhiiNahornyi approved these changes

2023-12-11 10:41 UTC, merged