Liftoff Site Support
prebid/prebid-server-java pull request #2855
Opened 2023-12-21 10:11 UTC by AntoxaAntoxic

2023-12-29 11:41 UTC, marki1an submitted a review, later dismissed

2024-01-02 11:45 UTC, SerhiiNahornyi requested changes

2024-01-02 11:45 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/bidder/liftoff/LiftoffBidder.java
> +                .site(app == null ? null : site)
Looks like from Go, site will always be removed

2024-01-05 13:33 UTC, SerhiiNahornyi commented on src/test/resources/org/prebid/server/it/openrtb2/liftoff/test-auction-liftoff-request.json
> +  },
No need for empty site. Pls remove 

Also from bidRequest remove 
```json
"channel": {
        "name": "web"
      },
```

2024-01-05 13:35 UTC, SerhiiNahornyi approved these changes

2024-01-05 13:35 UTC, merged