Nativo: Added User Sync settings
prebid/prebid-server-java pull request #2879
Opened 2024-01-04 18:53 UTC by rafataveira

2024-01-05 12:07 UTC, AntoxaAntoxic approved these changes

2024-01-05 13:41 UTC, SerhiiNahornyi commented on src/main/resources/bidder-config/generic.yaml
> +          enabled: true
by default, enabled property has `true` value, so pls remove `enabled: true`

2024-01-09 22:06 UTC, rafataveira commented on src/main/resources/bidder-config/generic.yaml
> +          enabled: true
done

2024-01-17 10:32 UTC, AntoxaAntoxic approved these changes

2024-01-23 17:23 UTC, And1sS requested changes
Pls, add `enabled: true` or `enabled: false` to added `usersync` section. Thats why pipeline fails.

2024-01-23 17:24 UTC, SerhiiNahornyi commented
> Pls, add `enabled: true` or `enabled: false` to added `usersync` section. Thats why pipeline fails.

It is our internal bug that we don't support this default parameter, no changes needed for this PR

2024-01-23 19:26 UTC, rafataveira commented
@SerhiiNahornyi Thank you for reviewing this. Is there any timeline on when this PR will be merged?

2024-01-24 21:05 UTC, SerhiiNahornyi commented
> @SerhiiNahornyi Thank you for reviewing this. Is there any timeline on when this PR will be merged?

In a week, maybe earlier, we will have the bug fixed. 
As soon as it is fixed we will merge your PR.

2024-01-26 10:21 UTC, SerhiiNahornyi commented
Fix for mentioned bug
https://github.com/prebid/prebid-server-java/pull/2936

2024-01-26 13:54 UTC, merged