NextMillennium: add `extraInfo` support and update `yaml`
prebid/prebid-server-java pull request #2910
Opened 2024-01-17 12:41 UTC by marki1an

2024-01-17 17:49 UTC, KolomiietsSerhii submitted a review, later dismissed

2024-01-19 14:53 UTC, CTMBNara requested changes

2024-01-19 14:53 UTC, CTMBNara commented on src/main/java/org/prebid/server/bidder/nextmillennium/NextMillenniumBidder.java
> +                : null);
```
        if (CollectionUtils.isNotEmpty(nmmFlags)) {
            impExt.putObject("nextMillennium")
                    .set("nmmFlags", mapper.mapper().valueToTree(nmmFlags));
        }
```

2024-01-19 14:53 UTC, CTMBNara commented on src/main/java/org/prebid/server/bidder/nextmillennium/NextMillenniumBidder.java
> +
Please, remove empty line.

2024-01-19 14:53 UTC, CTMBNara commented on src/main/java/org/prebid/server/spring/config/bidder/NextMillenniumConfiguration.java
> +                    return new NextMillenniumBidder(config.getEndpoint(), mapper, extraInfo.getNmmFlags());
```
                .bidderCreator(config -> new NextMillenniumBidder(
                        config.getEndpoint(),
                        mapper,
                        config.getExtraInfo().getNmmFlags()))
```

2024-01-19 14:54 UTC, CTMBNara reviewed
Also remove `.filter(Objects::nonNull)` on line 70. This is redundant.

2024-01-23 14:47 UTC, CTMBNara approved these changes

2024-01-29 14:03 UTC, merged