Core: Add new `AdQuery` bidder
prebid/prebid-server-java pull request #2922
Opened 2024-01-23 07:40 UTC by marki1an

2024-01-31 09:49 UTC, AntoxaAntoxic requested changes

2024-01-31 09:49 UTC, AntoxaAntoxic commented on src/main/java/org/prebid/server/bidder/adquery/AdQueryBidder.java
> +        }
it's possible to join in a single stream: `formats.stream().map(...).collect(Collectors.joining("_"))`

2024-01-31 09:49 UTC, AntoxaAntoxic commented on src/main/java/org/prebid/server/bidder/adquery/AdQueryBidder.java
> +        return number != null ? number : 0;
`ObjectUtils.defaultIfNull(...)` and there is no need to have a separate method

2024-01-31 09:49 UTC, AntoxaAntoxic commented on src/main/java/org/prebid/server/bidder/adquery/AdQueryBidder.java
> +        if (Objects.nonNull(device) && StringUtils.isNotBlank(device.getIp()) && device.getIp().length() > 0) {
`Optional.ofNullable(device).map(Device::getIp).filter(StringUtils::isNotBlank).ifPresent(ip -> headers.add(...));`

2024-01-31 09:49 UTC, AntoxaAntoxic commented on src/main/java/org/prebid/server/bidder/adquery/model/response/AdQueryDataResponse.java
> +    String deadlid;
typo: `dealid`, and since it's the deal id, I prefer using camel case and then JsonProperty will be required

2024-01-31 09:49 UTC, AntoxaAntoxic commented on src/main/java/org/prebid/server/bidder/adquery/model/request/AdQueryRequest.java
> +    @JsonProperty("AdUnitCode")
a typo `adUnitCode`

P.S. please double-check the contract once more time for all the DTOs

2024-01-31 09:49 UTC, AntoxaAntoxic commented on src/main/java/org/prebid/server/bidder/adquery/model/request/AdQueryRequest.java
> +    String bidder;
redundant annotation

2024-01-31 09:49 UTC, AntoxaAntoxic commented on src/main/java/org/prebid/server/bidder/adquery/AdQueryBidder.java
> +                .price(BigDecimalParser.parse(data.getCpm()))
I believe we can expect BigDecimal on the DTOs side and let the jackson mapper do the job

2024-01-31 09:49 UTC, AntoxaAntoxic commented on src/main/java/org/prebid/server/bidder/adquery/AdQueryBidder.java
> +                .crid(String.format("%d", data.getCreationId()))
I believe we can expect String on the DTOs side and let the jackson mapper do the job

2024-01-31 09:49 UTC, AntoxaAntoxic commented on src/main/java/org/prebid/server/bidder/adquery/AdQueryBidder.java
> +                .adm(String.format(ADM_TEMPLATE, data.getAdqLib(), data.getTag()))
`ADM_TEMPLATE.formatted(...)`

2024-01-31 09:49 UTC, AntoxaAntoxic commented on src/main/java/org/prebid/server/bidder/adquery/AdQueryBidder.java
> +                .impid(resoleImpId(bidRequest, data))
a typo: `resolveImpId`

2024-01-31 09:49 UTC, AntoxaAntoxic commented on src/main/java/org/prebid/server/bidder/adquery/AdQueryBidder.java
> +        return Objects.nonNull(data.getRequestId())
please get rid of unnecessary using of `Objects.isNull` and `Objects.nonNull`

2024-01-31 09:49 UTC, AntoxaAntoxic commented on src/main/java/org/prebid/server/bidder/adquery/AdQueryBidder.java
> +        }
parsing can be done by the jackson on deserialization step, just expect Integer type in the DTO, thus this method is redundant

2024-01-31 09:49 UTC, AntoxaAntoxic commented on src/main/java/org/prebid/server/bidder/adquery/AdQueryBidder.java
> +        return data.getAdQueryMediaType().getName();
`return BidType.banner;`

2024-01-31 09:49 UTC, AntoxaAntoxic commented on src/main/java/org/prebid/server/bidder/adquery/AdQueryBidder.java
> +    private static BidType resolveMediaType(AdQueryDataResponse data) {
nitpick: you can pass here just media type instead of the whole data

2024-01-31 09:49 UTC, AntoxaAntoxic commented on src/main/java/org/prebid/server/bidder/adquery/model/request/AdQueryRequest.java
> +public class AdQueryRequest {
use just Value and Builder

2024-01-31 09:49 UTC, AntoxaAntoxic commented on src/test/java/org/prebid/server/bidder/adquery/AdQueryBidderTest.java
> +    private static BidderCall<AdQueryRequest> givenHttpCall(AdQueryRequest adQueryRequest, String body) {
the first parameter is always null, looks redundant

2024-01-31 09:49 UTC, AntoxaAntoxic commented on src/test/java/org/prebid/server/bidder/adquery/AdQueryBidderTest.java
> +                mapper.writeValueAsString(AdQueryResponse.of(AdQueryDataResponse.builder()
mapping and creating AdQueryResponse repeat in every test, maybe it's better to extract inside the givenHttpCall method

2024-02-01 08:37 UTC, AntoxaAntoxic requested changes

2024-02-01 08:37 UTC, AntoxaAntoxic commented on src/main/java/org/prebid/server/bidder/adquery/AdQueryBidder.java
> +            return "%sx%s".formatted(w, h);
looks like this pattern is used twice, make sense to extract as a constant

2024-02-01 08:37 UTC, AntoxaAntoxic commented on src/main/java/org/prebid/server/bidder/adquery/AdQueryBidder.java
> +    private MultiMap resolveHeader(Device device) {
`makeHeaders` makes more sense for me

2024-02-01 08:37 UTC, AntoxaAntoxic commented on src/main/java/org/prebid/server/bidder/adquery/AdQueryBidder.java
> +                StringUtils.isNotBlank(data.getCurrency()) ? data.getCurrency() : DEFAULT_CURRENCY));
let's resolve currency on the separate line

2024-02-01 08:37 UTC, AntoxaAntoxic commented on src/main/java/org/prebid/server/bidder/adquery/AdQueryBidder.java
> +    private static List<BidderBid> extractBids(AdQueryResponse adQueryResponse, BidRequest bidRequest) {
as I can see the whole bid request is not necessary to pass

2024-02-01 08:37 UTC, AntoxaAntoxic commented on src/main/java/org/prebid/server/bidder/adquery/AdQueryBidder.java
> +            throw new PreBidException(String.format("Unsupported MediaType: %s", mediaType.getName()));
imho it's better to use a single formatting style through the file

2024-02-01 08:37 UTC, AntoxaAntoxic commented on src/main/java/org/prebid/server/bidder/adquery/AdQueryBidder.java
> +                .ifPresent(ip -> headers.add(HttpUtil.X_FORWARDED_FOR_HEADER, device.getIp()));
.ifPresent(ip -> headers.add(HttpUtil.X_FORWARDED_FOR_HEADER, ip));

2024-02-01 08:37 UTC, AntoxaAntoxic commented on src/main/java/org/prebid/server/bidder/adquery/AdQueryBidder.java
> +        if (mediaType.getName() != BidType.banner) {
you expect the mediaType might be null earlier, but don't handle it here

2024-02-01 08:37 UTC, AntoxaAntoxic commented on src/main/java/org/prebid/server/bidder/adquery/AdQueryBidder.java
> +                .impIds(BidderUtil.impIds(bidRequest))
since we build one request per imp it should be `.impIds(Collections.singleton(imp.getId))`

2024-02-01 08:37 UTC, AntoxaAntoxic commented on src/test/java/org/prebid/server/bidder/adquery/AdQueryBidderTest.java
> +                .startsWith("Cannot deserialize value of type ");
these asserts can be done in a single chain

2024-02-01 08:37 UTC, AntoxaAntoxic commented on src/test/java/org/prebid/server/bidder/adquery/AdQueryBidderTest.java
> +                                .build()));
too deep intendations (it's better to have not more than 8 spaces), make sense to extract something to a separate variable

2024-02-05 13:19 UTC, AntoxaAntoxic submitted a review, later dismissed

2024-02-06 17:14 UTC, SerhiiNahornyi requested changes

2024-02-06 17:14 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/bidder/adquery/AdQueryBidder.java
> +    private MultiMap makeHeaders(Device device) {
Can be static

2024-02-06 17:14 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/bidder/adquery/AdQueryBidder.java
> +    private String getImpSizes(Imp imp) {
Can be static

2024-02-07 08:02 UTC, AntoxaAntoxic approved these changes

2024-02-07 10:15 UTC, SerhiiNahornyi approved these changes

2024-02-07 10:21 UTC, merged