Add DSA fields and validation
prebid/prebid-server-java pull request #2931
Opened 2024-01-25 10:30 UTC by AntoxaAntoxic

https://github.com/prebid/prebid-server/issues/3367

2024-02-04 11:16 UTC, SerhiiNahornyi submitted a review, later dismissed

2024-02-05 15:15 UTC, SerhiiNahornyi approved these changes

2024-02-05 16:53 UTC, Net-burst submitted a review, later dismissed
LGTM

2024-02-08 14:07 UTC, Net-burst requested changes

2024-02-08 14:07 UTC, Net-burst commented on src/main/java/org/prebid/server/proto/openrtb/ext/request/ExtRegsDsa.java
> +    Integer dsarequired;
Please follow Java code style and use @JsonProperty or use Jackson naming strategy

2024-02-08 14:07 UTC, Net-burst commented on src/main/java/org/prebid/server/proto/openrtb/ext/request/ExtRegsDsaTransparency.java
> +    List<Integer> dsaparams;
Please follow Java code style and use @JsonProperty or use Jackson naming strategy

2024-02-08 14:07 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/model/request/auction/DsaTransparency.groovy
> +    List<Integer> dsaparams
Please follow Java code style and use @JsonProperty or use Jackson naming strategy

2024-02-08 14:07 UTC, Net-burst commented on src/test/groovy/org/prebid/server/functional/model/request/auction/RegsDsa.groovy
> +    Integer dsarequired
Please follow Java code style.

2024-02-08 20:13 UTC, Net-burst approved these changes
LGTM

2024-02-12 14:27 UTC, merged