Add functional tests for support testing label header
prebid/prebid-server-java pull request #2963
Opened 2024-02-12 08:42 UTC by osulzhenko

2024-02-14 09:47 UTC, marki1an requested changes
What about this [requirement](https://github.com/prebid/prebid-server/issues/3297#:~:text=If%20the%20call%20to%20/cookie_sync%20doesn%27t%20contain%20an%20account%20ID%2C%20use%20the%20default%20account.%20We%20need%20to%20know%20if%20the%20account%20(or%20default%20account)%20wants%20this%20behavior.) ?

2024-02-14 09:47 UTC, marki1an commented on src/test/groovy/org/prebid/server/functional/tests/CookieSyncSpec.groovy
> +
Same empty line

2024-02-14 09:47 UTC, marki1an commented on src/test/groovy/org/prebid/server/functional/tests/CookieSyncSpec.groovy
> +    def "PBS should set cookie deprecation header from the default account when the accountId from the request is not matched"() {
when default account contain privacy sandbox

2024-02-14 09:47 UTC, marki1an commented on src/test/groovy/org/prebid/server/functional/tests/AuctionSpec.groovy
> +        def secCookieDeprecation = [(COOKIE_DEPRECATION_HEADER): PBSUtils.randomString]
Don't really need set sec-cookie-deprecation header when privacy sandbox is null or false

2024-02-16 14:27 UTC, AntoxaAntoxic requested changes

2024-02-16 14:27 UTC, AntoxaAntoxic commented on src/test/groovy/org/prebid/server/functional/tests/AuctionSpec.groovy
> +        then: "BidResponse should have device.ext.cdep from sec-cookie-deprecation header"
probably `BidderRequest should have...`, please check other places

2024-02-16 14:27 UTC, AntoxaAntoxic commented on src/test/groovy/org/prebid/server/functional/tests/AuctionSpec.groovy
> +    def "PBS should set device.ext.cdep from header when default account don't contain privacy sandbox and request account is empty"() {
`should not`

2024-02-16 14:27 UTC, AntoxaAntoxic commented on src/test/groovy/org/prebid/server/functional/tests/CookieSyncSpec.groovy
> +        assert extractCookieParameter(response.headers[SET_COOKIE_HEADER], 'Max-Age') == TimeUnit.DAYS.toSeconds(7) as Integer
I do not see any test that check the whole set-cookie header value

2024-02-19 13:14 UTC, AntoxaAntoxic approved these changes

2024-02-19 18:02 UTC, marki1an approved these changes

2024-02-20 14:48 UTC, merged