Fix VAST Tags
prebid/prebid-server-java pull request #3059
Opened 2024-03-15 11:24 UTC by AntoxaAntoxic

2024-03-15 13:28 UTC, CTMBNara commented on src/main/java/org/prebid/server/vast/VastModifier.java
> +            Pattern.compile("<\\s*wrapper(>|\\s+.*?>)", Pattern.CASE_INSENSITIVE);
`"<\\s*wrapper(?:>|\\s.*?>)"`
Same for others:
- capturing group -> non-capturing-group
- `\s+.*?` can be reduced to `\s.*?`

2024-03-18 14:40 UTC, CTMBNara requested changes

2024-03-18 14:40 UTC, CTMBNara commented on src/main/java/org/prebid/server/vast/VastModifier.java
> +                vastXml.substring(indexOfCloseTag, indexOfCloseTag + group.length());
Let's get rid of unnecessary searches and replacements:
- `vastXml.indexOf(group)` -> `matcher.start()`
- `vastXml.lastIndexOf(group)` -> `matcher.end()`
- `vastXml.replace(tag, impressionTag + tag)` -> `insertAt(...)`

General idea:
```
    private static String appendTrackingUrlToVastXml(String xml, String urlTracking, String bidder) {
        return appendTrackingUrl(xml, urlTracking, INLINE_OPEN_TAG_PATTERN, INLINE_CLOSE_TAG_PATTERN)
                .or(() -> appendTrackingUrl(xml, urlTracking, WRAPPER_OPEN_TAG_PATTERN, WRAPPER_CLOSE_TAG_PATTERN))
                .orElseThrow(() -> new PreBidException(
                        "VastXml does not contain neither InLine nor Wrapper for %s response".formatted(bidder)));
    }

    private static Optional<String> appendTrackingUrl(String vastXml,
                                                      String vastUrlTracking,
                                                      Pattern openTagPattern,
                                                      Pattern closeTagPattern) {

        final Matcher openTagMatcher = openTagPattern.matcher(vastXml);
        if (!openTagMatcher.find()) {
            return Optional.empty();
        }

        final Matcher impressionMatcher = IMPRESSION_CLOSE_TAG_PATTERN.matcher(vastXml);
        if (impressionMatcher.find()) {
            return Optional.of(insertAfterExistingImpressionTag(vastXml, vastUrlTracking, impressionMatcher));
        }

        final int openTagEnd = openTagMatcher.end();
        final Matcher closeTagMatcher = closeTagPattern.matcher(vastXml);
        if (!closeTagMatcher.find(openTagEnd)) {
            return Optional.of(vastXml);
        }

        return Optional.of(insertUrlTracking(vastXml, closeTagMatcher.start(), vastUrlTracking));
    }

    private static String insertAfterExistingImpressionTag(String vastXml,
                                                           String vastUrlTracking,
                                                           Matcher impressionMatcher) {

        int replacementEnd = impressionMatcher.end();
        while (impressionMatcher.find()) {
            replacementEnd = impressionMatcher.end();
        }

        return insertUrlTracking(vastXml, replacementEnd, vastUrlTracking);
    }

    private static String insertUrlTracking(String vastXml, int index, String vastUrlTracking) {
        final String impressionTag = "<Impression><![CDATA[" + vastUrlTracking + "]]></Impression>";
        return vastXml.substring(0, index) + impressionTag + vastXml.substring(index);
    }
```

2024-03-19 11:33 UTC, Net-burst approved these changes
LGTM

2024-03-19 11:46 UTC, CTMBNara approved these changes

2024-03-19 12:24 UTC, merged