Refine privacies
prebid/prebid-server-java pull request #3128
Opened 2024-04-18 15:08 UTC by CTMBNara

2024-05-07 16:21 UTC, osulzhenko requested changes

2024-05-07 16:21 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/privacy/CoppaSpec.groovy
> +        }
We should split it for more readability:
```
        then: "Bidder request should left ip and geo general data"
        def bidderRequest = bidder.getBidderRequest(bidRequest.id)
        verifyAll (bidderRequest.device) {
            ip == "43.77.114.0"
            ipv6 == "af47:892b:3e98:b400::"
            geo.lat == bidRequest.device.geo.lat.round(2)
            geo.lon == bidRequest.device.geo.lon.round(2)

            geo.country == bidRequest.device.geo.country
            geo.region == bidRequest.device.geo.region
            geo.utcoffset == bidRequest.device.geo.utcoffset
        }
        
        and: "should mask device personal data"
        verifyAll (bidderRequest.device) {
            !didsha1
            !didmd5
            !dpidsha1
            !ifa
            !macsha1
            !macmd5
            !dpidmd5
            !geo.metro
            !geo.city
            !geo.zip
            !geo.accuracy
            !geo.ipservice
            !geo.ext
        }
        
        and: "should mask user personal data"
        verifyAll (bidderRequest.user) {
            !id
            !buyeruid
            !yob
            !gender
            !eids
            !data
            !geo
            !ext
            !eids
            !ext?.eids
        }
```
Same for other cases

2024-05-07 16:21 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/privacy/CoppaSpec.groovy
> +        bidRequestWithGeo.tap {
should be `getBidRequestWithGeo()` this will fix build issue

2024-05-07 16:21 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitPreciseGeoActivitiesSpec.groovy
> +            bidderRequests.user.geo.lon == bidRequest.user.geo.lon
Due to the increasing of checks, we should also optimize and split it

2024-05-08 11:18 UTC, AntoxaAntoxic approved these changes

2024-05-08 11:53 UTC, osulzhenko submitted a review, later dismissed

2024-05-09 10:16 UTC, SerhiiNahornyi approved these changes

2024-05-09 10:22 UTC, merged