Add DSA Validations
prebid/prebid-server-java pull request #3133
Opened 2024-04-23 08:32 UTC by AntoxaAntoxic

2024-04-29 13:31 UTC, CTMBNara requested changes

2024-04-29 13:31 UTC, CTMBNara commented on src/main/java/org/prebid/server/auction/DsaEnforcer.java
> +                .orElse(null);
```
final Integer pubRender = bidRequest.getRegs().getExt().getDsa().getPubRender();
```

2024-04-29 13:31 UTC, CTMBNara commented on src/main/java/org/prebid/server/auction/DsaEnforcer.java
> +        }
```
        if (pubRender == DsaPublisherRender.WILL_RENDER.getValue()
                && adRender != null && adRender == DsaAdvertiserRender.WILL_RENDER.getValue()) {
            throw new PreBidException("DSA publisher and buyer both signal will render");
        }

        if (pubRender == DsaPublisherRender.NOT_RENDER.getValue()
                && (adRender == null || adRender != DsaAdvertiserRender.WILL_RENDER.getValue())) {
            throw new PreBidException("DSA publisher and buyer both signal will not render");
        }
```

2024-04-29 13:31 UTC, CTMBNara commented on src/main/java/org/prebid/server/proto/openrtb/ext/request/DsaPublisherRender.java
> +}
```
public enum DsaPublisherRender {

    NOT_RENDER(0),
    COULD_RENDER(1),
    WILL_RENDER(2);

    private final int value;

    DsaPublisherRender(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }
}
```

2024-04-29 13:31 UTC, CTMBNara commented on src/main/java/org/prebid/server/proto/openrtb/ext/response/DsaAdvertiserRender.java
> +}
```
public enum DsaAdvertiserRender {

    NOT_RENDER(0),
    WILL_RENDER(1);

    private final int value;

    DsaAdvertiserRender(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }
}

```

2024-04-29 13:31 UTC, CTMBNara commented on src/main/java/org/prebid/server/proto/openrtb/ext/request/DsaRequired.java
> +}
```
public enum DsaRequired {

    NOT_REQUIRED(0),
    SUPPORTED(1),
    REQUIRED(2),
    REQUIRED_ONLINE_PLATFORM(3);

    private final int value;

    DsaRequired(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }
}
```

2024-04-29 13:59 UTC, AntoxaAntoxic commented on src/main/java/org/prebid/server/auction/DsaEnforcer.java
> +        }
never mind

2024-05-27 13:59 UTC, CTMBNara requested changes

2024-05-27 13:59 UTC, CTMBNara commented on src/main/java/org/prebid/server/auction/DsaEnforcer.java
> +        this.mapper = mapper;
`Objects.requireNotNull()`

2024-05-27 13:59 UTC, CTMBNara commented on src/main/java/org/prebid/server/auction/DsaEnforcer.java
> +        validateFieldLength(dsaResponse);
not needed anymore, we already checked this earlier

2024-05-28 12:38 UTC, CTMBNara approved these changes

2024-05-29 11:54 UTC, merged