Stored Auction Response on Global Level
prebid/prebid-server-java pull request #3247
Opened 2024-06-18 10:55 UTC by AntoxaAntoxic

### 🔧 Type of changes
- [ ] new bid adapter
- [ ] update bid adapter
- [x] new feature
- [ ] new analytics adapter
- [ ] new module
- [ ] bugfix
- [ ] documentation
- [ ] configuration
- [ ] tech debt (test coverage, refactorings, etc.)

### ✨ What's the context?

What's the context for the changes? Are there any

### 🧠 Rationale behind the change

Why did you choose to make these changes? Were there any trade-offs you had to consider?

### 🧪 Test plan

How do you know the changes are safe to ship to production?

### 🏎 Quality check

- [ ] Are your changes following [our code style guidelines](https://github.com/prebid/prebid-server-java/blob/master/docs/developers/code-style.md)?
- [ ] Are there any breaking changes in your code?
- [ ] Does your test coverage exceed 90%?
- [ ] Are there any erroneous console logs, debuggers or leftover code in your changes?

2024-07-23 13:00 UTC, SerhiiNahornyi requested changes

2024-07-23 13:00 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
> +    SkipAuctionService skipAuctionService(StoredResponseProcessor storedResponseProcessor,
Maybe better `SkippedAuctionService`?

2024-07-23 13:06 UTC, AntoxaAntoxic commented on src/main/java/org/prebid/server/auction/SkipAuctionService.java
> +            if (seatBid == null) {
it's not applicable to a single object

2024-07-23 13:12 UTC, AntoxaAntoxic commented on src/main/java/org/prebid/server/auction/SkipAuctionService.java
> +            if (seatBid == null) {
and an empty list is a valid response

2024-07-24 09:25 UTC, SerhiiNahornyi approved these changes

2024-07-24 09:26 UTC, merged