Core: Module storage logic
prebid/prebid-server-java pull request #3248
Opened 2024-06-18 13:42 UTC by SerhiiNahornyi

### 🔧 Type of changes
- [ ] new bid adapter
- [ ] update bid adapter
- [x] new feature
- [ ] new analytics adapter
- [ ] new module
- [ ] bugfix
- [ ] documentation
- [ ] configuration
- [ ] tech debt (test coverage, refactorings, etc.)

### ✨ What's the context?

What's the context for the changes? Are there any

### 🧠 Rationale behind the change

Why did you choose to make these changes? Were there any trade-offs you had to consider?

### 🧪 Test plan

How do you know the changes are safe to ship to production?

### 🏎 Quality check

- [ ] Are your changes following [our code style guidelines](https://github.com/prebid/prebid-server-java/blob/master/docs/developers/code-style.md)?
- [ ] Are there any breaking changes in your code?
- [ ] Does your test coverage exceed 90%?
- [ ] Are there any erroneous console logs, debuggers or leftover code in your changes?

2024-06-29 11:41 UTC, CTMBNara requested changes

2024-06-29 11:41 UTC, CTMBNara commented on src/main/java/org/prebid/server/cache/BasicModuleCacheService.java
> +        } catch (Throwable e) {
Catch only `PreBidException`

2024-06-29 11:41 UTC, CTMBNara commented on src/main/java/org/prebid/server/cache/BasicModuleCacheService.java
> +
Please, remove empty line

2024-06-29 11:41 UTC, CTMBNara commented on src/main/java/org/prebid/server/cache/BasicModuleCacheService.java
> +        } catch (Throwable e) {
Same, catch only `PreBidException`

2024-06-29 11:41 UTC, CTMBNara commented on src/main/java/org/prebid/server/cache/BasicModuleCacheService.java
> +                        callTimeoutMs)
Please, arrange it like this:
```
httpClient.post(
                         endpointUrl.toString(),
                         securedCallHeaders(),
                         mapper.encodeToString(moduleCacheRequest),
                         callTimeoutMs)
```

2024-06-29 11:41 UTC, CTMBNara commented on src/main/java/org/prebid/server/cache/BasicModuleCacheService.java
> +                        callTimeoutMs)
Same here:
```
httpClient.get(
                         getRetrieveEndpoint(key, moduleCode, application),
                         securedCallHeaders(),
                         callTimeoutMs)
```

2024-06-29 11:41 UTC, CTMBNara commented on src/main/java/org/prebid/server/cache/BasicModuleCacheService.java
> +                        response.getStatusCode(), response.getBody()));
This can be one-lined.

2024-06-29 11:41 UTC, CTMBNara commented on src/main/java/org/prebid/server/cache/BasicModuleCacheService.java
> +                        response.getStatusCode(), response.getBody()));
This can be one-lined.

2024-06-29 11:41 UTC, CTMBNara commented on src/main/java/org/prebid/server/cache/BasicModuleCacheService.java
> +                                                      String responseBody) {
This, also, can be one-lined

2024-06-29 11:41 UTC, CTMBNara commented on src/main/java/org/prebid/server/cache/BasicModuleCacheService.java
> +        try {
Please, add empty line after multi-line declaration

2024-06-29 11:41 UTC, CTMBNara commented on src/main/java/org/prebid/server/cache/BasicModuleCacheService.java
> +        if (StringUtils.isBlank(key)) {
Please, add empty line after multi-line declaration

2024-06-29 11:41 UTC, CTMBNara commented on src/main/java/org/prebid/server/cache/BasicModuleCacheService.java
> +        return StringUtils.equals(moduleCacheResponse.getValue(), processedValue)
No need to compare using `equals`, just compare with `==`

2024-06-29 11:41 UTC, CTMBNara commented on src/main/java/org/prebid/server/cache/CoreCacheService.java
> +            JacksonMapper mapper) {
Don't think that we need this change :p

2024-06-29 11:41 UTC, CTMBNara commented on src/main/java/org/prebid/server/cache/CoreCacheService.java
> +                        mapper.encodeToString(bidCacheRequest),
```
httpClient.post(
                         endpointUrl.toString(),
                         CacheServiceUtil.CACHE_HEADERS,
                         mapper.encodeToString(bidCacheRequest)
```

2024-06-29 11:41 UTC, CTMBNara commented on src/main/java/org/prebid/server/cache/ModuleCacheService.java
> +            return Future.succeededFuture();
Please, add empty line after multi-line declaration

2024-06-29 11:41 UTC, CTMBNara commented on src/main/java/org/prebid/server/cache/proto/request/module/ModuleCacheType.java
> +    ModuleCacheType(final String text) {
Do you think this `final` modifier is necessary? XD

2024-06-29 11:41 UTC, CTMBNara commented on src/main/java/org/prebid/server/cache/proto/response/module/ModuleCacheResponse.java
> +    }
Just add static constructor via lombok.
And i don't see any other usage of builder for this object, maybe we don't need it?

2024-07-01 08:33 UTC, SerhiiNahornyi commented on src/main/java/org/prebid/server/cache/CoreCacheService.java
> +            JacksonMapper mapper) {
But we will have!)

2024-07-01 13:26 UTC, CTMBNara approved these changes

2024-07-03 07:34 UTC, merged