Add functional tests for additional SeatNonBid codes
prebid/prebid-server-java pull request #3340
Opened 2024-07-30 11:11 UTC by osulzhenko

### 🔧 Type of changes
- [ ] new bid adapter
- [ ] update bid adapter
- [ ] new feature
- [ ] new analytics adapter
- [ ] new module
- [ ] bugfix
- [ ] documentation
- [ ] configuration
- [ ] tech debt (test coverage, refactorings, etc.)

### ✨ What's the context?

What's the context for the changes? Are there any

### 🧠 Rationale behind the change

Why did you choose to make these changes? Were there any trade-offs you had to consider?

### 🧪 Test plan

How do you know the changes are safe to ship to production?

### 🏎 Quality check

- [ ] Are your changes following [our code style guidelines](https://github.com/prebid/prebid-server-java/blob/master/docs/developers/code-style.md)?
- [ ] Are there any breaking changes in your code?
- [ ] Does your test coverage exceed 90%?
- [ ] Are there any erroneous console logs, debuggers or leftover code in your changes?

2024-07-31 12:35 UTC, marki1an requested changes
Add test for this one code 201 Request Blocked - Unsupported Channel (app/site/dooh) - if the request was not sent to the bidder because they don’t support dooh or app.

2024-07-31 12:35 UTC, marki1an commented on src/test/groovy/org/prebid/server/functional/tests/SeatNonBidSpec.groovy
> +
Empty line

2024-07-31 12:35 UTC, marki1an commented on src/test/groovy/org/prebid/server/functional/tests/SeatNonBidSpec.groovy
> +            imp.ext.first
didn't get it

2024-07-31 12:37 UTC, marki1an requested changes

2024-07-31 12:37 UTC, marki1an commented on src/test/groovy/org/prebid/server/functional/tests/SeatNonBidSpec.groovy
> +            imp[0].secure = 1
And let's make it enum where 0 = non-secure, 1 = secure.

2024-08-01 13:38 UTC, osulzhenko commented
> Add test for this one code 201 Request Blocked - Unsupported Channel (app/site/dooh) - if the request was not sent to the bidder because they don’t support dooh or app.

Unfortunately, our current Java implementation does not support blocking requests based on channels like app, site, or dooh.

2024-08-02 09:53 UTC, marki1an requested changes

2024-08-02 09:55 UTC, marki1an requested changes

2024-08-02 09:55 UTC, marki1an commented on src/test/groovy/org/prebid/server/functional/model/config/Ortb2BlockingAttributes.groovy
> +@JsonNaming(PropertyNamingStrategies.KebabCaseStrategy)
We can remove @JsonNaming

2024-08-02 09:55 UTC, marki1an commented on src/test/groovy/org/prebid/server/functional/model/config/Ortb2BlockingConfig.groovy
> +@JsonNaming(PropertyNamingStrategies.KebabCaseStrategy)
Same here we can remove @JsonNaming

2024-08-09 12:56 UTC, marki1an approved these changes

2024-08-09 12:56 UTC, merged