New Adapter: TradPlus
prebid/prebid-server-java pull request #3361
Opened 2024-08-07 08:50 UTC by tradplus

TradPlus is a leading, stable, and reliable ad monetization platform that is committed to providing global developers with fair, transparent and efficient monetization solutions. We also provide ADX and Saas ADX services. We serve 2,000+ global developers. Moreover, Our SDK has been certified by IAB Tech Lab and also joins Google Play SDK Index. And we have Information Security Management Certification.

Our advertising business spans the world. This is our official website: https://tradplusad.com/en. You can get more details about TradPlus.

this is TradPlus adapter version 1.0.

Thank!

2024-08-07 13:00 UTC, AntoxaAntoxic requested changes

2024-08-07 13:00 UTC, AntoxaAntoxic commented on src/test/java/org/prebid/server/bidder/tradplus/TradPlusBidderTest.java
> +    }
accoding to the json scheme null is impossible as an accountId value, so it make sense to check when accountId is blank " "

2024-08-13 09:42 UTC, SerhiiNahornyi commented
@tradplus, could you please address the comments mentioned above?

2024-08-27 09:41 UTC, Compile-Ninja commented
@tradplus There are conflicts in this PR. In addition to addressing the comments above, could you please merge the master branch as well?

2024-09-12 13:17 UTC, closed without merging

2024-10-10 02:39 UTC, tradplus commented
the issue has been fixed, please reopen this PR.

2024-10-16 10:44 UTC, tradplus commented
A PR has been recreated：https://github.com/prebid/prebid-server-java/pull/3508.