Test: `analytics call per account`
prebid/prebid-server-java pull request #3445
Opened 2024-09-16 11:33 UTC by marki1an

### 🔧 Type of changes
- [ ] new bid adapter
- [ ] update bid adapter
- [ ] new feature
- [ ] new analytics adapter
- [ ] new module
- [ ] bugfix
- [ ] documentation
- [ ] configuration
- [ ] tech debt (test coverage, refactorings, etc.)

### ✨ What's the context?

What's the context for the changes? Are there any

### 🧠 Rationale behind the change

Why did you choose to make these changes? Were there any trade-offs you had to consider?

### 🧪 Test plan

How do you know the changes are safe to ship to production?

### 🏎 Quality check

- [ ] Are your changes following [our code style guidelines](https://github.com/prebid/prebid-server-java/blob/master/docs/developers/code-style.md)?
- [ ] Are there any breaking changes in your code?
- [ ] Does your test coverage exceed 90%?
- [ ] Are there any erroneous console logs, debuggers or leftover code in your changes?

2024-09-16 12:51 UTC, Compile-Ninja requested changes
We also need test cases to check that additional data is merged to `ext.prebid.analytics.<adapter-name>.*`

2024-09-17 13:14 UTC, osulzhenko requested changes

2024-09-17 13:14 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/AnalyticsSpec.groovy
> +    def "PBS shouldn't populate log analytics when log disabled in config and without account"() {
and what will be when it's disabled in global config, but enabled in account?

2024-09-18 12:37 UTC, osulzhenko approved these changes
LGTM

2024-09-18 12:41 UTC, merged