Response correction: Fix VAST matching
prebid/prebid-server-java pull request #3493
Opened 2024-10-09 11:40 UTC by And1sS

### 🔧 Type of changes
- [ ] new bid adapter
- [ ] update bid adapter
- [ ] new feature
- [ ] new analytics adapter
- [ ] new module
- [x] bugfix
- [ ] documentation
- [ ] configuration
- [ ] tech debt (test coverage, refactorings, etc.)

### ✨ What's the context?

Response correction module does not match VAST markup correctly.

2024-10-11 10:50 UTC, marki1an requested changes

2024-10-11 10:50 UTC, marki1an commented on src/test/groovy/org/prebid/server/functional/tests/module/responsecorrenction/ResponseCorrectionSpec.groovy
> +
Remove please empty line

2024-10-11 10:50 UTC, marki1an commented on src/test/groovy/org/prebid/server/functional/tests/module/responsecorrenction/ResponseCorrectionSpec.groovy
> +                "${PBSUtils.randomString}<${' ' * PBSUtils.getRandomNumber(0, 20)}VAST ${PBSUtils.randomString}",
Why 20 spaces, is it a restriction?

2024-10-11 15:13 UTC, marki1an submitted a review, later dismissed

2024-10-16 09:45 UTC, Compile-Ninja approved these changes

2024-10-16 09:45 UTC, merged