Tests: Bid Adjustments Feature
prebid/prebid-server-java pull request #3544
Opened 2024-11-11 08:36 UTC by osulzhenko

### 🔧 Type of changes
- [ ] new bid adapter
- [ ] update bid adapter
- [ ] new feature
- [ ] new analytics adapter
- [ ] new module
- [ ] bugfix
- [ ] documentation
- [ ] configuration
- [ ] tech debt (test coverage, refactorings, etc.)

### ✨ What's the context?

What's the context for the changes? Are there any

### 🧠 Rationale behind the change

Why did you choose to make these changes? Were there any trade-offs you had to consider?

### 🔎 New Bid Adapter Checklist
- [ ] verify email contact works
- [ ] NO fully dynamic hosts
- [ ] geographic host parameters are NOT required
- [ ] NO direct use of HTTP is prohibited - *implement an existing Bidder interface that will do all the job*
- [ ] if the ORTB is just forwarded to the endpoint, use the generic adapter - *define the new adapter as the alias of the generic adapter*
- [ ] cover an adapter configuration with an integration test

### 🧪 Test plan

How do you know the changes are safe to ship to production?

### 🏎 Quality check

- [ ] Are your changes following [our code style guidelines](https://github.com/prebid/prebid-server-java/blob/master/docs/developers/code-style.md)?
- [ ] Are there any breaking changes in your code?
- [ ] Does your test coverage exceed 90%?
- [ ] Are there any erroneous console logs, debuggers or leftover code in your changes?

2024-11-12 12:19 UTC, marki1an requested changes
Add a few test cases for /amp endpoint  if it's possible

2024-11-12 14:17 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/model/request/auction/BidAdjustment.groovy
> +    Integer version
https://github.com/prebid/prebid-server/issues/2085#:~:text=%22version%22%3A%201%2C%20%20//%20needed%20in%20case%20we%20extend%20to%20additional%20attributes%20someday

2024-11-13 09:19 UTC, marki1an requested changes

2024-11-13 09:19 UTC, marki1an commented on src/test/groovy/org/prebid/server/functional/tests/BidAdjustmentSpec.groovy
> +        and: "Bidder request should contain default c"
and: "Bidder request should contain default currency"

2024-11-13 09:19 UTC, marki1an commented on src/test/groovy/org/prebid/server/functional/tests/BidAdjustmentSpec.groovy
> +
Please remove empty line

2024-11-13 09:19 UTC, marki1an commented on src/test/groovy/org/prebid/server/functional/tests/BidAdjustmentSpec.groovy
> +        String errorMessage = "bid adjustment from request was invalid: the found rule [adjtype=${adjustmentType}, value=${adjustmentPrice}, currency=null] in banner.generic.* is invalid"
deff errorMessage

2024-11-13 09:19 UTC, marki1an commented on src/test/groovy/org/prebid/server/functional/tests/BidAdjustmentSpec.groovy
> +        and: "Should add a warning when in debug mode"
`PBs should emit logs`

2024-11-13 09:19 UTC, marki1an commented on src/test/groovy/org/prebid/server/functional/tests/BidAdjustmentSpec.groovy
> +    }
The last one should be
`STATIC         | MAX_STATIC_ADJUST_VALUE        | ANY              | BidRequest.defaultBidRequest`
Add just one test case with the average max rule value.

2024-11-13 09:19 UTC, marki1an commented on src/test/groovy/org/prebid/server/functional/tests/BidAdjustmentSpec.groovy
> +        response.seatbid.first.bid.first.price == convertCurrency(adjustedBidPrice, bidResponse.cur, bidRequest.cur.first)
please add assert key word before

2024-11-13 09:53 UTC, marki1an approved these changes

2024-11-13 09:57 UTC, merged