Module Execution Host Config Check
prebid/prebid-server-java pull request #3566
Opened 2024-11-21 13:57 UTC by AntoxaAntoxic

### 🔧 Type of changes
- [ ] new bid adapter
- [ ] update bid adapter
- [ ] new feature
- [ ] new analytics adapter
- [ ] new module
- [x] bugfix
- [ ] documentation
- [ ] configuration
- [ ] tech debt (test coverage, refactorings, etc.)

### ✨ What's the context?

What's the context for the changes? Are there any

### 🧠 Rationale behind the change

Why did you choose to make these changes? Were there any trade-offs you had to consider?

### 🔎 New Bid Adapter Checklist
- [ ] verify email contact works
- [ ] NO fully dynamic hosts
- [ ] geographic host parameters are NOT required
- [ ] NO direct use of HTTP is prohibited - *implement an existing Bidder interface that will do all the job*
- [ ] if the ORTB is just forwarded to the endpoint, use the generic adapter - *define the new adapter as the alias of the generic adapter*
- [ ] cover an adapter configuration with an integration test

### 🧪 Test plan

How do you know the changes are safe to ship to production?

### 🏎 Quality check

- [ ] Are your changes following [our code style guidelines](https://github.com/prebid/prebid-server-java/blob/master/docs/developers/code-style.md)?
- [ ] Are there any breaking changes in your code?
- [ ] Does your test coverage exceed 90%?
- [ ] Are there any erroneous console logs, debuggers or leftover code in your changes?

2024-11-27 16:21 UTC, CTMBNara requested changes

2024-11-27 16:21 UTC, CTMBNara commented on src/main/java/org/prebid/server/hooks/execution/HookStageExecutor.java
In this class,
 - for Entrypoint stage:
   - pass `(host) hooks.admin.module-execution`
 - for other stages:
   - create a copy of `account.hooks.admin.module-execution` (let's name it `moduleExecution` for reference)
   - if `isConfigToInvokeRequired == true`:
     - put entries with `key=KEY, value=true` if there is no such KEY for all the KEYs in `account.hooks.modules`
     - wrap `moduleExecution` with `DefaultedMap.defaultedMap(moduleExecution, false)`
   - put all the values from `(host) hooks.admin.module-execution` to `moduleExecution `

2024-11-29 12:24 UTC, CTMBNara requested changes

2024-11-29 12:24 UTC, CTMBNara commented on src/main/java/org/prebid/server/hooks/execution/HookStageExecutor.java
> +                .orElseGet(Collections::emptyMap);
`orElse(Collections.emptyMap())`,  because it doesn't create a new object.

2024-12-03 12:41 UTC, And1sS approved these changes

2024-12-04 14:59 UTC, CTMBNara approved these changes

2024-12-04 14:59 UTC, merged