Modules: AB testing
prebid/prebid-server-java pull request #3576
Opened 2024-11-22 23:46 UTC by CTMBNara

### 🔧 Type of changes
- [ ] new bid adapter
- [ ] update bid adapter
- [x] new feature
- [ ] new analytics adapter
- [ ] new module
- [ ] bugfix
- [ ] documentation
- [ ] configuration
- [ ] tech debt (test coverage, refactorings, etc.)

### ✨ What's the context?

What's the context for the changes? Are there any

### 🧠 Rationale behind the change

Why did you choose to make these changes? Were there any trade-offs you had to consider?

### 🔎 New Bid Adapter Checklist
- [ ] verify email contact works
- [ ] NO fully dynamic hosts
- [ ] geographic host parameters are NOT required
- [ ] NO direct use of HTTP is prohibited - *implement an existing Bidder interface that will do all the job*
- [ ] if the ORTB is just forwarded to the endpoint, use the generic adapter - *define the new adapter as the alias of the generic adapter*
- [ ] cover an adapter configuration with an integration test

### 🧪 Test plan

How do you know the changes are safe to ship to production?

### 🏎 Quality check

- [ ] Are your changes following [our code style guidelines](https://github.com/prebid/prebid-server-java/blob/master/docs/developers/code-style.md)?
- [ ] Are there any breaking changes in your code?
- [ ] Does your test coverage exceed 90%?
- [ ] Are there any erroneous console logs, debuggers or leftover code in your changes?

2024-11-27 11:14 UTC, And1sS requested changes

2024-11-27 11:14 UTC, And1sS commented on src/main/java/org/prebid/server/hooks/execution/provider/HookProviderFactory.java
> +}
Redundant abstraction. Please, remove entire class. Just use `new ABTestHookProvider<>(hookId -> hookCatalog.hookById(hookId, stage), abTests, context, mapper)` where needed. This is an overkill for now.

2024-11-27 11:14 UTC, And1sS commented on src/main/java/org/prebid/server/hooks/execution/v1/HookDecorator.java
> +}
Another one. I get the point in making hierarchy 'idiomatic', but this still looks like an overkill to me. Please, remove this.

2024-11-27 11:14 UTC, And1sS commented on src/main/java/org/prebid/server/hooks/execution/provider/ab/ABTestHookDecorator.java
> +public class ABTestHookDecorator<PAYLOAD, CONTEXT extends InvocationContext>
And then this becomes something like `ABTestedHook`, which will inform users that its actually a `decorator` and it adds `AB testing` functionality to some hook. So the code still will be written in idiomatic way.

2024-11-27 11:14 UTC, And1sS commented on src/main/java/org/prebid/server/hooks/execution/model/ABTest.java
> +    Integer percent;
Why not `percentActive`?

2024-11-27 11:14 UTC, And1sS commented on src/main/java/org/prebid/server/hooks/execution/provider/ab/ABTestHookDecorator.java
> +package org.prebid.server.hooks.execution.provider.ab;
Please, rename `ab` -> `abtest`.  Because its unclear what `ab` means without context.

2024-11-27 11:14 UTC, And1sS commented on src/main/java/org/prebid/server/hooks/execution/provider/HookProvider.java
> +}
This one is ok.

2024-11-27 15:08 UTC, And1sS submitted a review, later dismissed

2024-12-04 13:49 UTC, And1sS approved these changes

2024-12-04 16:11 UTC, osulzhenko approved these changes

2024-12-04 16:21 UTC, merged