Add adUnitCode to the imp.ext.prebid exception list
prebid/prebid-server-java pull request #3610
Opened 2024-12-10 08:51 UTC by AntoxaAntoxic

### 🔧 Type of changes
- [ ] new bid adapter
- [x] bid adapter update
- [ ] new feature
- [ ] new analytics adapter
- [ ] new module
- [ ] module update
- [ ] bugfix
- [ ] documentation
- [ ] configuration
- [ ] dependency update
- [ ] tech debt (test coverage, refactorings, etc.)

### ✨ What's the context?
https://github.com/prebid/prebid-server/issues/4077

### 🧠 Rationale behind the change
Why did you choose to make these changes? Were there any trade-offs you had to consider?

### 🔎 New Bid Adapter Checklist
- [ ] verify email contact works
- [ ] NO fully dynamic hostnames
- [ ] geographic host parameters are NOT required
- [ ] direct use of HTTP is prohibited - *implement an existing Bidder interface that will do all the job*
- [ ] if the ORTB is just forwarded to the endpoint, use the generic adapter - *define the new adapter as the alias of the generic adapter*
- [ ] cover an adapter configuration with an integration test

### 🧪 Test plan
How do you know the changes are safe to ship to production?

### 🏎 Quality check
- [ ] Are your changes following [our code style guidelines](https://github.com/prebid/prebid-server-java/blob/master/docs/developers/code-style.md)?
- [ ] Are there any breaking changes in your code?
- [ ] Does your test coverage exceed 90%?
- [ ] Are there any erroneous console logs, debuggers or leftover code in your changes?

2024-12-10 11:48 UTC, CTMBNara submitted a review, later dismissed

2025-01-06 14:45 UTC, Net-burst commented
Waiting for the final update from the committee.

2025-01-24 15:21 UTC, marki1an requested changes
@osulzhenko Please add functional tests for those requirments.
This is the proposed exception list for imp[].ext.prebid. Bidders receive the following:

```
adunitcode
storedrequest
is_rewarded_inventory
options.echovideoattrs
```

2025-01-27 13:50 UTC, marki1an approved these changes

2025-01-27 16:41 UTC, CTMBNara approved these changes

2025-01-28 13:36 UTC, merged