Fix #3574 add driftpixel userSync redirect url
prebid/prebid-server-java pull request #3613
Opened 2024-12-11 09:07 UTC by muuki88

### 🔧 Type of changes

- [x] configuration

### ✨ What's the context?

Ported from Go version: https://github.com/prebid/prebid-server/pull/3973

### 🧠 Rationale behind the change

Keep bidder implementations in sync

### 🧪 Test plan

:crossed_fingers: 

### 🏎 Quality check
- [x] Are your changes following [our code style guidelines](https://github.com/prebid/prebid-server-java/blob/master/docs/developers/code-style.md)?
- [ ] Are there any breaking changes in your code?
- [ ] Does your test coverage exceed 90%?
- [ ] Are there any erroneous console logs, debuggers or leftover code in your changes?

2024-12-11 13:09 UTC, muuki88 commented
Seems the currency service failed

```
2024-12-11T09:10:21.279Z  WARN 2065 --- [           main] o.p.s.c.CurrencyConversionService        : Error occurred while request to currency service

org.prebid.server.exception.PreBidException: HTTP status code 503
	at org.prebid.server.currency.CurrencyConversionService.processResponse(CurrencyConversionService.java:108)
	at io.vertx.core.impl.future.Mapping.onSuccess(Mapping.java:35)
````

2024-12-11 14:00 UTC, osulzhenko commented
@muuki88 We are not using external services in the current tests. Also, please update your redirect URL. It has some differences compared to Go version. You can refer to other bidders with similar configurations. For example, [Vidoomy](https://github.com/prebid/prebid-server-java/blob/master/src/main/resources/bidder-config/vidoomy.yaml)

2024-12-12 13:43 UTC, muuki88 commented
Done

2024-12-12 14:40 UTC, muuki88 commented
I'm confused why the tests fail :see_no_evil:

2024-12-12 18:38 UTC, marki1an commented
@muuki88 Hi, I found an issue that looks like:
`Property: adapters.driftpixel.usersync.redirect.supportCors
    Value: "null"
    Reason: must not be null
`

2024-12-12 23:53 UTC, muuki88 commented
Thanks a lot @marki1an 

I'll take a look. Should I research for a way to make the test output more accessible? There were quite a lot of exceptions that all seemed unrelated

2024-12-13 08:49 UTC, muuki88 commented
```
APPLICATION FAILED TO START
***************************

Description:

Binding to target org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'adapters.driftpixel' to org.prebid.server.spring.config.bidder.model.BidderConfigurationProperties failed:

    Property: adapters.driftpixel.usersync.redirect.supportCors
    Value: "null"
    Reason: must not be null


Action:

Update your application's configuration
```

Okay. This crashed the entire application start :see_no_evil:

2024-12-13 11:00 UTC, muuki88 commented
I'm not 100% sure that there are no external services involved :sweat_smile: 

```
org.prebid.server.hooks.modules.greenbids.real.time.data.v1.GreenbidsRealTimeDataProcessedAuctionRequestHookTest.callShouldFilterBiddersBasedOnModelWhenAnyFeatureNotAvailable -- Time elapsed: 2.842 s <<< ERROR!
java.io.FileNotFoundException: https://github.com/P3TERX/GeoLite.mmdb/releases/download/2024.12.13/GeoLite2-Country.mmdb
```

2024-12-13 11:03 UTC, AntoxaAntoxic requested changes

2024-12-13 11:03 UTC, AntoxaAntoxic commented on src/main/resources/bidder-config/driftpixel.yaml
> +        userMacro: "%USER_ID%"
```yaml
    usersync:
      cookie-family-name: driftpixel
      redirect:
        url: "https://sync.driftpixel.live/psync?t=s&e=0&gdpr={{gdpr}}&consent={{gdpr_consent}}&us_privacy={{us_privacy}}&cb={{redirect_url}}"
        support-cors: false
        uid-macro: '%USER_ID%'
```

2024-12-16 08:06 UTC, muuki88 commented
Thanks @AntoxaAntoxic for your patience :pray: 

I think there's still a problem unrelated to this change. I opened an issues #3629

2024-12-16 08:21 UTC, AntoxaAntoxic commented
Please merge the latest master

2024-12-17 07:52 UTC, AntoxaAntoxic commented
@muuki88 Not sure I have the rights to do it. @Net-burst can you assist on that?

P.S. The failed test is not related to your changes, so please ignore.

2024-12-17 07:54 UTC, AntoxaAntoxic approved these changes

2024-12-17 11:41 UTC, CTMBNara approved these changes

2024-12-17 11:41 UTC, merged