Test: `Transition PAAPI parameters`
prebid/prebid-server-java pull request #3634
Opened 2024-12-16 14:35 UTC by marki1an

### 🔧 Type of changes
- [ ] new bid adapter
- [ ] bid adapter update
- [ ] new feature
- [ ] new analytics adapter
- [ ] new module
- [ ] module update
- [ ] bugfix
- [ ] documentation
- [ ] configuration
- [ ] dependency update
- [x] tech debt (test coverage, refactorings, etc.)

### ✨ What's the context?
What's the context for the changes?

### 🧠 Rationale behind the change
Why did you choose to make these changes? Were there any trade-offs you had to consider?

### 🔎 New Bid Adapter Checklist
- [ ] verify email contact works
- [ ] NO fully dynamic hostnames
- [ ] geographic host parameters are NOT required
- [ ] direct use of HTTP is prohibited - *implement an existing Bidder interface that will do all the job*
- [ ] if the ORTB is just forwarded to the endpoint, use the generic adapter - *define the new adapter as the alias of the generic adapter*
- [ ] cover an adapter configuration with an integration test

### 🧪 Test plan
How do you know the changes are safe to ship to production?

### 🏎 Quality check
- [ ] Are your changes following [our code style guidelines](https://github.com/prebid/prebid-server-java/blob/master/docs/developers/code-style.md)?
- [ ] Are there any breaking changes in your code?
- [ ] Does your test coverage exceed 90%?
- [ ] Are there any erroneous console logs, debuggers or leftover code in your changes?

2024-12-16 14:37 UTC, marki1an commented
Corresponding issue https://github.com/prebid/prebid-server/issues/3536

2024-12-26 12:14 UTC, osulzhenko requested changes

2024-12-26 12:14 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/bidder/openx/OpenxSpec.groovy
> +        assert !metricsRequest["Some name of metric for dropped igb object"]
Move these stubs to a constant

2024-12-26 12:14 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/bidder/openx/OpenxSpec.groovy
> +        assert !pbsService.getLogsByValue("DROP igb obj")
Move these stubs to a constant

2024-12-26 12:14 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/bidder/openx/OpenxSpec.groovy
> +        assert metricsRequest["alerts.general" as String] == 1
assert metrics[ALERT_GENERAL.getValue()] == 1

2025-01-10 08:43 UTC, osulzhenko commented
Required update

2025-01-16 12:55 UTC, osulzhenko requested changes
we additionaly should verify:
- that aliases can request both original and iab formats.
- that if impId from configs and impId from the response are mismatched (including wildcards), nothing happens.
- that warnings are issued in debug mode, alert.general metrics are emitted.
- that interestGroupAuctionBuyer is ignored when provided by a bidder.
- that the server defaults to the original format if ext.prebid.paaformat is not set or is invalid.
- ensure that empty igs or igi arrays do not cause crashes or errors.

2025-01-16 12:55 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/bidder/openx/OpenxSpec.groovy
> +        assert interestGroupAuctionSeller.ext.adapter == bidResponse.seatbid[0].seat.value
we can change it to:
```        
verifyAll (response.ext.interestGroupAuctionIntent.interestGroupAuctionSeller.flatten() as List<InterestGroupAuctionSeller>) {
            it.impId == [impId]
            it.config == [fledgeConfig]
            it.impId == bidResponse.seatbid.seat.value
            it.impId == bidResponse.seatbid.seat.value
        }
```

2025-01-24 17:54 UTC, osulzhenko requested changes
we should also cover:
`
If there's no impid, then drop any igb objects from this entry. If any were dropped, mmit a warning in debug mode, log at N% sampling, and emit an alert.general metric.
`
and
```
Loop through the igb array
Add ext.bidder and ext.adapter to the igb entry
Add the igb entry to the global response entry
```

Rest is looking fine

2025-01-24 17:54 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/bidder/openx/OpenxSpec.groovy
> +        assert auctionConfigs[0].bidder == bidResponse.seatbid[0].seat.value
Can we replace this with:
assert auctionConfigs[0].bidder == OPENX_ALIAS
Easier to identify :)

2025-01-24 17:54 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/bidder/openx/OpenxSpec.groovy
> +                        interestGroupAuctionBuyer: [new InterestGroupAuctionBuyer()]
can we also add [] option?

2025-01-24 17:54 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/bidder/openx/OpenxSpec.groovy
> +        assert interestGroupAuctionSeller.ext.bidder == bidResponse.seatbid[0].seat.value
assert interestGroupAuctionSeller.ext.bidder == OPENX_ALIAS

2025-01-24 17:54 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/bidder/openx/OpenxSpec.groovy
> +    def "PBS should log error and not populated fledge impId when bidder respond with empty config"() {
not an empty config, but an empty impid

2025-01-27 13:40 UTC, merged