Test: Price floors max rules dimensions
prebid/prebid-server-java pull request #3646
Opened 2024-12-20 12:33 UTC by marki1an

### 🔧 Type of changes
- [ ] new bid adapter
- [ ] bid adapter update
- [ ] new feature
- [ ] new analytics adapter
- [ ] new module
- [ ] module update
- [ ] bugfix
- [ ] documentation
- [ ] configuration
- [ ] dependency update
- [ ] tech debt (test coverage, refactorings, etc.)

### ✨ What's the context?
What's the context for the changes?

### 🧠 Rationale behind the change
Why did you choose to make these changes? Were there any trade-offs you had to consider?

### 🔎 New Bid Adapter Checklist
- [ ] verify email contact works
- [ ] NO fully dynamic hostnames
- [ ] geographic host parameters are NOT required
- [ ] direct use of HTTP is prohibited - *implement an existing Bidder interface that will do all the job*
- [ ] if the ORTB is just forwarded to the endpoint, use the generic adapter - *define the new adapter as the alias of the generic adapter*
- [ ] cover an adapter configuration with an integration test

### 🧪 Test plan
How do you know the changes are safe to ship to production?

### 🏎 Quality check
- [ ] Are your changes following [our code style guidelines](https://github.com/prebid/prebid-server-java/blob/master/docs/developers/code-style.md)?
- [ ] Are there any breaking changes in your code?
- [ ] Does your test coverage exceed 90%?
- [ ] Are there any erroneous console logs, debuggers or leftover code in your changes?

2024-12-24 12:21 UTC, osulzhenko requested changes
Please add test cases that cover the following:

- request-level `max-schema-dims` config cannot be passed in the request; it must be specified as part of the account config (i.e., ignore `ext.prebid.floors.max-schema-dims`).
- default value for `max-schema-dims` is 3.
- What happens if both `fetch.max-schema-dims` and `max-schema-dims` are set with different values? Which one takes priority?

2024-12-24 14:34 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsFetchingSpec.groovy
> +        def bidRequest = BidRequest.getDefaultBidRequest(APP)
also why APP?

2025-01-07 12:05 UTC, osulzhenko requested changes

2025-01-07 12:05 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsFetchingSpec.groovy
> +    def "PBS should validate price-floor.max-schema-dims from account config"() {
`PBS should validate price-floor.max-schema-dims from account config and not reject entire auction` same for others

2025-01-07 17:10 UTC, osulzhenko requested changes
Also, please add some privacy methods for these counts:
```
foo.ext.prebid.floors.data.modelGroups[0].values.size()
boo.ext.prebid.floors.data.modelGroups[0].schema.fields.size()
```

2025-01-07 17:10 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsSignalingSpec.groovy
> +            ext.prebid.floors.maxSchemaDims = PBSUtils.randomNumber
because it can be flaky, pls add:
ext.prebid.floors.maxSchemaDims = PBSUtils.getRandomNumber(2)

2025-01-07 20:28 UTC, marki1an commented on src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsSignalingSpec.groovy
> +                         "exceeded its maximum number 1"]
we can't just replace with maxRules, since  
```
maxRules            | maxRulesSnakeCase
        1           | null
        null        | 1
```

2025-01-08 08:48 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsSignalingSpec.groovy
> +                "exceeded its maximum number 1")
Price floor schema dimensions ${getSchemaSize(bidRequest)}

2025-01-08 08:49 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsSignalingSpec.groovy
> +                         "exceeded its maximum number 1"]
Let's then make it constant

2025-01-08 08:53 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsSignalingSpec.groovy
> +            config.auction.priceFloors.fetch.maxSchemaDims = 1
config.auction.priceFloors.maxSchemaDims = getSchemaSize(bidRequest)
            config.auction.priceFloors.fetch.maxSchemaDims = getSchemaSize(bidRequest) - 1

2025-01-08 08:55 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsSignalingSpec.groovy
> +        accountDao.save(account)
Do we really need an account here, especially with negative maxSchemaDims?

2025-01-08 08:57 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsSignalingSpec.groovy
> +        accountDao.save(account)
Do we really need an account here, especially with negative maxSchemaDims?

2025-01-08 08:57 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsSignalingSpec.groovy
> +        accountDao.save(account)
I believe account have priority over default account

2025-01-08 09:54 UTC, osulzhenko approved these changes

2025-01-08 09:54 UTC, merged