Bad Input Error if pbjs s2s config contains alias configuration for a disabled adapter
prebid/prebid-server-java pull request #3650
Opened 2024-12-23 13:27 UTC by zxPhoenix

### 🔧 Type of changes
- [ ] new bid adapter
- [ ] bid adapter update
- [ ] new feature
- [ ] new analytics adapter
- [ ] new module
- [ ] module update
- [x] bugfix
- [ ] documentation
- [ ] configuration
- [ ] dependency update
- [ ] tech debt (test coverage, refactorings, etc.)

### ✨ What's the context?
Fix [issue #3592](https://github.com/prebid/prebid-server-java/issues/3592). Bad Input Error if pbjs s2s config contains alias configuration for a disabled adapter.
Move unknown bidder and bidder is deactivated errors to warnings level.
Add unknown_bidder and deactivated_bidder metrics
 

### 🧠 Rationale behind the change
Why did you choose to make these changes? Were there any trade-offs you had to consider?

### 🔎 New Bid Adapter Checklist
- [ ] verify email contact works
- [ ] NO fully dynamic hostnames
- [ ] geographic host parameters are NOT required
- [ ] direct use of HTTP is prohibited - *implement an existing Bidder interface that will do all the job*
- [ ] if the ORTB is just forwarded to the endpoint, use the generic adapter - *define the new adapter as the alias of the generic adapter*
- [ ] cover an adapter configuration with an integration test

### 🧪 Test plan
Changes are covered by unit tests.

### 🏎 Quality check
- [x] Are your changes following [our code style guidelines](https://github.com/prebid/prebid-server-java/blob/master/docs/developers/code-style.md)?
- [ ] Are there any breaking changes in your code?
- [x] Does your test coverage exceed 90%?
- [ ] Are there any erroneous console logs, debuggers or leftover code in your changes?

2025-01-17 13:58 UTC, CTMBNara requested changes

2025-01-17 13:58 UTC, CTMBNara commented on src/main/java/org/prebid/server/auction/requestfactory/VideoRequestFactory.java
> +                                initialAuctionContext.getAccount(),
`initialAuctionContext.getAccount()` will always return `null` here

2025-01-17 13:58 UTC, CTMBNara commented on src/main/java/org/prebid/server/metric/Metrics.java
> +    }
I don't like this solution. Someone can spam the server with invalid bidders and load the memory by creating new entries in the map (with many invalid bidders).

2025-01-17 14:00 UTC, CTMBNara commented on src/main/java/org/prebid/server/auction/requestfactory/VideoRequestFactory.java
> +                                initialAuctionContext.getAccount(),
I think we can accept it this way, since we haven't supported Video endpoint for many months now.

2025-01-31 09:07 UTC, osulzhenko commented
@zxPhoenix could you please update this PR?

2025-01-31 11:29 UTC, zxPhoenix commented
> @zxPhoenix could you please update this PR?

Sure. Sorry for the delay. I have prioritised this PR.

2025-02-07 13:46 UTC, CTMBNara requested changes

2025-02-07 13:46 UTC, CTMBNara commented on src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
> +            @Value("${settings.fail-on-unknown-bidders}") boolean failOnUnknownBidders) {
Please, add default values as on line above

2025-02-07 13:46 UTC, CTMBNara commented on src/main/java/org/prebid/server/validation/RequestValidator.java
> +                                 Metrics metrics, Account account) throws ValidationException {
No need to pass `Metrics` here, it's not a static method

2025-02-07 13:46 UTC, CTMBNara commented on src/main/java/org/prebid/server/validation/RequestValidator.java
> +                        alias, coreBidder);
```
"request.ext.prebid.aliases.%s refers to unknown bidder: %s".format(alias, coreBidder);
```

2025-02-07 13:46 UTC, CTMBNara commented on src/main/java/org/prebid/server/validation/RequestValidator.java
> +                        alias, coreBidder);
same here

2025-02-12 18:19 UTC, CTMBNara approved these changes

2025-02-14 14:17 UTC, merged