Test: Bidder specific `tmax`
prebid/prebid-server-java pull request #3651
Opened 2024-12-23 15:24 UTC by marki1an

### 🔧 Type of changes
- [ ] new bid adapter
- [ ] bid adapter update
- [ ] new feature
- [ ] new analytics adapter
- [ ] new module
- [ ] module update
- [ ] bugfix
- [ ] documentation
- [ ] configuration
- [ ] dependency update
- [x] tech debt (test coverage, refactorings, etc.)

### ✨ What's the context?
What's the context for the changes?

### 🧠 Rationale behind the change
Why did you choose to make these changes? Were there any trade-offs you had to consider?

### 🔎 New Bid Adapter Checklist
- [ ] verify email contact works
- [ ] NO fully dynamic hostnames
- [ ] geographic host parameters are NOT required
- [ ] direct use of HTTP is prohibited - *implement an existing Bidder interface that will do all the job*
- [ ] if the ORTB is just forwarded to the endpoint, use the generic adapter - *define the new adapter as the alias of the generic adapter*
- [ ] cover an adapter configuration with an integration test

### 🧪 Test plan
How do you know the changes are safe to ship to production?

### 🏎 Quality check
- [ ] Are your changes following [our code style guidelines](https://github.com/prebid/prebid-server-java/blob/master/docs/developers/code-style.md)?
- [ ] Are there any breaking changes in your code?
- [ ] Does your test coverage exceed 90%?
- [ ] Are there any erroneous console logs, debuggers or leftover code in your changes?

2024-12-24 15:48 UTC, osulzhenko requested changes

2025-01-07 16:43 UTC, osulzhenko requested changes

2025-01-07 16:43 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/TimeoutSpec.groovy
> +    @IgnoreRest
pls remove

2025-01-07 16:43 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/TimeoutSpec.groovy
> +    def "PBS should apply action bidder min timeout when adapters.generic.tmax-deduction-ms is big value"() {
Maybe `max`?:
"PBS should apply auction.biddertmax.max timeout when adapters.generic.tmax-deduction-ms exceeds valid top range"

2025-01-07 16:43 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/TimeoutSpec.groovy
> +    def "PBS should apply action bidder min timeout when adapters.generic.tmax-deduction-ms is big value"() {
also add case for:
`If bidder_specific_tmax < auction.biddertmax.min, bidder_specific_tmax = auction.biddertmax.min
`

2025-01-07 16:43 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/TimeoutSpec.groovy
> +        def pbsConfig = ["adapters.generic.tmax-deduction-ms": "0"] + PBS_CONFIG
what if `tmax-deduction-ms` will be negative?

2025-01-07 17:32 UTC, marki1an commented on src/test/groovy/org/prebid/server/functional/tests/TimeoutSpec.groovy
>          def pbsService = new PrebidServerService(pbsContainer)
We can't do this because of ( withCopyFileToContainer(MountableFile.forHostPath(defaultRequest), APP_WORKDIR))

2025-01-07 18:15 UTC, osulzhenko approved these changes

2025-01-07 18:16 UTC, merged