Test: `bidder aliases`
prebid/prebid-server-java pull request #3655
Opened 2024-12-30 15:58 UTC by marki1an

### 🔧 Type of changes
- [ ] new bid adapter
- [ ] bid adapter update
- [ ] new feature
- [ ] new analytics adapter
- [ ] new module
- [ ] module update
- [ ] bugfix
- [ ] documentation
- [ ] configuration
- [ ] dependency update
- [ ] tech debt (test coverage, refactorings, etc.)

### ✨ What's the context?
What's the context for the changes?

### 🧠 Rationale behind the change
Why did you choose to make these changes? Were there any trade-offs you had to consider?

### 🔎 New Bid Adapter Checklist
- [ ] verify email contact works
- [ ] NO fully dynamic hostnames
- [ ] geographic host parameters are NOT required
- [ ] direct use of HTTP is prohibited - *implement an existing Bidder interface that will do all the job*
- [ ] if the ORTB is just forwarded to the endpoint, use the generic adapter - *define the new adapter as the alias of the generic adapter*
- [ ] cover an adapter configuration with an integration test

### 🧪 Test plan
How do you know the changes are safe to ship to production?

### 🏎 Quality check
- [ ] Are your changes following [our code style guidelines](https://github.com/prebid/prebid-server-java/blob/master/docs/developers/code-style.md)?
- [ ] Are there any breaking changes in your code?
- [ ] Does your test coverage exceed 90%?
- [ ] Are there any erroneous console logs, debuggers or leftover code in your changes?

2025-01-02 12:44 UTC, osulzhenko requested changes

2025-01-02 12:44 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/ImpRequestSpec.groovy
> +        defaultPbsService.sendAuctionRequest(bidRequest)
why you change service here?

2025-01-02 12:44 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/model/bidder/BidderName.groovy
> +    GENER_X("gener_x"),
can we use `UNKNOWN` for tests?

2025-01-02 12:44 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/model/request/auction/Bidder.groovy
> +    Generic generX
same here. Can we just use `UNKNOWN`?

2025-01-02 12:44 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/AliasSpec.groovy
> +                 "adapters.openx.endpoint"                : "$networkServiceContainer.rootUri/openx/auction".toString()])
given: "PBs server with aliases config". Also pls add cleanup

2025-01-02 12:44 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/AliasSpec.groovy
> +    def "PBS should invoke as aliases when aliases isn't known and core bidder isn't specified"() {
PBS should invoke aliases when alias is unknown and no core bidder is specified

2025-01-02 12:44 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/AliasSpec.groovy
> +            ext.prebid.aliases = [("gener_x"): GENERIC]
should be enum

2025-01-02 12:44 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/AliasSpec.groovy
> +    def "PBS should invoke as aliases when aliases isn't known and core bidder is specified"() {
`PBS should invoke as aliases when alias is unknown and core bidder is specified`

2025-01-02 12:44 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/AliasSpec.groovy
> +    def "PBS should ignore aliases that have a base adapter"() {
PBS should ignore aliases for requests with a base adapter

2025-01-02 12:44 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/AliasSpec.groovy
> +                 "adapters.openx.endpoint": "$networkServiceContainer.rootUri/openx/auction".toString()])
given: "PBs server with aliases config". Also pls add cleanup

2025-01-02 12:44 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/AliasSpec.groovy
> +        assert responseDebug.httpcalls[OPENX.value]*.uri != responseDebug.httpcalls[GENERIC.value]*.uri
I assume that we should go with a safe approach and replace this check with verifying `uri`, because if something goes wrong and it returns null, for example, we will never know

2025-01-02 12:44 UTC, osulzhenko commented on src/test/groovy/org/prebid/server/functional/tests/AliasSpec.groovy
> +    def "PBS shouldn't invoking alias of openX when generic config take precedence"() {
It's not clear why it should be `generic`. Maybe:
`PBS should ignore alias logic when hardcoded alias endpoints are present`

2025-01-08 11:02 UTC, marki1an commented on src/test/groovy/org/prebid/server/functional/model/bidder/BidderName.groovy
> +    GENER_X("gener_x"),
Is it gonna be easy to understand the test case, same for comment below

2025-01-08 12:36 UTC, osulzhenko approved these changes

2025-01-08 12:36 UTC, merged