Add bid size and secure markup validations, controlled by host through configuration
prebid/prebid-server-java pull request #830
Opened 2020-07-28 14:19 UTC by schernysh

2020-11-12 11:14 UTC, DGarbar requested changes

2020-11-12 11:14 UTC, DGarbar commented on docs/metrics.md
> +- `account.<account-id>.validation_err.secure` - number of bids received from account with `<account-id>` that had insecure creative while in secure context
Probably you mean adapter.\<bidder-name>.**response**.**validation**.\<metric>`

2020-11-12 11:14 UTC, DGarbar commented on src/main/java/org/prebid/server/metric/ValidationErrorMetrics.java
> +package org.prebid.server.metric;
Unused class

2020-12-14 14:32 UTC, rpanchyk submitted a review, later dismissed

2020-12-14 14:33 UTC, DGarbar approved these changes

2020-12-17 13:13 UTC, rpanchyk approved these changes

2020-12-17 13:16 UTC, merged