include format targeting flag implemented
prebid/prebid-server-java pull request #845
Opened 2020-08-06 09:11 UTC by BraslavskiyAndrey

2020-08-31 11:55 UTC, DGarbar approved these changes

2020-11-26 13:42 UTC, rpanchyk requested changes

2020-11-26 13:42 UTC, rpanchyk commented on src/main/java/org/prebid/server/proto/openrtb/ext/response/BidType.java
> +        if (this == xNative) {
Can be transformed to ternary operation.

2020-11-26 13:42 UTC, rpanchyk commented on src/test/java/org/prebid/server/auction/AmpRequestFactoryTest.java
> +                .extracting(ExtRequestTargeting::getIncludeformat, ExtRequestTargeting::getPricegranularity)
Do we need to test price granularity here?

2020-11-26 13:42 UTC, rpanchyk commented on src/test/resources/org/prebid/server/it/amp/test-appnexus-bid-request.json
> +        "includeformat" : false
Do we want to add defaulting value in bidder request if incoming `includeformat` flag is not defined?

2020-12-15 12:34 UTC, rpanchyk requested changes

2020-12-15 12:34 UTC, rpanchyk commented on src/main/java/org/prebid/server/auction/TargetingKeywordsCreator.java
> +        if (StringUtils.isNotBlank(format) && BooleanUtils.toBooleanDefaultIfNull(includeFormat, false)) {
Can we use `BooleanUtils.isTrue(..)` instead?

2020-12-15 12:45 UTC, rpanchyk approved these changes

2020-12-15 12:46 UTC, merged