Log missing video size id for RubiconBidder
prebid/prebid-server-java pull request #877
Opened 2020-08-26 10:28 UTC by BraslavskiyAndrey

2020-08-27 15:41 UTC, rpanchyk approved these changes

2020-12-22 14:45 UTC, schernysh requested changes

2020-12-22 14:45 UTC, schernysh commented on src/main/java/org/prebid/server/bidder/rubicon/RubiconBidder.java
> +                    .video(makeVideo(imp.getVideo(), extRubicon.getVideo(), extPrebid,
Please consider passing whole `imp` and `site` to `makeVideo` and let this method pull out everything it needs from these objects.

2020-12-22 14:45 UTC, schernysh commented on src/main/java/org/prebid/server/bidder/rubicon/RubiconBidder.java
> +        if ((videoSizeId == null || videoSizeId == 0) && System.currentTimeMillis() % 100 == 0) {
Please consider using https://github.com/prebid/prebid-server-java/blob/c6c41014dd0a2627595653aba3fd7da1341d9a0e/src/main/java/org/prebid/server/log/ConditionalLogger.java#L79 or similar idea to implement logging.

2021-01-05 12:05 UTC, schernysh approved these changes

2021-01-14 12:32 UTC, merged