Implement new logic for video sizeId.
prebid/prebid-server-java pull request #931
Opened 2020-09-25 12:23 UTC by snahornyi

2020-09-25 13:04 UTC, rpanchyk requested changes
Nice job, thanks!
Let me be more strict and ask you to add the unit-test for the case when we have to set `video.size_id=203`.

2020-09-25 14:04 UTC, rpanchyk submitted a review, later dismissed

2021-01-13 12:42 UTC, DGarbar approved these changes

2021-01-14 15:33 UTC, rpanchyk approved these changes

2021-01-14 15:34 UTC, merged