Add log of request to adapter by specified bidder
prebid/prebid-server-java pull request #966
Opened 2020-10-20 13:16 UTC by DGarbar

It can be refactored after https://github.com/rubicon-project/prebid-server-java/pull/815 will be merged

2020-10-29 11:00 UTC, schernysh requested changes

2020-10-29 11:21 UTC, DGarbar commented on src/main/java/org/prebid/server/log/HttpInteractionLogger.java
> +            final Iterator<Map.Entry<String, JsonNode>> bidderParams = impExtBidder.fields();
nice

2020-10-29 11:36 UTC, schernysh approved these changes

2021-09-06 09:54 UTC, DGarbar commented
Probably whole httpInteraction endpoint could be rewritten with Modularity feature

2021-09-17 09:47 UTC, rpanchyk approved these changes

2021-09-17 09:54 UTC, merged